### ISSUE TITLE
Error: Plugin /homebridge/node_modules/homebridge-hue requires a HomeBridge version of ^0.4.22 which does not satisfy the current HomeBridge version of 0.4.20. You may need to upgrade your installation of HomeBridge.

### ISSUE THREAD

**Issue by kappes** [oznu/docker-homebridge#10]
Hey,
I'm running the latest version on a pi3

`$ docker-compose pull homebridge
Pulling homebridge (oznu/homebridge:raspberry-pi)...
raspberry-pi: Pulling from oznu/homebridge
Digest: sha256:5aa6177e2752a08ff1a8d8f27039d71c775d191d4da4c32fb09036a6ac349b31
Status: Image is up to date for oznu/homebridge:raspberry-pi`

but getting this error when trying to use the hue plugin:

`[7/10/2017, 4:00:04 AM] Error: Plugin /homebridge/node_modules/homebridge-hue requires a HomeBridge version of ^0.4.22 which does not satisfy the current HomeBridge version of 0.4.20. You may need to upgrade your installation of HomeBridge.`

Will you update?

**Comment by oznu** [comment]
Thanks for submitting this.

I'll update the image now now with a patch to ensure the Raspberry Pi / armhf builds get the latest version of homebridge on build as the x86_64 builds do.

**Comment by oznu** [comment]
The Raspberry Pi / armhf image has been updated to 0.4.22:

```
docker pull oznu/homebridge:raspberry-pi
```

And homebridge-hue is happy:

```
[7/10/2017, 5:22:44 AM] ---
[7/10/2017, 5:22:45 AM] Loaded plugin: homebridge-hue
[7/10/2017, 5:22:45 AM] Registering platform 'homebridge-hue.Hue'
[7/10/2017, 5:22:45 AM] ---
```

**Comment by kappes** [comment]
wow, super fast. thanks a lot!

**Comment by kappes** [comment]
sorry, been too fast. homebridge still seems to be outdated.

**Comment by oznu** [comment]
Are you sure you pulled the new image?

Just tested this on my rPi3:

```
pi@raspberrypi:~ $ docker pull oznu/homebridge:raspberry-pi
raspberry-pi: Pulling from oznu/homebridge
96598928ae71: Pull complete
d5d43adff404: Pull complete
363ef289f763: Pull complete
2efd0784b475: Pull complete
716abe9a3a54: Pull complete
a3ed95caeb02: Pull complete
18ad9f4783c9: Pull complete
b33a1f5df223: Pull complete
130cdd8a81d8: Pull complete
814b26732a0d: Pull complete
ad0a793b59c6: Pull complete
Digest: sha256:5ddeb60882c7d2796dc2be8baccdaa41a3927a6c66651b9a535434c97178bc7d
Status: Downloaded newer image for oznu/homebridge:raspberry-pi

pi@raspberrypi:~ $ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
oznu/homebridge     raspberry-pi        e57b98bca41c        45 minutes ago      334MB

pi@raspberrypi:~ $ docker run -d --name homebridge oznu/homebridge:raspberry-pi
1f26765df97e2224230cd5f079adc33729b5a66b8328693adfe82b8f56b0ed46

pi@raspberrypi:~ $ docker exec homebridge cat /usr/local/share/.config/yarn/global/node_modules/homebridge/package.json | grep version
  "version": "0.4.22"
```

**Comment by kappes** [comment]
I think the problem cascaded somehow. your image is up-to-date, but hue somehow ignored that. I repaired the bridge and now it's working. thanks again!
