### ISSUE TITLE
Node js

### ISSUE THREAD

**Issue by hessus99** [oznu/docker-homebridge#100]
how i can upgrade the latest node.js. now it`s version 8.10 and philips hue plugin doesn`t work because the nodejs have to be 8.11 or later. Thanx.

**Comment by oznu** [comment]
The latest version of the image comes with 8.11.1.

**Comment by hessus99** [comment]
I make a new installation (raspberry) put same issue. Philips Hue plugin doesn't work and it give the error message : [2018-5-6 11:11:42] Plugin /homebridge/node_modules/homebridge-hue requires Node version of ^8.11.1 which does not satisfy the current Node version of v8.10.0. You may need to upgrade your installation of Node.

**Comment by hessus99** [comment]
Thanks! Now it works!
