### ISSUE TITLE
witch version? 

### ISSUE THREAD

**Issue by henkied** [oznu/docker-homebridge#101]
HI All,

I use the no-avahi version for my synology. In the docker I see 2 versions appear, which should I use (see attachment).I want to use the 1.7. no-avahi version. How can I copy the settings from my old version. He continues to use the no-avahi version, see also attachment
<img width="453" alt="schermafdruk 2018-05-10 09 47 40" src="https://user-images.githubusercontent.com/20031014/39858908-4c3e728c-5438-11e8-85e8-11076efc29e4.png">
<img width="590" alt="schermafdruk 2018-05-10 09 46 16" src="https://user-images.githubusercontent.com/20031014/39858909-4c56bdce-5438-11e8-9b59-e81ba46c4222.png">

**Comment by oznu** [comment]
Hi @henkied,

Pick the `no-avahi` version, this is always the latest version available.

**Comment by oznu** [comment]
That's not a general report, it should only show up under the right circumstances. Upgrading existing containers using the Synology DSM GUI is a bit complicated. Can you delete your existing container entirely and recreate it? You won't loose any settings or homebridge config as long as you've mapped the `/homebridge` volume to a local path (such as `/volume1/docker/homebridge`),

**Comment by henkied** [comment]
I have removed the existing container and installed a new one, indeed this version is new. BUT, I can no longer approach homebridge. I have reset all settings. Do you have an idea
<img width="1421" alt="schermafdruk 2018-05-10 10 46 50" src="https://user-images.githubusercontent.com/20031014/39861034-9ea5acc8-543f-11e8-8daa-6fcfe08eac10.png">

**Comment by oznu** [comment]
Can you show me the Environment tab on the running docker container?

**Comment by henkied** [comment]
update: 
<img width="786" alt="schermafdruk 2018-05-10 10 50 10" src="https://user-images.githubusercontent.com/20031014/39861142-f98fdea6-543f-11e8-8ec0-795e7896cf69.png">
<img width="196" alt="schermafdruk 2018-05-10 10 50 04" src="https://user-images.githubusercontent.com/20031014/39861143-f9a66824-543f-11e8-85ae-b35d3de2818b.png">

**Comment by henkied** [comment]
<img width="611" alt="schermafdruk 2018-05-10 10 51 40" src="https://user-images.githubusercontent.com/20031014/39861195-287512c2-5440-11e8-9645-27b4e65f989b.png">
<img width="595" alt="schermafdruk 2018-05-10 10 51 34" src="https://user-images.githubusercontent.com/20031014/39861197-288b7184-5440-11e8-85ee-fc1e784df982.png">

**Comment by oznu** [comment]
I was about to ask if you used https://github.com/oznu/homebridge-syno-spk originally - based on the port in your screenshot. That changes things, and we need to cleanup a little to get things back to how they should be 😄.

1. Stop and uninstall the Homebridge SPK app from package centre.
2. In the Docker app in DSM remove any *Containers* for homebridge - delete them.
3. In the Docker app in DSM remove any *Images* for homebridge - delete them.
4. Install this again: https://github.com/oznu/homebridge-syno-spk

Hopefully once that is done everything will be back to normal. Next time you want to upgrade the Homebridge image you'll just have to go into the *DSM Package Centre* and `Stop` and `Run` the app. Every time you do this it checks for updates to the Docker image and downloads them if any are available.

**Comment by henkied** [comment]
WOW everything reinstalled, everything works perfectly again.

Many thanks again !!
