### ISSUE TITLE
Node 4.3 or later?

### ISSUE THREAD

**Issue by rnilssoncx** [oznu/docker-homebridge#103]
Is there any plan to update the node engine?  The automation switches plugin requires at least 9.3. 

https://github.com/grover/homebridge-automation-switches

**Comment by oznu** [comment]
This container is pinned to the LTS releases of Node.js. The next major upgrade to Node.js will be in October 2018.

https://github.com/nodejs/Release#release-schedule

The `homebridge-automation-switches` plugin works fine on node 8.11.2, likely the plugin author just set the version of node require to the version they tested it on. Using `npm` the plugin installs correctly, using `yarn` the plugin will fail to install as `yarn` validates the node requirements more strictly.

**Comment by rnilssoncx** [comment]
Thanks!  That was what I needed.
