### ISSUE TITLE
Enable SSL for homebridge-config-ui-x

### ISSUE THREAD

**Issue by Djelibeybi** [oznu/docker-homebridge#106]
On a standard Homebridge install, it's possible to enable SSL for `homebridge-config-ui-x` by adding an `ssl` block to the `config.json`.

Is there any way to do the same with the Docker image? If not, can this be considered an enhancement request? :)

**Comment by oznu** [comment]
Hi @Djelibeybi,

As long as you're running the latest version of this image, you can now use the `config.json` file to configure most settings for `homebridge-config-ui-x` as described in that plugins documentation.

You can use the config GUI to do this, *Plugins Screen* -> Config UI Plugin -> Settings.

If you do not see the screen in the image below, you need to upgrade your docker image. Don't try and just add the platform for `homebridge-config-ui-x` in your `config.json` manually if this is the case, otherwise you'll break things. 

Make sure you set the port correctly when using this screen for the first time. It might not default to the port you're currently using. Also, certain settings are not required in the `config.json` as these are enforced at runtime, such as the log settings, sudo flag, and the restart command.

Now, to add your SSL certificates you need to copy them into your locally mounted homebridge volume, then enter the full path relative to the container, which would be something like this:

```
/homebridge/my-cert.pem
/homebridge/my-cert.key
```

Once SSL is enabled you will only be able to access the UI over https, so after you restart homebridge you'll need to manually amend the url in the browser.

![image](https://user-images.githubusercontent.com/3979615/40700701-fde031fc-641d-11e8-96f1-79e5af37036c.png)

**Comment by Djelibeybi** [comment]
Works perfectly.  I didn't notice the new Settings option in the config-ui-x plugin. That's really nifty.

**Comment by ocsele** [comment]
Dear @oznu , I'm new into homebridge, but learning fast. I'd like to access Homebridge config outside of my LAN (port alternated from outside, working fine over plain html), and would like to turn on SSL, but I'm missing this SSL part of the Settings in config-ui-x, where I should enter the path to my copied Let's encrypt cert files. Why could I miss this block, and how should I enable SSL in my case?

I'm running Homebridge on Syno DSM 6.2.2-24922 Update 4, in Docker from your repo (installed via your syno package), config-ui-x version is 4.8.1

Screenshot of settings of configui:
![kép](https://user-images.githubusercontent.com/60293567/73123071-f1536580-3f8b-11ea-8049-4d071e485dfe.png)

**Comment by JLafranca** [comment]
Dear @oznu , I have the same 'problem' as @ocsele , I don't see the option to input the pathways to the certificate. I am running HomeBridge 1.3.4

Could you assist?

**Comment by rweckhoff** [comment]
> Dear @oznu , I have the same 'problem' as @ocsele , I don't see the option to input the pathways to the certificate. I am running HomeBridge 1.3.4
> 
> Could you assist?

It's not in the UI for Docker.  Add it to your config file (I've mounted a RO /certs to the container):

    "platforms": [
        {
            "name": "Config",
            "port": 11733,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto",
            **"ssl": {
                "key": "/certs/your.key",
                "cert": "/certs/your.cert"
            },**
            "platform": "config"
        },

**Comment by HolgerAusB** [comment]
I know, this is an old issue. In my non-docker Homebridge 1.5.0 there is no SSL-setup in the UI, so I edited the config manually. And it works good so far.

But now I wanted to monitor the HB with [uptime-kuma](https://github.com/louislam/uptime-kuma). Even when I check the "Ignore TLS/SSL-Errors" it does not prove that HB-server is up. So I tried to curl the page from a different linux machine and get errors too:

```
user@raspi99:~ $ curl -i -v https://hb.example.com:8581/login
*   Trying 192.168.xx.xx:8581...
* Connected to hb.example.com (192.168.xx.xx) port 8581 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

And openssl show:
```
user@raspi99:~ $ openssl s_client -showcerts -servername hb.example.com -connect hb.example.com:8581
CONNECTED(00000003)
depth=0 CN = *.example.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = *.example.com
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN = *.example.com
verify return:1
---
Certificate chain
 0 s:CN = *.example.com
   i:C = US, O = Let's Encrypt, CN = R3
-----BEGIN CERTIFICATE-----
MI..............
..MANY LINES....
...............=
-----END CERTIFICATE-----
---
Server certificate
subject=CN = *.example.com

issuer=C = US, O = Let's Encrypt, CN = R3

---
No client certificate CA names sent
Peer signing digest: SHA384
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1535 bytes and written 382 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 384 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 21 (unable to verify the first certificate)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: FD...
	Session-ID-ctx:
    Resumption PSK: 83...
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - de ..
    0010 - ..
    0020 - ..
    0030 - ..
    0040 - ..
    0050 - ..
    0060 - ..
    0070 - ..
    0080 - ..
    0090 - ..
    00a0 - ..
    00b0 - ..
    00c0 - ..
    00d0 - 9c ..

    Start Time: 1655966452
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 72...
    Session-ID-ctx:
    Resumption PSK: 4C...
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
	0000 - de ..
    0010 - ..
    0020 - ..
    0030 - ..
    0040 - ..
    0050 - ..
    0060 - ..
    0070 - ..
    0080 - ..
    0090 - ..
    00a0 - ..
    00b0 - ..
    00c0 - ..
    00d0 - a9 ..
	
    Start Time: 1655966452
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
```
I need to mention that certbots works on a different machine. It gets a letsencrypt-cert for the wildcard-domain *.example.com and after each renewal a post-hook script is uploading /etc/letsencrypt/live/example.com/ via `scp -r` to the hb-machine. On the hb machine I set the rights to a special user&group sslcert:sslcert and put the user homebridge to that group, so it has access.

## How can I fix that cert problem?
