### ISSUE TITLE
avahi services

### ISSUE THREAD

**Issue by ivanhoe37** [oznu/docker-homebridge#108]
Hi, 
with other images I can map the path /etc/avahi to my local path, to execute additional services listed under the /services directory.
With you image, it maps and reads the services correctly but only publish them when I edit some file under /etc/avahi, even not modifying anything.

for examples, with MQTT, it shows:
 - Loading service file /etc/avahi/services/mosquitto.service.

when I modify any file:
 - Files changed, reloading.
 - Service "MQTT on TinkerServer" (/etc/avahi/services/mosquitto.service) successfully established.

**Comment by oznu** [comment]
The avahi service is configured to be as minimal as possible.

https://github.com/oznu/docker-homebridge/blob/master/root/defaults/avahi-daemon.conf

You can overwrite this file with your own config options from here which will probably be required to change the behaviour to be what you want.

https://www.systutorials.com/docs/linux/man/5-avahi-daemon.conf/

Map your local `avahi-daemon.conf` to `/defaults/avahi-daemon.conf` as this file is copied to `/etc/avahi-daemon.conf` every time the container starts/restarts.
