### ISSUE TITLE
Host name conflict ?

### ISSUE THREAD

**Issue by edwardbattistini** [oznu/docker-homebridge#109]
I have this showing up in the terminal. 
Is it normal ?

I have managed to add Homebridge to my Home app. But can't do much...

Any idea ? I have attached a screen grab

<img width="667" alt="screen shot 2018-06-30 at 20 11 48" src="https://user-images.githubusercontent.com/6288298/42128377-d9cfeca2-7ca1-11e8-99bd-66eb86d35632.png">

**Comment by oznu** [comment]
Please try using the `no-avahi` tag or disabled the avahi/bonjour process running on the host.
