### ISSUE TITLE
Homebridge not showing up in home.app

### ISSUE THREAD

**Issue by sylarevan** [oznu/docker-homebridge#110]
Hi there,

I'm not able to add homebridge in the apple home app : it does not appears at all. So far I'm using a pretty standard setup, running on a Synology NAS (with DSM 6.1.7-15284 Update 1). Here is my config files :

package.json:
```
{
  "dependencies": {
    "homebridge-dummy": "^0.2.0"
  }
}
```

config.json:
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file.",

    "accessories": [
    	{
          "accessory": "DummySwitch",
          "name": "My Switch",
          "stateful": true
        }  
    ],

    "platforms": [
    ]
}
```
DSM_HOSTNAME environment variable is tuned correctly.

Nothing strange in log files so far. Using a bonjour browser on my iPhone does not show any homekit capabilities from my NAS IP ... 

I have no idea on how to debug this. Do you have some suggestions? Thanks.

**Comment by oznu** [comment]
Please make sure you have enabled host networking.

You might also consider trying https://github.com/oznu/homebridge-syno-spk which will get everything setup correctly in far fewer steps.

**Comment by elmocito** [comment]
I tried the SPK version, but it not finding anything...
Tried to change the username, pin, (reboot, deleting the files in the docker folder, etc. etc.)...
Running it through the host network...
