### ISSUE TITLE
A build with Node.js 10.x

### ISSUE THREAD

**Issue by rbhr** [oznu/docker-homebridge#112]
Hey oznu

First of all, I love what you have built here. I run a bunch of them on RPi, DSM & VMs and have finally been able to push it to some friends who prior to this would have buggered it up or had no clue. I would love you to add a buy me a beer/coffee button.

Would you be able to add a Node.js 10.x build to your CI pipeline? I have two things that need 10.x now. If not, no probs.

Thanks
Richard

**Comment by oznu** [comment]
This image is uses the Node.js LTS builds. 10.x will land in October 2018.

https://github.com/nodejs/Release

However you can upgrade the image to version 10.x by executing these commands inside the container if you wish:

```shell
# remove existing version of npm
rm -rf $(npm -g prefix)/lib/node_modules/npm

# replace x86_64 with arm or aarch64 in the next two commands if required
curl -fLO https://github.com/oznu/alpine-node/releases/download/10.6.0/node-v10.6.0-linux-x86_64-alpine.tar.gz
tar -xzf node-v10.6.0-linux-x86_64-alpine.tar.gz -C /usr --strip-components=1 --no-same-owner

# rebuild homebridge
cd $(npm -g prefix)/lib/node_modules
npm rebuild

# rebuild plugins
cd /homebridge
npm rebuild
```
