### ISSUE TITLE
Use with cluster and Portainer

### ISSUE THREAD

**Issue by lespatots** [oznu/docker-homebridge#114]
I would like to use a raspberry pi cluster for running Homebridge, particularly as I would like to run a few Homebridge configurations. The reason for this is that I'm managing two locations (later three) and I would also like segregate some homebridge plugins (Harmony is one) to avoid losing all Homebridge services after a failure.

Where would I put the config.json file for each config and how to reference it. I did manage to setup ports and differing Homekit id on standalone pi's but that isn't really the way to go. I guess the main issue is persistance?

**Comment by oznu** [comment]
>  I guess the main issue is persistence?

You're on the right track. Just map the `/homebridge` mount to different paths on the host and it all should work.
