### ISSUE TITLE
http Request sent delayed 

### ISSUE THREAD

**Issue by ipa64** [oznu/docker-homebridge#116]
Hello,
Thanks for your work, I used your homebridge with LIFX plugins with success for a while now.
Recently I have added homebridge-http to use an ESP8266 relay, all seems to works well, but there is a strange behavior: 
If I send orders frequently ( from HomeKit ) all is working well, by frequently I mean less than 3 minutes.
if I don’t send an order for at least 5 minutes or more, after this period there is a hang-up, the order is sent but after about 20 seconds !
I have tried homebridge-http-switch, same behavior.
Thanks for advice

**Comment by oznu** [comment]
This does seem like odd behaviour. Have you made sure the ESP8266 and/or the homebridge server is not going to sleep? Or that the ESP8266 is not going into low power mode?

**Comment by ipa64** [comment]
To check that his what I did:
Wait for at least 5 minutes then
- I send a http request by another way to theESP8266, it responds immediately.
- Homekit: I tried to manipulate an homebridge-LIFX accessory it works immediately.
- Homekit: I tried to manipulate the ESP8266  accessory, hang-up for about 20 seconds before the board receive the request. 
After that I can manipulate again the Esp8266 accessory and it receive requests immediately.

**Comment by oznu** [comment]
Not sure what else to check. I've got a few ESP8266's doing various things around the house. I used to control them all via standard HTTP requests from this docker image (be it using my own custom plugins, not homebridge-http); and never experienced these delays regularly.

Instead now I have a WebSocket server running on the ESP8266 which allows me to maintain instant two way communication between Homebridge to the microcontroller. I have found this provided the most responsive and reliable experience, examples here:

https://github.com/oznu/homebridge-esp8266-fan
https://github.com/oznu/homebridge-daikin-esp8266

**Comment by ipa64** [comment]
Interesting I will try this way

**Comment by oznu** [comment]
No problem, otherwise the author of the homebridge-http plugin might be able to help more than I can with this one. 😄

**Comment by ipa64** [comment]
Ok I did it based on your home bridge-esp8266-fan
Now it's working very well !
Thank you
