### ISSUE TITLE
Homebridge not running on startup

### ISSUE THREAD

**Issue by misterd4n** [oznu/docker-homebridge#119]
Hello,

Installed docker-homebridge on LibreELEC using this guide from the wiki:
https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-LibreELEC

I installed the image using the no-avahi-raspberry-pi tag.

Everything works great, except when I reboot the pi 3. When the pi reboots, I can access the configuration page on port 8581, however, homebridge does not start. I have to restart the container for it to finally work.

Any idea why this happens? I looked everywhere on the wiki and in closed issues to find a similar problem.

Any help would be appreciated. Attached are the logs.
[log.txt](https://github.com/oznu/docker-homebridge/files/2276374/log.txt)

**Comment by oznu** [comment]
Can you provide the container logs?

```
docker logs homebridge
```

**Comment by misterd4n** [comment]
There you go. This is what I have in the logs.

In the configuration page, it says that homebridge is not started and in the home app, all my accessories appear with "No response" until I restart the container inside the configuration page.

Once the container is restarted manually, everything works until I restart the pi 3.

[log.txt](https://github.com/oznu/docker-homebridge/files/2279843/log.txt)

**Comment by oznu** [comment]
The logs look fine. Are you using WiFi?

I'm thinking homebridge might be starting before your WiFi connection is up so it's not broadcasting on that interface.

**Comment by misterd4n** [comment]
Yes, I am using wifi. Is there a way to delay the start of the container until the wifi connection is made?

**Comment by oznu** [comment]
You can delay starting homebridge inside the container.

Add this to the bottom of the`startup.sh` script:

```
sleep 30
```

The `startup.sh`script was created in the same folder as your `config.json`, you can also edit it via the GUI by clicking the Docker menu item and selecting `Startup Script`.

30 seconds should be more than enough, but if that doesn't work try 60.

**Comment by misterd4n** [comment]
Hello again,

I've tried this option up, tried sleep up to 120 seconds in the startup script and unfortunately, it does not seem to help. I still have to restart the Homebridge container manually.

**Comment by misterd4n** [comment]
I added two echo commands to the startup script to see where the sleep command happens.
This what I get. I don't understand what I am doing wrong.

Here is the log.
[log.txt](https://github.com/oznu/docker-homebridge/files/2280675/log.txt)

**Comment by misterd4n** [comment]
Yeah, I ended up doing something pretty similar.

I added this line to the /storage/.config/autostart.sh:

sleep 60 && docker restart homebridge &

30 seconds was not enough in my case.

Hope it helps someone else.

**Comment by allwyn007** [comment]
i have the same issue i tried to add the line in  /storage/.config/autostart.sh . but it says no such file or directory
