### ISSUE TITLE
I want use homebridge-apple-tv...

### ISSUE THREAD

**Issue by rubyon** [oznu/docker-homebridge#120]
I want use homebridge-apple-tv...

but...

how can I do input pairing code ?

I want all service stop...

and start manually in Docker shell...

**Comment by rubyon** [comment]
I do it myself

s6-svscanctl -t /var/run/s6/services

and

homebridge -U /homebridge -P /homebridge/node_modules -C

and... pairing OK

**Comment by Pensive** [comment]
tried 
`pidof homebridge`

followed by 
`kill xxx`

where xx is the homebridge process. no joy :(

**Comment by Pensive** [comment]
OK - i gave up trying to do this on the actual synology docker.

Eventually I just ran a new instance of homebridge on my macbook in a terminal window, installed the homebridge-apple-tv plugin and ran it on that. Once I had paired i just pasted those credentials into my synology homebridge config, and killed the temporary instance of homebridge. That worked for me.

You can also use
`appletv pair` on a macbook if you install the necessary tools, but i used the tools i was already used to working with.

**Comment by oznu** [comment]
Thanks for the solution @Pensive.

It got me thinking you could also install `node-appletv` in the container so you can run the required command from the shell.

```
npm install -g node-appletv
```

Then just run:

```
appletv pair
```

---

You can access the terminal using `docker exec -it homebridge sh` or using the terminal provided by [Homebridge Config UI X](https://github.com/oznu/homebridge-config-ui-x)

**Comment by Pensive** [comment]
Thanks oznu - i just tested and confirmed - that works great :) good solution and only takes a couple of minutes.

**Comment by isklikas** [comment]
I got the same problem, but in this case, with a Sony TV, so node-appletv isn't applicable here unfortunately. Since everything auto-restarts what options have I got? This MacBook solution seems like the only viable one for me.
