### ISSUE TITLE
Issue with oznu/homebridge:debian-raspberry-pi

### ISSUE THREAD

**Issue by kevinlsw** [oznu/docker-homebridge#122]
I am getting a core (in the ./config directory) when starting a debian-raspberry-pi image on a Raspberry Pi ZeroW.  Log isn't showing much.

I changed to the regular oznu/homebridge:raspberry-pi image and everything is working fine there. Just curious on what's wrong with the debian variant.

pi@homebridge:~/homebridge $ docker-compose up -d
Creating homebridge_homebridge_1 ... done

pi@homebridge:~/homebridge $ cat docker-compose.yml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:debian-raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - TZ=America/Los_Angeles
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
      - PACKAGES=ffmpeg

pi@homebridge:~/homebridge $ docker-compose logs
Attaching to homebridge_homebridge_1
homebridge_1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
homebridge_1  | [s6-init] ensuring user provided files have correct perms...exited 0.
homebridge_1  | [fix-attrs.d] applying ownership & permissions fixes...
homebridge_1  | [fix-attrs.d] done.
homebridge_1  | [cont-init.d] executing container initialization scripts...
homebridge_1  | [cont-init.d] 10-adduser: executing...
homebridge_1  | [cont-init.d] 10-adduser: exited 267.
homebridge_1  | [cont-init.d] 20-set-timezone: executing...
homebridge_1  | [cont-init.d] 20-set-timezone: exited 267.
homebridge_1  | [cont-init.d] 30-packages: executing...
homebridge_1  | [cont-init.d] 30-packages: exited 267.
homebridge_1  | [cont-init.d] 40-dbus-avahi: executing...
homebridge_1  | [cont-init.d] 40-dbus-avahi: exited 267.
homebridge_1  | [cont-init.d] 45-user-data: executing...
homebridge_1  | [cont-init.d] 45-user-data: exited 267.
homebridge_1  | [cont-init.d] 50-plugins: executing...
homebridge_1  | [cont-init.d] 50-plugins: exited 267.
homebridge_1  | [cont-init.d] 55-config-ui: executing...
homebridge_1  | [cont-init.d] 55-config-ui: exited 267.
homebridge_1  | [cont-init.d] done.
homebridge_1  | [services.d] starting services
homebridge_1  | [services.d] done.

pi@homebridge:~/homebridge $ id pi
uid=1000(pi) gid=1000(pi) groups=1000(pi),4(adm),20(dialout),24(cdrom),27(sudo),29(audio),44(video),46(plugdev),60(games),100(users),101(input),108(netdev),999(spi),998(i2c),997(gpio),996(docker)

pi@homebridge:~/homebridge $ uname -a
Linux homebridge 4.14.50+ #1122 Tue Jun 19 12:21:21 BST 2018 armv6l GNU/Linux

pi@homebridge:~/homebridge $ ls -al config/core
-rw------- 1 root root 172032 Aug 13 21:10 config/core

[core.txt](https://github.com/oznu/docker-homebridge/files/2284801/core.txt)

**Comment by oznu** [comment]
Hi @kevinlsw,

The Raspberry Pi Zero only supports ARMv6 architecture. The debian variant is ARMv7, which requires a Raspberry Pi 2 or 3.

**Comment by kevinlsw** [comment]
Ah I see. Thanks for the quick response!
