### ISSUE TITLE
Homebridge slowly eats my memory

### ISSUE THREAD

**Issue by henkied** [oznu/docker-homebridge#123]
Hi @oznu Everything starts fine at start. After a few days, the memory is about 88% after restarting the docker container it isat normal level again. I have to do this every 4 days. Do you know solution?

<img width="320" alt="ram" src="https://user-images.githubusercontent.com/20031014/44622450-ceb1ae80-a8b8-11e8-85c6-a1ee46df4e95.png">

**Comment by oznu** [comment]
Which process inside the container is growing?

**Comment by henkied** [comment]
the docker proces.

**Comment by henkied** [comment]
<img width="769" alt="docker 2" src="https://user-images.githubusercontent.com/20031014/44627677-fee96380-a931-11e8-8dce-138449c3136f.png">
<img width="743" alt="docker" src="https://user-images.githubusercontent.com/20031014/44627678-fee96380-a931-11e8-86f3-7925365de9cb.png">

**Comment by oznu** [comment]
You can show just the processes running inside the container:

Docker -> Containers -> Select Homebridge -> Details -> Process Tab.

**Comment by henkied** [comment]
<img width="907" alt="schermafdruk 2018-08-26 14 13 25" src="https://user-images.githubusercontent.com/20031014/44628107-3c51ef00-a93a-11e8-8a42-0895abe64190.png">
<img width="891" alt="schermafdruk 2018-08-26 14 13 16" src="https://user-images.githubusercontent.com/20031014/44628108-3c51ef00-a93a-11e8-9266-a874bb232e76.png">

**Comment by henkied** [comment]
this is at this moment....

**Comment by henkied** [comment]
i think it is ffmpeg i have removed one camera look of this is the solution

**Comment by henkied** [comment]
now it is better i think
<img width="853" alt="schermafdruk 2018-08-26 14 35 16" src="https://user-images.githubusercontent.com/20031014/44628304-4aedd580-a93d-11e8-9d33-febf780ecf91.png">

**Comment by oznu** [comment]
Great!
