### ISSUE TITLE
Update old docker image

### ISSUE THREAD

**Issue by nchlsgh1** [oznu/docker-homebridge#124]
Hi Oznu,
Great work. Currently im using docker with homebridge @0.4.38
How do I update this without changing any other settings?

Thanks!

**Comment by oznu** [comment]
Hi @nchlsgh1,

You can just download the most current image:

```shell
# change latest to whatever tag you used originally
docker pull oznu/homebridge:latest
```

Remove your old container:

```
docker rm -f homebridge
```

Then create a new container mapping the same local folder to `/homebridge`. All your settings and config are stored in this mapping so you won't lose any settings.

---

If you're using docker-compose it's even easier:

```
docker-compose pull homebridge
docker-compose up -d
```

**Comment by nchlsgh1** [comment]
Hi Oznu,

This is great I am using docker-compose. Huge thanks so the work you put into this... Somehow I am not able to directly load homebridge... while your docker is all set up and ready for its config.json and packages :)

pi@HomeKit:~/homebridge $ docker-compose pull homebridge
Pulling homebridge (oznu/homebridge:raspberry-pi)...
raspberry-pi: Pulling from oznu/homebridge
05580b002c18: Pull complete
975d8f877f1a: Pull complete
beb06d26d47f: Extracting [==>                                                ]  d3544d9712b1: Downloading [====================================>              ]  5.561MB/7.566MBwnloading [============>                                      ]  4.496MB/18.1MBownload complete
150361e151a3: Download complete
    569B/569B Waiting
96ee6f6cf522: Waiting
Cheers!
