### ISSUE TITLE
Restart Container on LibreELEC reboot

### ISSUE THREAD

**Issue by mcdantas** [oznu/docker-homebridge#127]
I've installed the homebridge thru docker in my LibreELEC running on a Odroid C2. It worked fine, but every time the Odroid was rebooted the Homebridge Container wasn't started, I had to start it manually on Docker.

I worked it around editing the autostart.sh on LibreELEC:

# _nano /storage/.config/autostart.sh_

Paste the following command:

# _docker restart homebridge_

Now, every time the Odroid reboots the docker restarts the homebridge.

**Comment by oznu** [comment]
Thanks, I've added this information to the wiki.
