### ISSUE TITLE
Add ffmpeg libfdk_aac encoder support.

### ISSUE THREAD

**Issue by tasict** [oznu/docker-homebridge#128]
Could you add libfdk_aac support in ffmpeg package for homebridge-camera-ffmpeg audio supported？

**Comment by oznu** [comment]
To add libfdk_aac to ffmpeg you  need to compile ffmpeg with support for that codec.

Unfortunately this takes a very long time, even longer when cross compiling for armhf/aarch64, so would not be feasible to do as the Travis CI build times are limited to 50 minutes per job.

**Comment by aekv** [comment]
Please add for Debian image. 
FFmpeg + AAC
https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-4

**Comment by malmentm** [comment]
Also want this

**Comment by Jafalex** [comment]
Is this the only way to get audio on ffmpeg video feeds in Homekit (through Homebridge)?
It's not ideal to be missing audio...

**Comment by oznu** [comment]
Good news.

`ffmpeg`, with `libfdk-aac` audio support, is now included in this image.

**Comment by Jafalex** [comment]
It’s working! Thanks!

**Comment by gondalez** [comment]
Thank you! I can confirm audio now works nicely with unifi cameras.
