### ISSUE TITLE
 E: Package 'libtool' has no installation candidate - Trying to install for homebridge-apple-tv

### ISSUE THREAD

**Issue by Pensive** [oznu/docker-homebridge#131]
Hi guys

   Sorry linux noob here; i'm in the homebridge-config-ui-x terminal having Docker runnign in Synology on the Debian version and getting this error when i run 
"apt-get install libtool" which is needed for the apple tv plugin.

Do I need to enable some repositories or something? 

`root@MyNas/homebridge# apt-get install libtool
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libtool is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libtool' has no installation candidate
root@MyNas:/homebridge#`

**Comment by oznu** [comment]
Add this to the end of the startup.sh script (it's in the same directory as your `config.json`):

```
apt-get update
apt-get install -y libtool
```

**Comment by Pensive** [comment]
Thank you!!
For future n00bs - I also had to add autoconf as well, and restart the container of course - but then the plugin installed

`apt-get update
apt-get install -y libtool
apt-get install -y autoconf`

**Comment by fugazzy** [comment]
I am running in the same problem, but the fix does not seem to work for me:
there is no apt-get
oznu/homebridge:no-avahi on Synology docker (DS918+)
