### ISSUE TITLE
Accessories Not showing up in HomeKit + Unable to add Room

### ISSUE THREAD

**Issue by stkol76** [oznu/docker-homebridge#136]
Hi,

I have a big issue getting the accessories to show up in HomeKit .. the Bridge is connecting and “live” in HomeKit, but nothing Else from Docker HomeBridge .. everything in HomeBridge is according to the Docker status screen running as it should.

Config.json:

`{
    "bridge": {
        "name": "MY Homebridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 5XXX6,
        "pin": "XX-XX-XXX"
    },
    "description": "This is the Homebridge",
    "accessories": [],
    "platforms": [
        {
            "platform": "Camera-ffmpeg-omx",
            "cameras": [
                {
                    "name": "Baghave",
                    "videoConfig": {
                        "source": "-re -i http://admin:pass@192.168.1.183/mjpeg.cgi?user=admin&password=pass",
                        "stillImageSource": "-i http://admin:pass@192.168.1.183/IMAGE.JPG",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30
                    }
                }
            ]
        }
    ]
}
`

Also I am not able to add rooms in the “Accesssories” tab.

Can you please help, I have tried for 3 days now to get this to work.

Best Regards
Stig :-)

**Comment by oznu** [comment]
To add a camera you need to:

1. Go into the Home app
2. Add Accessory
3. Click don't have code or can't scan

You should see the camera listed here. You'll need to do this for each camera as they are exposed differently to the default homebridge bridge accessory.
