### ISSUE TITLE
Error: Cannot find module '../build/Release/pty.node' 

### ISSUE THREAD

**Issue by CapoD** [oznu/docker-homebridge#137]
Hi,
the container has the same problem as mentioned here. [Related issue](https://github.com/oznu/homebridge-config-ui-x/issues/9)
I tried to apply the described fix by adding it to the `startup.sh`, however this does not help. 

It would be nice to get an upgraded container image.

Thank you!

**Comment by oznu** [comment]
Hi @CapoD,

The latest version of the image now includes the latest version of the ui.
