### ISSUE TITLE
s6-applyuidgid: fatal: unable to exec homebridge: Exec format error

### ISSUE THREAD

**Issue by nano-f** [oznu/docker-homebridge#139]
Having a weird issue since I updated the docker image (raspberry-pi tag). After the init in the container is done and plugins installed, it loops with this in the logs:

```
Server startup complete.
-U /homebridge -P /homebridge/node_modules -C
s6-applyuidgid: fatal: unable to exec homebridge: Exec format error
```

Any ideas? Thanks!

**Comment by nano-f** [comment]
Seems like it's because it can't find homebridge at all.

**Comment by oznu** [comment]
Can you try pulling the latest version of the image?

**Comment by nano-f** [comment]
Same error:

**Comment by oznu** [comment]
Can you run `uname -a` and post the output here?

**Comment by nano-f** [comment]
Sure:
`Linux LibreELEC 4.14.69 #1 SMP Thu Sep 13 16:58:47 BST 2018 armv7l GNU/Linux`

**Comment by nano-f** [comment]
Nevermind I pulled the `raspberry-pi` tag and it's all good now! Cheers
