### ISSUE TITLE
How to install materik/homebridge-harmonyhub instead of kraigm/homebridge-harmonyhub?

### ISSUE THREAD

**Issue by nexttoyou** [oznu/docker-homebridge#141]
Hello,

I’d very much replace "kraigm/homebridge-harmonyhub" by "materik/homebridge-harmonyhub". As it has the same name I unfortunately do not know how this could be done using the methods shown in the documentation (I still might have overseen/misunderstood something).

Many thanks in advance!

**Comment by oznu** [comment]
Hi @nexttoyou,

https://github.com/oznu/docker-homebridge#homebridge-plugins

Remove existing plugin: 

```
docker exec homebridge npm uninstall homebridge-harmonyhub
```

Add the alternative plugin:

```
docker exec homebridge npm install materik/homebridge-harmonyhub#0.2.0
```

**Comment by nexttoyou** [comment]
Hi @oznu,

I’m sorry that I did not mention the platform in my case. As I use a Synology DSM, should it be done like this?

`yarn remove homebridge-harmonyhub`

`yarn add materik/homebridge-harmonyhub#0.2.0`

Or wouldn’t that work?

Many thanks again!

**Comment by oznu** [comment]
If you're using a reasonable up-to-date version of the container (updated in last year), then using npm over yarn would be the way to go.

**Comment by nexttoyou** [comment]
Unfortunately, it seems that the same plug-in from **kraigm** but not the one from **materik** is just installed again (at least it shows up like that in the homebridge-config-ui-x). I tried it twice already, always with restarting the container afterwards:

`npm uninstall homebridge-harmonyhub`

`npm install materik/homebridge-harmonyhub#0.2.0`

Any clues?

**Comment by oznu** [comment]
It will show up like that because it is the same plugin with the same package manifest. Check the contents of the `package.json` file to make sure the correct one is loaded.

**Comment by nexttoyou** [comment]
Yep, perfect, thanks!
