### ISSUE TITLE
how to update nodejs

### ISSUE THREAD

**Issue by RSMBS** [oznu/docker-homebridge#142]
hello,

in the docker container is node v8.12.0 installed automatically.
but for my plugins to work i need to update node.
how can i do this without destroying my docker container?
i tried everything but didnt succede.

could someone help me?

best regards

**Comment by oznu** [comment]
Upgrading node inside an existing container is not supported. A new version of the container will be available soon - the new major version of Node LTS has only been available for less than a day.

**Comment by oznu** [comment]
The latest version has node 10.13.0.
