### ISSUE TITLE
Noob issue

### ISSUE THREAD

**Issue by swordfishunter123** [oznu/docker-homebridge#147]
I've follwed the steps 3 times to install hombridge, but after installation i cant see the files config, package, and the folders in the homebridge folder. Am i doing something wrong ..

**Comment by oznu** [comment]
Hi @swordfishunter123,

Maybe. Can you share the command you used to start the container?

**Comment by swordfishunter123** [comment]
wow. Quick response,
I just clicked apply after running the wizard and the container started. 
Additionally, i tried installing the wemo plugin in the example, but I still see no files in the hombridge folder.

**Comment by oznu** [comment]
Synology?

Check the mounted path in the docker container overview.

Docker App > Container > Select Homebridge > Details > Overview > Volume
