### ISSUE TITLE
Cannot execute commands prior to homebridge startup

### ISSUE THREAD

**Issue by FiReiSFuN** [oznu/docker-homebridge#15]
Great work on this container, it's fantastic. 

My issue (a feature request really) specifically relates to the plugin homebridge-homeassistant, which connects homebridge to a running Home Assistant instance. 

When Home Assistant is set up with SSL and a self-signed certificate, for homebridge to be able to connect to the Home Assistant instance, we must first do:

export NODE_TLS_REJECT_UNAUTHORIZED=0

So that homebridge will not fail to connect because of an SSL error. 

Can we add a script to the volume /homebridge that contains code to be executed prior to homebridge startup?

Thanks in advance!

**Comment by oznu** [comment]
I do plan on adding an option for a custom init script soon. In your case though you should be able to pass in the environment variable via docker to do exactly what you need.

```
docker run -e "NODE_TLS_REJECT_UNAUTHORIZED=0" oznu/homebridge
```

**Comment by FiReiSFuN** [comment]
Wasn't aware this was possible. Will be testing shortly.

**Comment by FiReiSFuN** [comment]
Success! Thanks for the help on this. Issue can be closed.
