### ISSUE TITLE
Install failure - Pi Zero W

### ISSUE THREAD

**Issue by drewweber** [oznu/docker-homebridge#151]
Getting a failure while installing on brand new Raspberry Pi Zero W, running Raspbian Stretch Light

command was `docker-compose up -d`

> ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
> 
> If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

Any help would be appreciated.

**Comment by ianfuchs** [comment]
Looks like it’s a docker-ce version issue with the ARMv6 in the Pi Zero W. If you downgrade to the older version of compose, it should work (vested and verified).

`sudo apt-get install docker-ce=18.06.1~ce~3-0~raspbian
`

**Comment by drewweber** [comment]
Thanks @ianfuchs! That got me running on docker. I am now getting a crash on homebridge right after it displays the Homekit code.

`Error: listen EADDRINUSE :::51826
homebridge_1_8cff28131624 |     at Server.setupListenHandle [as _listen2] (net.js:1286:14)
homebridge_1_8cff28131624 |     at listenInCluster (net.js:1334:12)
homebridge_1_8cff28131624 |     at Server.listen (net.js:1421:7)
homebridge_1_8cff28131624 |     at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
homebridge_1_8cff28131624 |     at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
homebridge_1_8cff28131624 |     at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:607:16)
homebridge_1_8cff28131624 |     at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:128:16)
homebridge_1_8cff28131624 |     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:97:10)
homebridge_1_8cff28131624 |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
homebridge_1_8cff28131624 |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)`

**Comment by ianfuchs** [comment]
It looks like you have a port conflict with some other process running on your Pi. 

You could try `netstat` Or `netstat | grep '51826'` To see if there is something else running on that port. 

You could also change the Homebridge port in the config file to something not in use and see if it starts.

**Comment by oznu** [comment]
Thanks @ianfuchs, I've added this to the wiki.
