### ISSUE TITLE
TimeoutOverflowWarning

### ISSUE THREAD

**Issue by aekv** [oznu/docker-homebridge#154]
Hi,

After image update (docker-compose pull), I have issue: 

`homebridge    | 2018-11-28T12:00:12.006443242Z (node:401) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
homebridge    | 2018-11-28T12:00:12.006471893Z Timeout duration was set to 1.
...
`

**Comment by oznu** [comment]
Hi @aekv,

If you're still facing this issue could you post a full log output?
