### ISSUE TITLE
"Couldn't Add Accessory"

### ISSUE THREAD

**Issue by caboj** [oznu/docker-homebridge#156]
I've installed this onto my Pi 3 several times, trying raspberry-pi, no-avahi-raspberry-pi, and finally debian-no-avahi-raspberry-pi images. Every time, it installs and runs fine, but I cannot add the accessory to the Home app, getting "Couldn't Add Accessory".

Below is my docker-compose.yml. I've tried this from scratch 3+ times, but always get "Couldn't Add Accessory". I'm able to see that Homebridge is running at <ip>:9090, but I can't add to my Homekit.

I was previously running Homebridge on my Mac, but disabled it and removed it from Home, if that helps.

`version: '2'
services:
  homebridge:
    image: oznu/homebridge:debian-no-avahi-raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=9090`

**Comment by oznu** [comment]
If you're still facing this issue, you will need to remove the `accessories` and `persist` folders in the homebridge config directory, as well as change the MAC address username in your `config.json`.

**Comment by pberchum** [comment]
I have the same issue and removing the folders and changing the username does not help for me. A ny suggestions?

**Comment by louia** [comment]
I have same problem with latest version of homebridge.
My iPhone Home App tell me "Accessorie Not found" and I don't have the message box "Accessorie Not Certified...."
