### ISSUE TITLE
Need help getting homebridge-nest and homebridge-nest-cam to run

### ISSUE THREAD

**Issue by Azzhoe** [oznu/docker-homebridge#157]
I keep seeing this error in my log... I have installed Homebridge via the Docker Container method. But can't seem to get my homebridge-nest and homebridge-nest-cam plugin to work. I am trying to look for a token in the log file but it says Error Service Unavailable and I'm not sure what I'm doing wrong, I also notice the following in my log file as well:

[         .........] - postinstall:homebridge: WARN homebridge No license field [         .........] - postinstall:homebridge: WARN homebridge No license field [         .........] - postinstall:homebridge: WARN homebridge No license field [         .........] - postinstall:homebridge: WARN homebridge No license field [         .........] - postinstall:homebridge: WARN homebridge No license field [         .........] - postinstall:homebridge: WARN homebridge No license field [         .........] - postinstall:homebridge: WARN homebridge No license field [         .........] - postinstall:homebridge: WARN homebridge No license field  audited 286 packages in 8.67s | stdout
-- | --

found 1 low severity vulnerability | stdout
-- | --

run `npm audit fix` to fix them, or `npm audit` for details

**Comment by oznu** [comment]
Hi @Azzhoe,

If you're still facing this issue could you post a full log output?
