### ISSUE TITLE
Startup Script to Delete cachedAccessories?

### ISSUE THREAD

**Issue by dawger1** [oznu/docker-homebridge#159]
Hi there,

Long time user, infrequent poster. First off, thank you for the amazing work. Being able to control our non-HomeKit enabled devices from our iOS devices has been fantastic!

My issue is this: every time we have a power interruption, all of our devices show as Not Responding in Apple Home. The fix is to login to the raspberry pi, delete the cachedAccessories folder, and restart   Homebridge. What I’m wondering is if it would be possible to add a line to my startup.sh (or elsewhere) that auto removes this folder every time power is lost to my Pi. If so, could you please explain how to this non-Linux User?  I’m imagining that cachedAccesories is there for a reason, but upon a power cycle, it seems to cause more harm than good. 

Thanks again, and keep up the great work!

**Comment by oznu** [comment]
Hi @dawger1,

I think there might be some issues with your plugins if you need to delete this file after a reboot; but if this works for you then add this to the bottom of your `startup.sh` script:

```
rm -rf /homebridge/accessories/cachedAccessories
```
