### ISSUE TITLE
[Question] Does docker container improve running performance?

### ISSUE THREAD

**Issue by thomasbrooks4** [oznu/docker-homebridge#160]
I'm relatively new to Docker, but I definitely see the benefits of using Docker to spin up Homebridge. I was wondering though, how does running Homebridge on a Docker container affect ongoing performance?

**Comment by oznu** [comment]
Running homebridge in a docker container will not improve performance. There is a slight resource overhead compared to running natively but this should be negligible for most users.

The exception to this being ffmpeg and hardware decoding on boards like the Raspberry Pi. If you are running on an rPi and need to use ffmpeg then you should run homebridge natively.
