### ISSUE TITLE
After installation, I can‘t edit the json file. Not enough quota for user 911

### ISSUE THREAD

**Issue by didifreak** [oznu/docker-homebridge#161]
After installatoion, I can‘t eidt the json file. Not enough quota for user 911.
I installed the docker file beeing logged in as admin. I restarted the app and installed the homebridge plugin via terminal. When I try to edit the json.config, I get an error, saying, I have not enough quota (for user 911). I tried to change the ownership to me, but couldn‘t. 
What am I overlooking?
Thanks for your help.

**Comment by oznu** [comment]
Hi @didifreak,

What platform are you running on? Make sure you have set the `PUID` and `PGID` to match your users uid and gid as per:

https://github.com/oznu/docker-homebridge#user--group-identifiers

**Comment by didifreak** [comment]
Thanks.
