### ISSUE TITLE
Can't install docker on fresh Raspbian Lite setup

### ISSUE THREAD

**Issue by seannymurrs** [oznu/docker-homebridge#163]
I'm following your guide to install homebridge on my Raspberry Pi. I got to the step where I need to install Docker. When I input the following command:

`sudo apt-get install docker-ce=18.06.1~ce~3-0~raspbian`

I get the following error:

`E: Unable to locate package docker-ce`

Not really sure how to proceed from here.

**Comment by oznu** [comment]
@seannymurrs,

Thanks for reporting this. I've reverted a recent change I made to the wiki.
