### ISSUE TITLE
Can access GUI from LAN

### ISSUE THREAD

**Issue by JDogg016** [oznu/docker-homebridge#164]
about 5 days ago I lost the Ability to access the home bridge GUI from my local network. I am on port 8581, but every time I try to access the GUI over the web the browser comes back and says cannot connect to the server. Homebridge is running, I have full control over all my accessories, I just can’t access the GUI. Is there something I can check?

**Comment by oznu** [comment]
Hi @JDogg016,

Check the port that the UI is suppose to be running on according to the `config.json`. It might be set to 8080?
