### ISSUE TITLE
homebridge-eq3ble / Bluetooth Support

### ISSUE THREAD

**Issue by jfc87** [oznu/docker-homebridge#165]
Hello, I'm running the container on a Raspberry Pi 3 Model B Rev 1.2.

I would like to install this plugin (https://www.npmjs.com/package/homebridge-eq3ble) but I get this error (log): 

```bash

pi@raspberrypi:~/homebridge $ docker exec homebridge npm install homebridge-eq3ble

> usb@1.5.0 install /homebridge/node_modules/usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.5.0/usb_bindings-v1.5.0-node-v64-linux-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not found for usb@1.5.0 and node@10.14.2 (node-v64 ABI, musl) (falling back to source compile with node-gyp)
make: Entering directory '/homebridge/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
In file included from ../libusb/libusb/os/linux_usbfs.c:43:0:
../libusb/libusb/os/linux_usbfs.h:24:25: fatal error: linux/types.h: No such file or directory
 #include <linux/types.h>
                         ^
compilation terminated.
make: *** [libusb.target.mk:138: Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o] Error 1
make: Leaving directory '/homebridge/node_modules/usb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/homebridge/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/homebridge/node_modules/usb/src/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /homebridge/node_modules/usb
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/homebridge/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/homebridge/node_modules/usb/src/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/homebridge/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.14.79-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/homebridge/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /homebridge/node_modules/usb
node-pre-gyp ERR! node -v v10.14.2
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/homebridge/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/homebridge/node_modules/usb/src/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

> bluetooth-hci-socket@0.5.1 install /homebridge/node_modules/bluetooth-hci-socket
> node-gyp rebuild

make: Entering directory '/homebridge/node_modules/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o
../src/BluetoothHciSocket.cpp: In member function 'void BluetoothHciSocket::poll()':
../src/BluetoothHciSocket.cpp:251:95: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
                                                                                               ^
In file included from ../src/BluetoothHciSocket.cpp:8:0:
../../nan/nan.h:980:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../src/BluetoothHciSocket.cpp: In member function 'void BluetoothHciSocket::emitErrnoError()':
../src/BluetoothHciSocket.cpp:275:72: error: no matching function for call to 'v8::Function::NewInstance(int, v8::Local<v8::Value> [1])'
   Local<Value> error = errorConstructor->NewInstance(1, constructorArgs);
                                                                        ^
In file included from /root/.node-gyp/10.14.2/include/node/node.h:63:0,
                 from /root/.node-gyp/10.14.2/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/root/.node-gyp/10.14.2/include/node/v8.h:3993:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/root/.node-gyp/10.14.2/include/node/v8.h:3993:44: note:   candidate expects 3 arguments, 2 provided
/root/.node-gyp/10.14.2/include/node/v8.h:3996:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/root/.node-gyp/10.14.2/include/node/v8.h:3996:44: note:   candidate expects 1 argument, 2 provided
../src/BluetoothHciSocket.cpp:282:93: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
                                                                                             ^
In file included from ../src/BluetoothHciSocket.cpp:8:0:
../../nan/nan.h:980:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../src/BluetoothHciSocket.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE BluetoothHciSocket::BindRaw(Nan::NAN_METHOD_ARGS_TYPE)':
../src/BluetoothHciSocket.cpp:395:34: warning: 'int64_t v8::Value::IntegerValue() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
       devId = arg0->IntegerValue();
                                  ^
In file included from /root/.node-gyp/10.14.2/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.2/include/node/node.h:63,
                 from /root/.node-gyp/10.14.2/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/root/.node-gyp/10.14.2/include/node/v8.h:2476:46: note: declared here
   V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                              ^
/root/.node-gyp/10.14.2/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/BluetoothHciSocket.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE BluetoothHciSocket::BindUser(Nan::NAN_METHOD_ARGS_TYPE)':
../src/BluetoothHciSocket.cpp:417:34: warning: 'int64_t v8::Value::IntegerValue() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
       devId = arg0->IntegerValue();
                                  ^
In file included from /root/.node-gyp/10.14.2/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.2/include/node/node.h:63,
                 from /root/.node-gyp/10.14.2/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/root/.node-gyp/10.14.2/include/node/v8.h:2476:46: note: declared here
   V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                              ^
/root/.node-gyp/10.14.2/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [binding.target.mk:99: Release/obj.target/binding/src/BluetoothHciSocket.o] Error 1
make: Leaving directory '/homebridge/node_modules/bluetooth-hci-socket/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /homebridge/node_modules/bluetooth-hci-socket
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.5.0 (node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.5.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ homebridge-eq3ble@1.3.3
added 114 packages from 77 contributors and audited 682 packages in 42.86s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

```

I think it's related to the probably missing bluetooth support, any recommendations ?

**Comment by oznu** [comment]
Hi @jfc87,

Passing the bluetooth controller into the docker container will be challenging. For your use case I would recommend running Homebridge [natively using systemd](https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a/).

**Comment by mrdc** [comment]
Hi @oznu, 
> I would recommend running Homebridge natively using systemd.

What to do in case of running Docker Homebridge on LibreELEC? It's not possbile to use apt-get and most of other tools to install Homebridge and use it via systemd.

**Comment by giswa** [comment]
> Hello, I'm running the container on a Raspberry Pi 3 Model B Rev 1.2.
> 
> I would like to install this plugin (https://www.npmjs.com/package/homebridge-eq3ble) but I get this error (log):
> 
> ```shell
> pi@raspberrypi:~/homebridge $ docker exec homebridge npm install homebridge-eq3ble
> 
> > usb@1.5.0 install /homebridge/node_modules/usb
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp WARN Using needle for node-pre-gyp https download
> node-pre-gyp WARN Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.5.0/usb_bindings-v1.5.0-node-v64-linux-arm.tar.gz
> node-pre-gyp WARN Pre-built binaries not found for usb@1.5.0 and node@10.14.2 (node-v64 ABI, musl) (falling back to source compile with node-gyp)
> make: Entering directory '/homebridge/node_modules/usb/build'
>   CC(target) Release/obj.target/libusb/libusb/libusb/core.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/io.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
> In file included from ../libusb/libusb/os/linux_usbfs.c:43:0:
> ../libusb/libusb/os/linux_usbfs.h:24:25: fatal error: linux/types.h: No such file or directory
>  #include <linux/types.h>
>                          ^
> compilation terminated.
> make: *** [libusb.target.mk:138: Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o] Error 1
> make: Leaving directory '/homebridge/node_modules/usb/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
> gyp ERR! System Linux 4.14.79-v7+
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/homebridge/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/homebridge/node_modules/usb/src/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
> gyp ERR! cwd /homebridge/node_modules/usb
> gyp ERR! node -v v10.14.2
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/homebridge/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/homebridge/node_modules/usb/src/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/homebridge/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> node-pre-gyp ERR! System Linux 4.14.79-v7+
> node-pre-gyp ERR! command "/usr/local/bin/node" "/homebridge/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /homebridge/node_modules/usb
> node-pre-gyp ERR! node -v v10.14.2
> node-pre-gyp ERR! node-pre-gyp -v v0.11.0
> node-pre-gyp ERR! not ok
> Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/homebridge/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/homebridge/node_modules/usb/src/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
> 
> > bluetooth-hci-socket@0.5.1 install /homebridge/node_modules/bluetooth-hci-socket
> > node-gyp rebuild
> 
> make: Entering directory '/homebridge/node_modules/bluetooth-hci-socket/build'
>   CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o
> ../src/BluetoothHciSocket.cpp: In member function 'void BluetoothHciSocket::poll()':
> ../src/BluetoothHciSocket.cpp:251:95: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
>      Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
>                                                                                                ^
> In file included from ../src/BluetoothHciSocket.cpp:8:0:
> ../../nan/nan.h:980:46: note: declared here
>    NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
>                                               ^~~~~~~~~~~~
> ../src/BluetoothHciSocket.cpp: In member function 'void BluetoothHciSocket::emitErrnoError()':
> ../src/BluetoothHciSocket.cpp:275:72: error: no matching function for call to 'v8::Function::NewInstance(int, v8::Local<v8::Value> [1])'
>    Local<Value> error = errorConstructor->NewInstance(1, constructorArgs);
>                                                                         ^
> In file included from /root/.node-gyp/10.14.2/include/node/node.h:63:0,
>                  from /root/.node-gyp/10.14.2/include/node/node_buffer.h:25,
>                  from ../src/BluetoothHciSocket.cpp:7:
> /root/.node-gyp/10.14.2/include/node/v8.h:3993:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
>    V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
>                                             ^~~~~~~~~~~
> /root/.node-gyp/10.14.2/include/node/v8.h:3993:44: note:   candidate expects 3 arguments, 2 provided
> /root/.node-gyp/10.14.2/include/node/v8.h:3996:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
>    V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
>                                             ^~~~~~~~~~~
> /root/.node-gyp/10.14.2/include/node/v8.h:3996:44: note:   candidate expects 1 argument, 2 provided
> ../src/BluetoothHciSocket.cpp:282:93: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
>    Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
>                                                                                              ^
> In file included from ../src/BluetoothHciSocket.cpp:8:0:
> ../../nan/nan.h:980:46: note: declared here
>    NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
>                                               ^~~~~~~~~~~~
> ../src/BluetoothHciSocket.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE BluetoothHciSocket::BindRaw(Nan::NAN_METHOD_ARGS_TYPE)':
> ../src/BluetoothHciSocket.cpp:395:34: warning: 'int64_t v8::Value::IntegerValue() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
>        devId = arg0->IntegerValue();
>                                   ^
> In file included from /root/.node-gyp/10.14.2/include/node/v8.h:26:0,
>                  from /root/.node-gyp/10.14.2/include/node/node.h:63,
>                  from /root/.node-gyp/10.14.2/include/node/node_buffer.h:25,
>                  from ../src/BluetoothHciSocket.cpp:7:
> /root/.node-gyp/10.14.2/include/node/v8.h:2476:46: note: declared here
>    V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
>                                               ^
> /root/.node-gyp/10.14.2/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
>    declarator __attribute__((deprecated(message)))
>    ^~~~~~~~~~
> ../src/BluetoothHciSocket.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE BluetoothHciSocket::BindUser(Nan::NAN_METHOD_ARGS_TYPE)':
> ../src/BluetoothHciSocket.cpp:417:34: warning: 'int64_t v8::Value::IntegerValue() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
>        devId = arg0->IntegerValue();
>                                   ^
> In file included from /root/.node-gyp/10.14.2/include/node/v8.h:26:0,
>                  from /root/.node-gyp/10.14.2/include/node/node.h:63,
>                  from /root/.node-gyp/10.14.2/include/node/node_buffer.h:25,
>                  from ../src/BluetoothHciSocket.cpp:7:
> /root/.node-gyp/10.14.2/include/node/v8.h:2476:46: note: declared here
>    V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
>                                               ^
> /root/.node-gyp/10.14.2/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
>    declarator __attribute__((deprecated(message)))
>    ^~~~~~~~~~
> make: *** [binding.target.mk:99: Release/obj.target/binding/src/BluetoothHciSocket.o] Error 1
> make: Leaving directory '/homebridge/node_modules/bluetooth-hci-socket/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
> gyp ERR! System Linux 4.14.79-v7+
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /homebridge/node_modules/bluetooth-hci-socket
> gyp ERR! node -v v10.14.2
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm WARN homebridge No description
> npm WARN homebridge No repository field.
> npm WARN homebridge No license field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.5.0 (node_modules/usb):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.5.0 install: `node-pre-gyp install --fallback-to-build`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> 
> + homebridge-eq3ble@1.3.3
> added 114 packages from 77 contributors and audited 682 packages in 42.86s
> found 1 low severity vulnerability
>   run `npm audit fix` to fix them, or `npm audit` for details
> ```
> 
> I think it's related to the probably missing bluetooth support, any recommendations ?

I ran into the same problem using a different plugin. 
Reason seems to be that the Noble npm module is not working on node version 10/12. The project seems to have stopped at node version 8. So any Bluetooth plugin based on Noble will not run unless you have node version 8.
There's a Fork @abandonware/noble that correct this, but I really don't know how to set this up.
find more info here : https://github.com/noble/node-bluetooth-hci-socket/issues/84
