### ISSUE TITLE
homekit can't connect to homebridge

### ISSUE THREAD

**Issue by alebx** [oznu/docker-homebridge#166]
I'm using the latest version of container on a synology nas, homebridge is starting fine and the homebridge ui is also accessible, but the pairing fails.

**Comment by alebx** [comment]
Thanks for the fast reply. This resolved my issue! I wasn't aware that I couldn't use my migrated settings from my raspberry pi setup.

**Comment by Theobelgium** [comment]
I have a similar issue, which is not resolved by a reset of homebridge. Do you have any other options to try? I keep getting a 'accessory not found' after trying to pair homebridge with Homekit
