### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by coryroloff** [oznu/docker-homebridge#173]
Hello,

I'm attempting to run this image with user namespaces enabled in the docker daemon, but am getting errors when running oznu/homebridge. I have the following set when I launch the container:

```sh
--userns=host --privileged --net=host
```

I've also tried setting `-e PUID=0 -e PGID=0`. I've also tried setting these to the user and group that docker normally remaps.

Unfortunately, every combination I try it seems the start up script doesn't have permission to execute commands like chmod/chown or even npm install. Basically every command throws "Operation not permitted".

Obviously I know this isn't ideal and is sort of weird when using namespaces, but right now I'm just trying to see if I can get it running. :)

Thoughts?

**Comment by oznu** [comment]
Hi @coryroloff,

I don't think this container will operate under a non-root namespace as the container uses the [s6 overlay](https://github.com/just-containers/s6-overlay) as a process manager which requires root to operate correctly.

If you have any luck please post back here for others though.
