### ISSUE TITLE
Clarification on adding node.gs packages

### ISSUE THREAD

**Issue by ceraz68** [oznu/docker-homebridge#174]
I'd like to add nodemailer to my list of available npm packages available for homebridge plugins. This would be installed in docker/homebridge/node_modules alongside the existing nodemailer-fetch and nodemailer-shared packages

I'm not sure on the right procedure to install the package:
1) SSH into the Synology and running "$ docker exec homebridge npm install nodemailer" gives permission errors:
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/containers/homebridge/exec: dial unix /var/run/docker.sock: connect: permission denied

2) for issue #65 you recommended adding "apk add --no-cache ffmpeg ffmpeg-libs" to startup.sh but not sure if this is the right thing to do as the instructions refer to plugins.

3) I guess the package.json file is really for homebridge-plugins and not base packages.

I'm afraid to corrupt my docker by making a stupid mistake so thanks for any suggestions on the best way to add the package to the docker :-)

**Comment by oznu** [comment]
@ceraz68 - the `package.json` would be the best place for this. Any packages not listed in the `package.json` are going to be purged next time you start the container so it's best to have them all listed there, even if they aren't specifically homebridge plugins.
