### ISSUE TITLE
apt-get: not found 

### ISSUE THREAD

**Issue by mcnahum** [oznu/docker-homebridge#175]
I want to install: 
but for this I need libtool and I found a solution for it:
but when I do this I've the error: "apt-get: not found "

any idea why apt is not here...?

**Comment by oznu** [comment]
The default image uses Alpine Linux which does not use `apt`, rather it uses `apk`.

You can switch to the Debian variant of this image if you need to by using the `debian` tag:

https://github.com/oznu/docker-homebridge/wiki#image-variants
