### ISSUE TITLE
LibreElec + docker + cec-client

### ISSUE THREAD

**Issue by ageorgios** [oznu/docker-homebridge#177]
trying to use cec-client inside docker image
I had success installing using:

```
-e PACKAGES=cec-utils
```
but I do not know which devices to pass to docker like --device=/dev/fb0

any help?

**Comment by RaymondMouthaan** [comment]
You might wanna try to log into the running container with:

'docker exec -it <container name> /bin/bash' 


Or 

'docker exec -it <container name> /bin/sh'


And do:

'ls -al /dev' 

To find your device.
