### ISSUE TITLE
history command on the debian version

### ISSUE THREAD

**Issue by mcnahum** [oznu/docker-homebridge#178]
The "history" command is not working on the debian version (running on synology docker).
I'm not finding why and how to fix it...?

**Comment by oznu** [comment]
Hi @mcnahum,

Are you on the latest image? I tested the history command and it seems to be working fine:

![image](https://user-images.githubusercontent.com/3979615/52530599-3e7aff00-2d5c-11e9-9cd0-3d9a3f8bf449.png)

**Comment by mcnahum** [comment]
is there a proper way to know the version?
on synology I used the switch "debian" who should bring me the last one...

**Comment by oznu** [comment]
I've been using the same source image for quite a while now. What is the output of when you run the `history` command?

**Comment by mcnahum** [comment]
<img width="857" alt="screenshot 2019-02-12 at 08 24 51" src="https://user-images.githubusercontent.com/30963862/52618670-c1f13900-2e9f-11e9-8e3c-72caeb053065.png">

**Comment by oznu** [comment]
Try starting the terminal with `bash` instead of `sh`.

**Comment by mcnahum** [comment]
yes working like that...

**Comment by oznu** [comment]
`history` is a bash built-in, which looks not to implimented in Debian's `sh`.
