### ISSUE TITLE
Update Node version

### ISSUE THREAD

**Issue by peter99330** [oznu/docker-homebridge#180]
Hi,

I am trying to install the homebridge-hue plugin, but:

`Plugin /homebridge/node_modules/homebridge-hue requires Node version of ^10.15.1 which does not satisfy the current Node version ofv8.11.3. You may need to upgrade your installation of Node.`

Any chance a release with the newest Node version is happening soon?

(I am running homebridge on a raspberry.)

Thanks!

**Comment by oznu** [comment]
Sure thing:

https://github.com/oznu/docker-homebridge/blob/master/Dockerfile#L2

**Comment by peter99330** [comment]
Thanks, worked perfectly!
