### ISSUE TITLE
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

### ISSUE THREAD

**Issue by smsroman** [oznu/docker-homebridge#184]
tried twice on rpi zero w:
stuck here:
pi@raspberrypi:~/homebridge $ docker-compose up -d
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by smsroman** [comment]
solved by sudo apt-get install docker-ce=18.06.1~ce~3-0~raspbian

but then 
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade

and it broke again.

and solved again by sudo apt-get install docker-ce=18.06.1~ce~3-0~raspbian
do not upgrade!

but homebridge seems to be not autostarting

**Comment by oznu** [comment]
Hi @smsroman,

Check you have docker running:

```
docker ps
```

Then clean up:

```
docker-compose down
```

Then try and start again:

```
docker-compose up -d
```

I'll check out the install guide to make sure it's still up-to-date.

**Comment by oznu** [comment]
I've updated and tested the guide in the wiki. I've also added a quick install script:

https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Raspberry-Pi#quick-install
