### ISSUE TITLE
problem during installation

### ISSUE THREAD

**Issue by iko3** [oznu/docker-homebridge#185]
when running installation script I'm getting this error:
Command "/usr/bin/python /usr/local/lib/python2.7/dist-packages/pip-19.0.3-py2.7.egg/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-lNLRWe/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel "cffi>=1.4.1; python_implementation != 'PyPy'"" failed with error code 1 in None

How can I fix it?

complete log attached
[pi_log.txt](https://github.com/oznu/docker-homebridge/files/3024751/pi_log.txt)

**Comment by oznu** [comment]
Are you running a fresh install of the latest version of Raspbian Lite?

**Comment by iko3** [comment]
yes, I am

> Are you running a fresh install of the latest version of Raspbian Lite?

yes, I am

**Comment by oznu** [comment]
Can replicate. It was working 14 days ago when I published this script!

**Comment by oznu** [comment]
Upstream issue: https://github.com/docker/compose/issues/6617

**Comment by oznu** [comment]
Script updated to pin to docker-compose 1.23.0.

```
curl https://raw.githubusercontent.com/oznu/docker-homebridge/master/raspbian-installer.sh?v=2019-03-30 -o get-homebridge.sh
chmod u+x get-homebridge.sh
./get-homebridge.sh
```

Thanks for reporting.
