### ISSUE TITLE
Update error unhandled rejection Error

### ISSUE THREAD

**Issue by elbrodark** [oznu/docker-homebridge#186]
Hi,
**When i click the Update button on the Hombridge UI i always get this error:**
![hombridgeuierror](https://user-images.githubusercontent.com/9810157/55291828-bc19cd80-53e3-11e9-90be-f020a317ca6f.png)

**in the synology docker-terminal:**
![dockererror](https://user-images.githubusercontent.com/9810157/55291823-b15f3880-53e3-11e9-9e9f-32983913c6a4.PNG)

what did i wrong?

**Comment by oznu** [comment]
To use Homebridge Config UI X with this Docker image you need to set an environment variable.

https://github.com/oznu/docker-homebridge/blob/master/README.md#homebridge-ui-options
https://github.com/oznu/homebridge-config-ui-x/wiki/Enabling-UI-with-Docker

**Comment by elbrodark** [comment]
perfect, thanks
