### ISSUE TITLE
exec user process caused "exec format error"

### ISSUE THREAD

**Issue by jmmen1** [oznu/docker-homebridge#187]
I'm trying to run homebridge on my Raspberry Pi 3, and I'm getting an error:

    $ docker run --rm --name=homebridge --net=host \
    > -e PUID=1000 -e PGID=1000 -e TZ=America/Chicago \
    > -v ${PWD}/volumes/homebridge:/homebridge \
    > oznu/homebridge:arm64v8 
    standard_init_linux.go:207: exec user process caused "exec format error"

    $ cat /etc/os-release 
    PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
    NAME="Raspbian GNU/Linux"
    VERSION_ID="9"
    VERSION="9 (stretch)"
    ID=raspbian
    ID_LIKE=debian
    HOME_URL="http://www.raspbian.org/"
    SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
    BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Has anyone else run into this issue?

**Comment by oznu** [comment]
Raspbian is a 32 bit only OS. You need to run the arm32v6 tag, not the arm64v8 tag.

Alternatively you can just use the `latest` tag and it will pull the correct image for your system.

**Comment by jmmen1** [comment]
Oops, thank you. I knew the CPU was 64-bit, but I didn't realize that Raspbian hadn't been updated to 64-bit yet.
