### ISSUE TITLE
A problem with more docker

### ISSUE THREAD

**Issue by songzh96** [oznu/docker-homebridge#189]
I use homebridge:1.7.8-no-avahi image create tow env.
the first image mount path is /homebridge. i use dsm can found config.json
sencond image is /homekit. i use dsm can`t find config.json,but i use command can find it.

question: What should I do can use dsm found the file?

thanks.

**Comment by oznu** [comment]
If you mount the volume within an existing share you should be able to view it in DSM.

**Comment by songzh96** [comment]
thank you.

i test it, it`s ok.
