### ISSUE TITLE
Seems like iOS 11 beta not able to pair homebridge

### ISSUE THREAD

**Issue by florid2** [oznu/docker-homebridge#19]
iOS 10.3.3 can detect homebridge but not iOS 11 beta 6.

**Comment by oznu** [comment]
This is a known issue with Homebridge. Please see https://github.com/nfarina/homebridge/issues/1414 for possible solutions.

You may have to delete the persist and accessories folders in your `/homebridge` mount and restart the container. Also make sure you're running the latest version of this docker image.
