### ISSUE TITLE
Console v4.0.4 is listening on undefined port 8581

### ISSUE THREAD

**Issue by mrdc** [oznu/docker-homebridge#191]
Hello,

I've started to receive this error after I had installed Homebridge on my Raspbian Stretch 2019-04-08. Previous time web gui worked well. The only change is that Homebridge was installed in LibreELEC. Have no clue what is wrong.

`[4/22/2019, 8:50:08 PM] [homebridge-config-ui-x] Console v4.0.4 is listening on undefined port 8581
(node:1093) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)i`

Specs:
LibreELEC 9.0.1
RPi3b+

Container was started with the CLI arguments:

docker run -t -i -d --restart=always --net=host \
  --name=homebridge \
  -v /storage/homebridge:/homebridge \
  -e PACKAGES=ffmpeg \
  -e HOMEBRIDGE_CONFIG_UI=1 \
  -e HOMEBRIDGE_CONFIG_UI_PORT=8581 \
  oznu/homebridge:raspberry-pi

**Comment by oznu** [comment]
Hi,

Please pull down the latest image, it was fixed in 4.0.5.

**Comment by mrdc** [comment]
Thanks, will give it a try.
