### ISSUE TITLE
Homebridge-Daikin-ESP8266

### ISSUE THREAD

**Issue by jeylites** [oznu/docker-homebridge#192]
Hello Oznu,

Hope all is well!!! 

Can the Daikin ESP8266 be used for York Air conditioning?

**Comment by oznu** [comment]
Probably not. The project uses https://github.com/markszabo/IRremoteESP8266/tree/master/src to generate the required IR codes and does not list York. You may have to "learn" each code yourself which is beyond the scope of the project.
