### ISSUE TITLE
Is there a fix for the omx not working on this docker?

### ISSUE THREAD

**Issue by madness0** [oznu/docker-homebridge#193]

**Comment by oznu** [comment]
Not really - it's best to install it natively (using systemd as the process manager) if you need omx.

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-&-Systemd-(Raspbian,-Ubuntu,-Debian)

**Comment by madness0** [comment]
@oznu Im using Hoobs which is based on your docker, can you guide me how to do that ?, one more question please any idea why it takes so long to refresh snapshots? it takes about 1 minute remotely and about 12 seconds on Wifi, Im using the same stream URL because the snapshot one would not work, Thanks in advance

**Comment by oznu** [comment]
I'm not sure about Hoobs, I didn't realise they were using my Docker image as well. The guide above is for Raspbian.

The reason for the slow snapshot times would probably be the lack of OMX hardware decoding.

**Comment by madness0** [comment]
@oznu I don't understand should i remove the Hoobs and just run home bridge on Raspbian or should I edit something in the UI?, Thanks for the fast replies and im totally new to this

**Comment by oznu** [comment]
Yes, running a fresh install of Raspbian and installing homebridge on it is the way to go if you need OMX support.

**Comment by madness0** [comment]
@oznu ok thank you so much, if you have extra time can you take a look at Hoobs and give me your opinion and if there is something I can with it, because it is really convenient :)
