### ISSUE TITLE
Integrate wiringPi for RF Plugins 

### ISSUE THREAD

**Issue by antagosteenl** [oznu/docker-homebridge#194]
Hello, is ist possible to implement wiringPi in the docker file? I couldn’t build it inside the container. I like to use ist for RF 433MHz Switches.

Thanks! And best regards

**Comment by oznu** [comment]
Hi @antagosteenl,

To do this with Docker you would have to pass through the relevant `/dev` device to the container. You might be able to get this to work; but it's not something I support.

Instead I recommend you install Homebridge natively using `systemd` as a process manager if you need access to GPIO:

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-&-Systemd-(Raspbian,-Ubuntu,-Debian)

**Comment by antagosteenl** [comment]
Hi @oznu,

Thanks for your fast response! 
You are doing a great job.
