### ISSUE TITLE
Multiple docker instances

### ISSUE THREAD

**Issue by Nyqi** [oznu/docker-homebridge#200]
When using multiple docker-compose instances config-x doesn't work on secondary homebridge instance, the first one is working.
 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/4690621/58382085-fd82bf80-7fc5-11e9-8613-5b218a230175.png">

I've changed config-x port in docker-compose.yml.

First homebridge docker instance:
```version: '2'
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=0
      - PUID=0
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8282
```

and the second one:
```version: '2'
services:
  homebridge_unstable:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ./config_unstable:/homebridge
    environment:
      - PGID=0
      - PUID=0
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8003
```

What's wrong?

**Comment by banana-ben** [comment]
Did you change the home bridge port and username in the second instance?
https://github.com/oznu/docker-homebridge/issues/32#issuecomment-338614339

**Comment by Nyqi** [comment]
Yes I did. Homebridge works, config-x doesn’t and there are 0 errors in logs.

**Comment by oznu** [comment]
Can you try logging out and logging back in?

**Comment by Nyqi** [comment]
wow, it works now. thanks

**Comment by oznu** [comment]
Thanks for confirming. I'll add a check for this in the UI.
