### ISSUE TITLE
Web UI Not Loading

### ISSUE THREAD

**Issue by jpetticrew** [oznu/docker-homebridge#202]
The web UI is not loading for me. It worked when I first installed Homebridge, but now when I try to access it, Safari and Chrome both fail to open the page. Homebridge is otherwise running fine, but I can't get into the UI to update plugins and stuff.

I am on Ubuntu Server 18.04 and running fully updated Docker.

**Comment by oznu** [comment]
Can you show the logs and your docker start command?

**Comment by jpetticrew** [comment]
Here is the text of my docker compose file. How can I get the logs for you?
`version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ${USERDIR}/docker/config/homebridge:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080`

**Comment by oznu** [comment]
Execute this command from the same directory you have the `docker-compsoe.yml` file in:

```
docker-compose restart homebridge
docker-compose logs -f homebridge
```

**Comment by jpetticrew** [comment]
It is this over and over again:
`Error: Cannot find module 'commander'
homebridge_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
homebridge_1  |     at Module.require (internal/modules/cjs/loader.js:637:17)
homebridge_1  |     at require (internal/modules/cjs/helpers.js:22:18)
homebridge_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js:7:19)
homebridge_1  |     at Module._compile (internal/modules/cjs/loader.js:701:30)
homebridge_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
homebridge_1  |     at Module.load (internal/modules/cjs/loader.js:600:32)
homebridge_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
homebridge_1  | internal/modules/cjs/loader.js:584
homebridge_1  |     throw err;
homebridge_1  |     ^
`

**Comment by oznu** [comment]
Try this:

```
docker-compose pull
docker-compose up -d
```

**Comment by jpetticrew** [comment]
That worked! But now I cannot log in... The default is admin/admin right?

**Comment by oznu** [comment]
The username and password should not have changed from what you had before. But if it's not working just delete the `${USERDIR}/docker/config/homebridge/auth.json` file and restart.

Replace `${USERDIR}` with whatever that equals for you.

**Comment by jpetticrew** [comment]
Up and running. Not sure what happened with the username and password... Thanks for your help!
