### ISSUE TITLE
2 homebridge on my synology Nas how?

### ISSUE THREAD

**Issue by henkied** [oznu/docker-homebridge#204]
I would like to run 2 homebridge on my synology Nas.

I have been running homebridge for a while through this manual, https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology

How can I easily get a 2 homebridge running?

I have read about it in this forum. I don't understand where to fill in the following:

If you're using Docker Compose just create a second entry under services:

version: "2"
services:
   homebridge:
     image: oznu / homebridge: latest
     network_mode: host
     volumes:
       - ./volumes/homebridge:/homebridge
   homebridge-two:
     image: oznu / homebridge: latest
     network_mode: host
     volumes:
       - ./volumes/homebridge-two:/homebridge

Does anyone want to help me on my way?

**Comment by Krocko** [comment]
@henkied have you found a Solution?
