### ISSUE TITLE
homebridge-camera-ffmpeg enable audio?

### ISSUE THREAD

**Issue by jdawgydawg** [oznu/docker-homebridge#208]
Please be gentle I am 100% a n00b. 

I have 2 cameras set up using homebridge-camera-ffmpeg on a Synology NAS and they stream great in the Home app when audio parameter is set to false. 

I'd like to enable audio but the the only guidance is "To use audio ffmpeg must be compiled with --enable-libfdk-aac"

How do I do that? Is there something to add to the startup.sh file? Here is my current startup.sh file.

[startup.txt](https://github.com/oznu/docker-homebridge/files/3307816/startup.txt)

**Comment by th3cube** [comment]
Hi jdawgydawg,

the last Commit look promising. [Camera-ffmpeg](https://github.com/KhaosT/homebridge-camera-ffmpeg/commit/9740557a180a888d2ffc9213b25d20bae27c22b7)

> audio can be set to true to enable audio streaming from camera. To use audio ffmpeg must be compiled with --enable-libfdk-aac, see https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki, default false. Many ffmpeg binaries are not compiled with libfdk-aac, and to work around this issue, force the OPUS codec: "acodec": "libopus"

add this to your config.json

`"audio":` `true,`
`"acodec":` "libopus"`

**Comment by jdawgydawg** [comment]
Thank you.

I have added those to my config and now the live video comes through. Still no audio though :(

**Comment by vswraith** [comment]
Still an issue, anyone know how to enable audio?

**Comment by jdawgydawg** [comment]
Still an issue for me. Adding libopud got me a volume slider but still no sound :(

**Comment by nrosa2002** [comment]
Hi,

The 
"audio": true,
"acodec": "libopus"

addition, doesn´t do it for me. Still no sound and actually stalls the perfectly working image. Doesn´t update and when you press for live feed, it simply stalls.
Any clue how to solve this?

**Comment by UziKhana** [comment]
`brew tap homebrew-ffmpeg/ffmpeg`

Then

`brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-fdk-aac`

from [stackoverflow](https://stackoverflow.com/a/55108365)

**Comment by apfelnutzer** [comment]
See [Stackoverflow](https://stackoverflow.com/questions/60294906/erroroutput-file-0-does-not-contain-any-stream-ffmpeg) - maybe the order of the parameters is wrong?

I've got the same issue - camera works in HomeKit without audio but as soon as I enable auto the log shows `[error] Output file #1 does not contain any stream`...
