### ISSUE TITLE
Docker Homebridge config-ui-x http folder path

### ISSUE THREAD

**Issue by RSMBS** [oznu/docker-homebridge#210]
I want to create an virtual hast over the Web Station for Homebridge.
But I cannot find the HTTP root folder path for Homebridge.
Can you help me out?

Best Regards

**Comment by oznu** [comment]
Hi,

It doesn't have one as it's served by its own HTTP server. The defaults Web Station has to create a VHOST are also incompatible with the UI - you're probably going to need to manually edit the Apache config:

https://github.com/oznu/homebridge-config-ui-x/wiki/Reverse-Proxy:-Apache
