### ISSUE TITLE
access the root folder on synology

### ISSUE THREAD

**Issue by djrams10** [oznu/docker-homebridge#212]
Hello, is it possible to access the root folder on synology? I have created a 2nd instance homebridge and I do not have access to his file. can be with a root access? with UI config interface? Thank you in advance.

**Comment by oznu** [comment]
When creating the container make sure you set up the volume correctly. The mount path **MUST** be `/homebridge`, not `/homebridge 2` as you have defined.

![image](https://user-images.githubusercontent.com/3979615/61991873-ae2a3f80-b099-11e9-9d08-74b3f223a5bf.png)

**Comment by djrams10** [comment]
even if I already have one? it's not going to be a problem of conflict? the files of both instances will end up in the same place?

**Comment by oznu** [comment]
Yes. This is the path **inside** the container, which always need to be `/homebridge`. Set local path to be unique:

![image](https://user-images.githubusercontent.com/3979615/61991987-81772780-b09b-11e9-85aa-4611f8b5e739.png)

**Comment by djrams10** [comment]
I just did it and it does not work anymore.

<img width="874" alt="Capture d’écran 2019-07-27 à 10 28 21" src="https://user-images.githubusercontent.com/28505910/61992039-4bb14f00-b059-11e9-9422-d6f8c16469d7.png">

**Comment by oznu** [comment]
You need to change the port in your config.json to not be the same as your first instance.

**Comment by djrams10** [comment]
how can I do it? Thanks

**Comment by oznu** [comment]
https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology#4-customising-configjson

**Comment by djrams10** [comment]
I'm sorry, but I do not see how. at no time I have the opportunity to change the ports

**Comment by djrams10** [comment]
Thanks I find, in the config.json file. All works perfectly. Thank you

Thank you I found in the config.json file. Everything works perfectly. Thank you
Can I create a shortcut on the desktop as for the first instance or not?

<img width="146" alt="Capture d’écran 2019-07-27 à 10 52 10" src="https://user-images.githubusercontent.com/28505910/61992298-9bdde080-b05c-11e9-8f90-7cc6478ad5ac.png">

**Comment by oznu** [comment]
Hi @djrams10,

I don't know of a way to do this without the SPK sorry.

**Comment by djrams10** [comment]
thank you for your help in any case and your great work. With your interface, it changes everything when users like me want to use homebridge. Thank you again, it's a great job.

**Comment by oznu** [comment]
You're welcome. I'm glad you got it sorted.
