### ISSUE TITLE
Downgrade nodeJS

### ISSUE THREAD

**Issue by misanthrophy** [oznu/docker-homebridge#213]
Hi, I am new to docker, but I want to give it a try to improve stability of my raspberry pi. 

Because a specific homebridge only works with node 8.16 and nothing newer, so I want to know, what can I do, to downgrade from node 10.16.0 to 8.16? 

I am using a Raspberry Pi 4 with Raspbian Buster and the nightly docker image. 

Thanks in advance!

**Comment by oznu** [comment]
Hi @misanthrophy,

It's strange a plugin would not work correctly on 10.x while it does on 8.x; but if this is the case you will need to build your own image (you can modify this one for personal use).

This image uses the current LTS (long term support) version of Node.js, currently that is v10; in October this will change to v12.
