### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by volschin** [oznu/docker-homebridge#214]
Analyzing the created docker Image history it can be seen, that 270 MB of the 470 MB comes from the apk install.
Homebridge changed its architecture of used packages and in my opinion with version 0.4.50 make, g++, python and lib-avahi should no longer be needed.

If they are needed for an additional Plugin they could be offered to be placed in the start script.

This would help to reduce the size significantly.

**Comment by oznu** [comment]
Hi @volschin,

Thanks for your suggestion. A number of rather popular plugins still require these tools to compile native modules, as this is now quite a popular Docker image (> 1 million pulls per month) I'm hesitant to make a change that would break existing installations.

**Comment by volschin** [comment]
With release 0.4.42 of HAP-NodeJS (2018-05-06) mdns was replaced by native bonjour-hap. There should be no need of libavahi-dev anymore.

**Comment by oznu** [comment]
Hi @volschin,

This is true, and why I am able to provide a `no-avahi` [image variant](https://github.com/oznu/docker-homebridge/wiki#image-variants). 

Some existing plugins still use the `mdns` package however, for example:

*  [homebridge-dacp](https://github.com/grover/homebridge-dacp/blob/master/package.json#L20)
* [homebridge-tradfri](https://github.com/jesper-lindberg/homebridge-tradfri/blob/master/package.json#L31)
* [homebridge-openhab2](https://github.com/tommasomarchionni/homebridge-openhab2/blob/master/package.json#L31)
* [homebridge-automation-chromecast](https://github.com/paolotremadio/homebridge-automation-chromecast/blob/master/package.json#L27)

While it would be good for these plugins to swap to the native js implementation of bonjour (like [homebridge-alexa](https://github.com/NorthernMan54/homebridge-alexa) has done), removing support right now would break these plugins. Setting up avahi and dbus requires a bit more work than just installing the package via `startup.sh`.

**Comment by volschin** [comment]
Thanks for the clarification. 
dacp has a package entry but nowhere used it in the code. Opened an issue there.
Tradfri could probably easyly change to bonjour. Opened a ticket also.

I like your image. I think its the best available, also with s6.
