### ISSUE TITLE
homebridge-samsung-tizen on LibreELEC

### ISSUE THREAD

**Issue by Braveshock** [oznu/docker-homebridge#217]
I'm writing in connection with homebridge problem I have on libreelec os. I followed all steps based on the below link :
https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-LibreELEC
 
and unfortunately I dont see the accesories. Basiaclly I have at home hue bridge and wanted to install homebridge-samsung-tizen plugin on my RPi4 to be able to switch on/off my tv. When I log in to homebridge I see that everything works based on log view - Homebridge and Samsung Tv but I can't find any accessory using iOS Apple Home app
Can anyone help with that?
Thanks in advance

**Comment by oznu** [comment]
I'd you're not seeing anything in the Home app when you click "Don't have a code or can't scan" - try changing the username and pin in the config.json to something different and then restart the container.

I believe that accessory exposes the TV as a standalone accessory, so if you have already paired Homebridge, you will still need to go through the process of adding a new accessory via the Home app.

**Comment by oznu** [comment]
If you enabled the web ui you can click the "reset Homebridge" link at the very bottom of the Status page; this will change the Homebridge PIN and Username for you.

**Comment by Braveshock** [comment]
Hey,   Thanks so much for the update.  Basically I did what you said and occasionally it worked but not every time. I restarted via web ui, got new pin and username but didn&#39;t see the accessory when clicked &#34;I don&#39;t have a code o cannot scan&#34;. I was able to add my Samsung TV once I scanned the QR code but as mentioned it wasn&#39;t always. When I restarted only raspberry the Samsung TV button is not responding.  Another think is what I noticed when disable LibreELEC&#39;s Avahi Service using avahi-daemon commends I&#39;m loosing every time my ssh server and cannot connect with my Pi4.   Is there any other way to make that happen? I already set up the Homebridge on my second RPi3 but I wanted to use that one for my projects. MyPi4 is where I have Kodi, its always on so that&#39;s the reason I wanted to have Homebridge there. I thought about OSMC system for Kodi and Homebridge but don&#39;t know how it might work too.  Thanks  Regards  Mateusz  Dnia 4 sierpnia 2019 08:42 oznu &lt;notifications@github.com&gt; napisał(a):  If you enabled the web ui you can click the &#34;reset Homebridge&#34; link at the very bottom of the Status page; this will change the Homebridge PIN and Username for you.  —  You are receiving this because you authored the thread.  Reply to this email directly,  github.com view it on GitHub , or  github.com mute the thread .
