### ISSUE TITLE
Update on Synology

### ISSUE THREAD

**Issue by giss69** [oznu/docker-homebridge#218]
Hallo,

i tried to update homebridge on Synology because of the new version of node.
if i follow this steps:
Updating Homebridge

To update to the latest version of Homebridge and the oznu/homebridge container:

1.Download the latest version of Homebridge
2.On the Container tab stop the existing Homebridge container
3.Edit the existing container and change it's name to homebridge-old
4.Select homebridge-old then click Settings then Duplicate settings
5.Name the container homebridge
6.Start the homebridge container
7.Delete the homebridge-old container

i have exactly the same version of HB with the old node as before.
what i'm doing wrong?
Should i after rename HB install the new version first? 

Thank you

**Comment by oznu** [comment]
If those steps aren't working; try deleting the container and the image, and recreating it. If you point the `/homebridge` volume mount to the same location you shouldn't loose any config, plugins, or have to re-pair with HomeKit.

Alternatively you might consider using https://github.com/oznu/homebridge-syno-spk which ensures everything is up-to-date everything time it starts.

**Comment by giss69** [comment]
@oznu 
Thank you for a quick replay. 
1. I used your spk before it’s greate! But now I prefer to install it bei myself, because I’m using 8 homebridge for different plugins. 
2. I guess, that I missing anything bei these steps. Should I install a new downloaded version first after renaming the old one? Should I use same folder where the old was?
 I tried it as well, but when I duplicated the old setting and use the name of my HB, it says „ the name is already in use“. 
Thank you

**Comment by oznu** [comment]
I haven't tested those steps since I created the wiki article, it could be they no longer work on the current version of DSM.

DSM makes it really hard to update an existing containers image.

**Comment by nicoduj** [comment]
Hi, I followed those steps (except that I have inverted steps 3 and 4 : I have set a new name to the duplicated container, and then renamed the old one and the new one . It worked like a charm !

**Comment by giss69** [comment]
@nicoduj 
thank you for you experience. After the downloading a new version of HB (step 1) and stopping 
old HB (step 2) did you install first a new version of HB? if yes which folder und name did you choose?
thank you

**Comment by nicoduj** [comment]
@giss69 What I do is :  
1 - select the registry tab on the docker UI on my synology, search, keyword "oznu", double click on the line oznu / homebridge, and select latest
2 - I wait for the new image to be downloaded (a (1) on image tab on the left will disappear when it will be done)
2.On the Container tab stop the existing Homebridge container
3.Select homebridge container then click Settings then Duplicate settings
4.Name the container homebridge-new
5.Edit the existing container and change it's name to homebridge-old
6.Edit the homebridge-new container and change it's name to homebridge
6.Start the homebridge container
7.Delete the homebridge-old container (after a while)

**Comment by giss69** [comment]
@nicoduj 
thank you! it works! its funny, but it did it well before!
the problem was, that under advancing setting i have the indication that its still the old version, but if i check it on terminal its a new one!
<img width="615" alt="Bildschirmfoto 2019-08-15 um 16 31 04" src="https://user-images.githubusercontent.com/46527669/63102082-b2e86200-bf7a-11e9-91e4-cc97b681cc5b.png">
<img width="268" alt="Bildschirmfoto 2019-08-15 um 16 34 57" src="https://user-images.githubusercontent.com/46527669/63102083-b2e86200-bf7a-11e9-9647-8ee6666cd80e.png">

**Comment by nicoduj** [comment]
yes, since you copy the docker settings the var are not up to date I think

**Comment by giss69** [comment]
is there a possibility to show correct date?

**Comment by nicoduj** [comment]
you can add TZ env variable to the docker config  : 

![image](https://user-images.githubusercontent.com/19813688/63109391-65bfbc80-bf89-11e9-98d6-2c467e2f983a.png)
