### ISSUE TITLE
Alexa plugin doesn't work right

### ISSUE THREAD

**Issue by MaurizioB84** [oznu/docker-homebridge#219]
**Describe Your Problem:**
I try to setup alexa home bridge plugin but doesn't work in the container with docker-compose script, Maybe depending on insicure start.
**Logs:**

2019-08-07T13:07:55.924Z hapNodeJSClient HAP Discover failed HomeBridge http://192.168.2.22:51826 invalid PIN or homebridge is not running in insecure mode with -I IncomingMessage

**Docker Start Command:**
docker-compose.yaml
version: '3'
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    depends_on:
      - home-assistant
    ports:
      # console
      - 4000:4000
    volumes:
      - ./homebridge/config/:/homebridge
      - ./ssl:/ssl
      # - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Paris
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_INSECURE=1
      - HOMEBRIDGE_CONFIG_UI_PORT=4000

**Homebridge Config:**
    "bridge": {
        "name": "HomeBridge",
        "username": "CA:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
        {
            "name": "Alexa",
            "username": "xxxxxxx",
            "password": "xxxxxx",
            "pin": "031-45-154",
            "routines": false,
            "debug": true,
            "platform": "Alexa"
        }

**Environment:**

* **Host Operating System**: Raspbian
* **Docker Version**: Docker version 19.03.1, build 74b1e89, docker-compose version 1.24.1, build 4667896
* **Image Tag / Type**: latest

**Comment by oznu** [comment]
Hi @MaurizioB84,

Please check the insecure mode setting in the Homebridge Config UI X interface, this has the power to override the variable set at run time.

Click the Docker logo on the menu bar -> Settings.

![Homebridge Config UI X Docker Settings](https://raw.githubusercontent.com/oznu/homebridge-config-ui-x/master/screenshots/homebridge-config-ui-x-docker-settings.png)

https://github.com/oznu/homebridge-config-ui-x/wiki/Enabling-Accessory-Control#docker

**Comment by MaurizioB84** [comment]
many thanks,

now it's works! sorry but I don't see this part of the guide :(

I tried only with the config on docker-compose.yaml...

Resolved

👍 👍 👍

**Comment by oznu** [comment]
Happy to help.

The idea was to make it easy for people to toggle it on and off without having to recreate their entire container (which is a pain on Synology DSM). The override only happens the the first time it's changed via the UI and writes the settings to `.docker.env` in your '/homebridge` volume mount.

**Comment by boscorelly** [comment]
Thank you !
the unsecure mode setting in docker-compose is not used, i had to verride
