### ISSUE TITLE
Updating homebridge-config-ui-x to 4.5.2 causes homebridge-config-ui-x to stop working

### ISSUE THREAD

**Issue by HammerAce42** [oznu/docker-homebridge#220]
**Describe Your Problem:**
UI was showing an update to the homebridge-config-ui-x plugin available. I tried installing and upon restarting, the UI failed to load. I deleted the existing docker container, updated to the latest using docker-compose pull homebridge and recreated it.

To ensure it wasn't a coincidence, I tried updating again once the new container was up and running and had the same outcome.

**Logs:** (including only the pieces which seem relevant)

homebridge_1  | [8/9/2019, 3:55:59 AM] Error: Cannot find module 'commander'
homebridge_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
homebridge_1  |     at Module.require (internal/modules/cjs/loader.js:692:17)
homebridge_1  |     at require (internal/modules/cjs/helpers.js:25:18)
homebridge_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/index.js:12:19)
homebridge_1  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
homebridge_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
homebridge_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)
homebridge_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
homebridge_1  |     at Module.require (internal/modules/cjs/loader.js:692:17)
homebridge_1  |     at require (internal/modules/cjs/helpers.js:25:18)
homebridge_1  |     at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:72:23)
homebridge_1  |     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:153:14)
homebridge_1  |     at Array.forEach (<anonymous>)
homebridge_1  |     at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:145:22)
homebridge_1  |     at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
homebridge_1  |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
homebridge_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
homebridge_1  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
homebridge_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
homebridge_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)

[8/9/2019, 3:55:59 AM] Error: The requested platform 'config' was not registered by any plugin.
homebridge_1  |     at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
homebridge_1  |     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
homebridge_1  |     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
homebridge_1  |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
homebridge_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
homebridge_1  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
homebridge_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
homebridge_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)
homebridge_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
homebridge_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
homebridge_1  |     at startup (internal/bootstrap/node.js:283:19)
homebridge_1  |     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
homebridge_1  | [8/9/2019, 3:55:59 AM] Got SIGTERM, shutting down Homebridge...
homebridge_1  | s6-applyuidgid: fatal: unable to exec homebridge-config-ui-x: No such file or directory
homebridge_1  | s6-applyuidgid: fatal: unable to exec homebridge-config-ui-x: No such file or directory
homebridge_1  | s6-applyuidgid: fatal: unable to exec homebridge-config-ui-x: No such file or directory

**Docker Start Command:**

Docker Compose file:

version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=80

**Environment:**

* **Host Operating System**: Raspbian

**Comment by oznu** [comment]
Hi @HammerAce42,

I can't replicate, but perhaps npm failed to install the updated package correctly.

You can get back up and running by executing these commands in the same folder as your `docker-compose.yml` file:

```
docker-compose down
docker-compose up -d
```

**Comment by HammerAce42** [comment]
Had it happen twice though. I am already back up and running since I deleted and recreated the container one more time, but I still see the update pending. Are you planning to publish an updated docker container with the newer version of the UI plugin?

Here's something that might have caused me to get into a weird state:
I tried to update the ui plugin by using sudo npm install -g --unsafe-perm homebridge-config-ui-x via the terminal in the UI a few days ago since I was trying the homebridge-gsh plugin and hadn't seen the note that it was still work in progress, so thought I wasn't seeing the setup UI due to an outdated version of the ui plugin. I ultimately ran sudo npm uninstall -g --unsafe-perm homebridge-config-ui-x to undo any effects of that right before installing the update via the UI for the first time earlier today. In any case, I thought deleting and recreating the docker container would get me back to a good state, but that seems not to be the case? Is there a more thorough way to reset to get to a good state?

**Comment by oznu** [comment]
I just published a new image. To update:

```
docker-compose pull
docker-compose up -d
```

While uninstalling the homebridge-config-ui-x  plugin would have caused things to break, a new container should have fixed everything up.

**Comment by HammerAce42** [comment]
Thanks for the new image! That obviously takes care of the update notification for the ui plugin. I'll close this out for now and re-open in case the same problem arises when the next ui plugin release is published.

**Comment by HammerAce42** [comment]
This occurred again today when trying to update config-ui-x to 4.6.0. Any suggestions on how to get to a clean config since the below commands clear up the issue temporarily but it comes back each time I attempt a config-ui-x update?

```
 docker-compose down
docker-compose up -d
```

If all fails, I plan to just re-image the SD card and setup everything again, but hoping it doesn't come to that.

**Comment by jpetticrew** [comment]
+1 for me. Every time I try to update to 4.6.0 I have to manually restart using 
`docker-compose down
docker-compose up -d`

**Comment by HammerAce42** [comment]
So I ended up re-imaging and setting everything up again, only to find that the issue still occurs when updating. Unfortunately, I only saw jpetticrew's +1 after I had started the re-imaging.

Sounds like pulling a new docker image with the latest config-ui-x is the workaround.  Onzu, could you update the docker image to include the published 4.6.0 version of config-ui-x (the one in the latest docker image is currently homebridge-config-ui-x v4.6.0-beta.40, which still shows the update prompt). Also, may I suggest disabling updates to that specific plugin via the UI until the root cause is figured out and addressed?

**Comment by killerrabbit33** [comment]
I have the same problem. Pulling a new image works just fine (as long as it has an updated plugin!) but updating through the UI itself still breaks the plugin.

**Comment by oznu** [comment]
Are you all running on Raspberry Pi?

**Comment by killerrabbit33** [comment]
Yes, I'm running on a 3B with Docker.

**Comment by oznu** [comment]
Could you try this, in Homebridge Config UI X go to the Terminal (Docker logo -> Terminal) and run this command then restart (using the UI):

```
npm install -g --unsafe-perm homebridge-config-ui-x@latest
```

If that works I have a theory why it might be breaking.

**Comment by killerrabbit33** [comment]
Did not work. It never finished the install--it stopped at about 2/3 of the way for more than 10 minutes, and restarting after that leads to the same error.

**Comment by oznu** [comment]
Thanks for testing. That rules out one theory I had. Can you try this:

1. Open the UI to the Status page in a browser tab and just leave it running there while you complete the following steps.

2. From the command line on your Raspberry Pi exec into you container

```
docker-compose exec homebridge sh
```

3. Try the install command here:

```
npm install -g --unsafe-perm homebridge-config-ui-x@latest
```

**Comment by killerrabbit33** [comment]
Seems to get me the same result. This is where it hangs:
`[            ......] \ remove:homebridge-config-ui-x: sill doSerial remove 10`
It doesn't show the progress bar but it's about 2/3 of the way there.

Many thanks for looking into this--It's late where I am so I'll return tomorrow to keep working.

**Comment by jpetticrew** [comment]
FWIW, I am running on Ubuntu Server.

**Comment by oznu** [comment]
I can't replicate this on a Raspberry Pi 4 or Ubuntu Server 18.04 (my main docker machine and the only platform I actually test everything on).

While it does hang on `[ ......] \ remove:homebridge-config-ui-x: sill doSerial remove 10`, it will always resume after a few minutes.

I'm thinking this is due to some file locking like issue, where the npm update command is trying to overwrite a file that's currently in use. While I have no immediate fix for this issue, I do have plans to do an "offline" upgrade, where Homebridge Config UI X will itself down to update itself which should alleviate this issue.

**Comment by jpetticrew** [comment]
Mine also hangs on that step but always comes back. Mine fails on the restart. It never comes back up.

**Comment by oznu** [comment]
In the meantime, I just pushed an image update with the latest UI; v4.6.0 and the new Node.js v10.16.3.

**Comment by killerrabbit33** [comment]
Sounds good. Thank you again for investigating!

**Comment by HammerAce42** [comment]
I noticed v4.6.1 of ui-x is now available. @oznu, have you made any changes that might fix the upgrade issue? If so, I will give updating a shot.

**Comment by jpetticrew** [comment]
I just tried to update. Same issue. Update “finished” and told me to restart Homebridge and it failed to restart. Had to do it manually.

**Comment by oznu** [comment]
Nothing new for this issue sorry. There is a new docker image out.

**Comment by oznu** [comment]
After a failed upgrade, where the UI is refusing to start, can you please provide the output from this command (executed inside the container):

```
ls -la $(npm -g prefix)/lib/node_modules/homebridge-config-ui-x/node_modules
```

**Comment by killerrabbit33** [comment]
I already pulled a new image with the updated plugin. Is there a way to pull the previous build so I can try to update the plugin?

**Comment by oznu** [comment]
4.6.2 should fix this, but it won't help you getting you to 4.6.2 - so you may need to update the docker image manually again.

**Comment by killerrabbit33** [comment]
Thank you! Updated the image and everything is working. Looking forward to trying the plugin update. Thanks again for looking into this.
