### ISSUE TITLE
Fragile config.json

### ISSUE THREAD

**Issue by Hochiss** [oznu/docker-homebridge#221]
Currently, a single mistake in config.json would make all devices n/a.

I wonder if possible each device has its own "config.json", thus to single out that device if that plugin mis-configurated. 

Also how could homebridge (e.g. in Docker) be more stable and robust?  maybe:
- please stop homebridge continuously reboot and generate error log;
- How to report if node.json global server down or not reachable, or npm package corrupt; 
- health check for each plugin?  

Today I notice my docker ID has been changed, thus not able to ssh login to. Strange! how could that be? Does google (node.js) haven access to my docker container? or Synology can? 

later on, I notice also one of plugin was uninstalled and I am not conscious about that! very strange. (for more details, I manually installed @solowalker27's [onkyo git](https://github.com/solowalker27/homebridge-onkyo/issues/5#issue-480239170), which isn't yet in [npm](https://www.npmjs.com/), but in ui-x shows link to @ToddGreenfield, the ver.0.7.1. should be correct coming from prior).

**Comment by Hochiss** [comment]
@oznu thanks for your explanation. In fact, I am getting more and more concerned about the security and privacy about using homebridge(HB):
- I notice if I disconnect the docker/NAS  from internet, ui-x will not show @ to the git, and every new start of HB will failed;
- as [HB creator post at twitter](https://twitter.com/nfarina/status/1055561540710019073?s=20)says, "I have read the floating commands ...", (see the foggy background of HB), that means everyone's command will be readable publicly; 
- in general, node.js server is of google, so "potentially" google could identify everyone into their kitchen or bedroom, thus complete home network... 

sorry for this off-topic... your opinion?

**Comment by oznu** [comment]
> I notice if I disconnect the docker/NAS from internet, ui-x will not show @ to the git,

The UI makes calls are made to the npm registry to get details about the package and check for updates. The only external endpoints on the internet the UI will establish connections to are:

* https://registry.npmjs.org
* https://api.github.com

>  and every new start of HB will failed

Packages are downloaded from the npm registry when the docker container starts. These are downloaded from https://registry.npmjs.org.

> as HB creator post at twittersays, "I have read the floating commands ...", (see the foggy background of HB), that means everyone's command will be readable publicly;

I think you misunderstand, those "floating commands" are not in real time or actual users utterances. The Homebridge core does not make any external calls to the internet and at no point do any of the owners or contributors to Homebridge have control over or even know what you're doing with the software. The great thing about HomeKit in general is that it works 100% locally. 

Compare this to any Alexa or Google Assistant device - all that communication will be routed via the internet, through Google and the device manufacturers servers. These guys are definitely tracking you.

> in general, Node.js server is of google, so "potentially" google could identify everyone into their kitchen or bedroom, thus complete home network...

Node.js is an open source project of the Linux Foundation, while Google maintains the V8 runtime,  you can be sure this is not reporting anything back to Google, the open source community would be outraged and big business wouldn't be touching it if this was the case.

Don't trust me though, check out the source code: https://github.com/nodejs/node

> sorry for this off-topic... your opinion?

^
