### ISSUE TITLE
Unraid docker install: how to ssh into homebridge container?

### ISSUE THREAD

**Issue by misterwiggles** [oznu/docker-homebridge#223]
I followed some general guidelines posted here and on the Unraid forums to setup a docker template for this container. Everything is working fine.

Two issues:

1. I can’t seem to figure out how to setup ssh to allow me to access the running Homebridge server. I followed the keygen instructions that were posted here and it seemed to work. But the final step of ‘abc’ user didn’t take. The only way I could run that final step was to use my root user credentials. When I try to ssh into the container from Terminal on my Mac I get an error that the host can’t be found. Which may be the 2nd issue below.

2. When I look at my running docker containers on Unraid I see Port Mappings (app to host) info for every container EXCEPT the homebridge container. My other containers that are set to HOST show a mapping of my Unraid server IP address:container port ID. But not the homebridge one. The homebridge container is set to HOST and it is running fine. I suspect this mapping issue is why I can’t get ssh working.

Thanks

**Comment by oznu** [comment]
I would just SSH into the NAS then exec into the homebridge docker container.

```
docker exec -it homebridge sh
```

While setting up SSH in the container is not something I support, you will need to make sure the ssh daemon is actually running, and that it's set to a port other than 22 - as this is probably in use by the host. Port mappings are ignored when running in `--net=host` mode.
