### ISSUE TITLE
DSM 6.2.2 No Longer Has "Use the same network as Docker host"

### ISSUE THREAD

**Issue by broberts01** [oznu/docker-homebridge#224]
Do I need to do anything else? Seems to be running OK as per logs, but iOS doesn't see it.

**Comment by Krocko** [comment]
On my DS 218+ it is available. DSM 6.2.2-24922 Update 3
It was also there with Update 2

**Comment by oznu** [comment]
Hi @broberts01,

Just tested 6.2.2-24922 and the option is there. See screenshot below:

![image](https://user-images.githubusercontent.com/3979615/63637166-ad96c000-c6bc-11e9-9d9e-3c8fe73d3b98.png)

**Comment by oznu** [comment]
Host mode is absolutely required to run this container, if it's not enabled, that why you're unable to pair with iOS.

**Comment by broberts01** [comment]
Ah I see the issue -- I was modifying the container, not the image.  Thanks for your help!
