### ISSUE TITLE
PACKAGES=ffmpeg not working again like in issue #153

### ISSUE THREAD

**Issue by blysik** [oznu/docker-homebridge#225]
I'm using oznu/homebridge:1.7.9 on an intel NUC.

I'm seeing the same error as in issue #153 

```
/homebridge # ffmpeg
Error relocating /usr/lib/libgnutls.so.30: getrandom: symbol not found
/homebridge #
```

Am I missing something?  Thanks!

**Comment by oznu** [comment]
Please try the latest version. I don't tag releases unless I'm making a breaking change which I haven't done in a while.
