### ISSUE TITLE
Error after Synology docker 18.0.9.0-0505 Version upgrade

### ISSUE THREAD

**Issue by VoltIcaRus** [oznu/docker-homebridge#227]
*Note Added By Project Maintainer on 2019-08-29:*

As [per this post on the Synology Forums](https://community.synology.com/enu/forum/15/post/128146) and [this post on Reddit](https://www.reddit.com/r/synology/comments/cw75ck/dockercompose_dont_pass_anymore_env_to_docker/?utm_source=amp&utm_medium=&utm_content=post_body) the latest Docker Package provided by Synology is broken and is not populating environment variables for containers created using [Docker Compose](https://docs.docker.com/compose/).

This issue may prevent Homebridge Config UI X from loading for users who have manually created their containers using `docker-compose` or users who used the [Synology Homebridge SPK](https://github.com/oznu/homebridge-syno-spk) as this uses `docker-compose` in the background.

There are currently a few work arounds you can implement while we wait for Synology to fix their Docker package.

#### Best Option - Downgrade The Synology Docker Package

Downgrading the Synology Docker package to 17.05 will make everything work as it did before. Details instructions on how to downgrade can by found in [this post on the Synology Forums](https://community.synology.com/enu/forum/15/post/128146). The SPK for Docker 17.05 can be found [here](https://usdl.synology.com/download/Package/spk/Docker/17.05.0-0401/).

#### Another Option - Update the Docker Container and manually configure the UI in config.json

The latest version of the oznu/homebridge Docker image will run the UI correctly even without the required environment variables, the caveat being you need to add the basic config for the UI in the `/homebridge/config.json`. Only a basic config is required to tell the UI to start, it will figure out the rest:

```json
"platforms": [
    {
      "platform": "config",
      "name": "Config",
      "port": 8080
    }
]
```

#### Not Recommended Method - Manually add environment variables to the container using the Synology Docker App in DSM

This method works, but your containers will break again if you ever recreate or update the image. This method is not recommended.

---
*Original Issue by VoltIcaRus:*
----------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/3735740/64019889-49b44180-cb6b-11e9-8635-950af3e68350.png)

This is the official answer from Synology.
Do not update
Please wait
----------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/3735740/63783154-724bf980-c927-11e9-8c46-61fcd578b390.png)

![image](https://user-images.githubusercontent.com/3735740/63783466-0a49e300-c928-11e9-9b6f-03aec76521f9.png)

New Synology's Docker Update
I updated it, but in Homebridge Config UI X
I can't see the log and I can't control the container.
Also, when I look at the container log, the log like the second picture appears indefinitely.
There seems to be no problem with the iot device control, but it continues to accumulate meaningless logs.
Synology's docker changed from 17.05 to 18.09 docker-compose changed from 1.14 to 1.24
Is it a problem because env is not reflected properly?

I downgraded to version 17.05.0-0401
No error was found.

Thank you for providing a great program! thank!

**Comment by oznu** [comment]
The environment variables that tell the UI it's running in docker look like their missing.

```
HOMEBRIDGE_CONFIG_UI=1
HOMEBRIDGE_CONFIG_UI_PORT=8080
```

**Comment by VoltIcaRus** [comment]
It seems to be a Synology’s mistake. Environment variables are not reflected at all and they do not work. They are stupid.  Thanks for the reply!

**Comment by oznu** [comment]
Did you solve the issue somehow or is it a bug in their latest update?

**Comment by VoltIcaRus** [comment]
This is a bug in the latest update. Environment variables are not applied when load a container with docker-compose.

**Comment by oznu** [comment]
Hmm that's going to cause issues with my SPK loader.

**Comment by oznu** [comment]
Solution is to downgrade?

https://www.reddit.com/r/synology/comments/cw75ck/dockercompose_dont_pass_anymore_env_to_docker/?utm_source=amp&utm_medium=&utm_content=post_body

**Comment by oznu** [comment]
https://community.synology.com/enu/forum/15/post/128146

**Comment by VoltIcaRus** [comment]
Yes, downgrade to 17.05.0-0401

**Comment by VoltIcaRus** [comment]
For users who have already updated, please receive the file from https://usdl.synology.com/download/Package/spk/Docker/ and remove the existing dockers before installing

**Comment by scrytch** [comment]
Hi all,

My install was done using https://github.com/oznu/homebridge-syno-spk but it uses docker-compose to run.

I've got mine up and going by shutting down my oznu/homebridge container, then re-added/edited the environment variables to show below:

- PGID=100
- PUID=1024
- HOMEBRIDGE_CONFIG_UI=1
- HOMEBRIDGE_CONFIG_UI_PORT=8080

Note, this is different from standard setup of 1000/1000 for PGIU/PUID (which don't work on my Synology). I also have a different port than above so make sure you set yours correctly.

Mine is now working - recognises it's in Docker and UI, logs and updates function again.

Many thanks to oznu in the homebridge slacker for assistance.

Thanks,
Shane.

**Comment by chadman4** [comment]
> Yes, downgrade to 17.05.0-0401

Does this mean I will have to delete my current homebridge container first? Which means all plugins will be deleted?

Synology won't let me uninstall docker without deleting homebridge first.

**Comment by VoltIcaRus** [comment]
Data and containers are not deleted unless you intentionally delete the data. Common to all Synology Package installations.
There is no reason to be afraid.

> > Yes, downgrade to 17.05.0-0401
> 
> Does this mean I will have to delete my current homebridge container first? Which means all plugins will be deleted?
> 
> Synology won't let me uninstall docker without deleting homebridge first.

Data and containers are not deleted unless you intentionally delete the data. Common to all Synology Package installations.
There is no reason to be afraid.

**Comment by VoltIcaRus** [comment]
Also, if you don't have a container that needs to work with a lot of docker-compose and you're only working with homebridge, you won't get an error if scrytch tells you in the latest version
I'll wait for the synopsis to modify because I have to add environment variables to many containers manually.

**Comment by VoltIcaRus** [comment]
![image](https://user-images.githubusercontent.com/3735740/64019405-086f6200-cb6a-11e9-9ac0-48b75848d162.png)
This is the official answer from Synology.
Do not update
Please wait

**Comment by oznu** [comment]
It looks like Synology have removed the 18.0.9.0-0505 package from their repo for now.

**Comment by oznu** [comment]
Synology have released a new Docker Package that should have fixed this issue.
