### ISSUE TITLE
Bluetooth connectivity to Synology Docker Container

### ISSUE THREAD

**Issue by deadlyknapsack** [oznu/docker-homebridge#228]
I've been running Homebridge on a Pi for the better part of a year now. Overall, pretty happy with it. However, I'm starting to transfer a lot of applications to Docker Containers on my Synology. I set up Homebridge Docker Container on my DS716+ to check it out, but I run into some challenges when I want to install plugins that use Bluetooth connectivity. For example, I have a ton of Mi Flower sensors. The plugin (mi-flower-care) for my Homebridge on the Pi uses a Bluetooth dongle and needs some bluetooth packages and Noble (if I'm not mistaken). Is there a way to have this plugin run succesfully on Synology? For the sake of argument, let's assume I already have a Synology compatible Bluetooth adapter.

Thanks.

**Comment by sebyno** [comment]
I'm also interested. Want to leave my raspberry and use synology with docker.

**Comment by claesjacobsson** [comment]
Any progress?
