### ISSUE TITLE
Can't install via docker

### ISSUE THREAD

**Issue by Stooovie** [oznu/docker-homebridge#229]
When I try to run the commands from Install guide part 7 (docker run -d --restart=always --net=host \....), I get this:

c5ccbb21783aa37537334e8bdf842ab439d81c379f2a97f45fcf578a27f68223

and that's it. There are no existing containers. I run it in Libreelec. 

when i removed all containers, deleted and reinstalled Docker addon in LE and run the command, I get this:

> docker: Error response from daemon: Conflict. The container name "/homebridge" is already in use by container "c5ccbb21783aa37537334e8bdf842ab439d81c379f2a97f45fcf578a27f68223". You have to remove (or rename) that container to be able to reuse that name.

Any tips?

**Comment by oznu** [comment]
You have to remove (or rename) that container to be able to reuse that name.

```
docker rm -f homebridge
```

**Comment by Stooovie** [comment]
Thanks, I did that, this was AFTER I deleted the container. ps -a returned nothing and yet it spit out the error. Probably some caching issue. It went away eventually.
