### ISSUE TITLE
EOL of docker package on Synology

### ISSUE THREAD

**Issue by ceraz68** [oznu/docker-homebridge#231]
Hi I just got a warning of end of life for the docker package on Synology. I'm on a DSM412+ running the latest software. I understood that new installs won't work but existing installation of the package will operate (I assume unmaintained)

Anyone else seen this message? What would be the impact for docker-homebridge?

**Comment by rbhr** [comment]
@ceraz68 The Docker container engine is not going away, only Docker DSM which is the DiskStation Manager within a container.

**Comment by ceraz68** [comment]
OK thanks for clarifying, no need to worry then  :-)
