### ISSUE TITLE
FFMPEG Exited Error Code 2

### ISSUE THREAD

**Issue by JDogg016** [oznu/docker-homebridge#232]
```

**Describe Your Problem:**
When accessing any of my cameras I receive the log below

[9/2/2019, 6:38:29 PM] [Camera-ffmpeg] Start streaming video from Playground with 1280x720@299kBit                                              
[9/2/2019, 6:38:29 PM] [Camera-ffmpeg] An error occurs while making stream request                                                              
[9/2/2019, 6:38:29 PM] [Camera-ffmpeg] ERROR: FFmpeg exited with code -2   

The config.json file works fine and is follows:

{
                    "name": "Playground",
                    "videoConfig": {
                        "source": "-re -i rtsp://xxx:xxx@xxx.xxx.xxx.xxx:554/videoMain",
                        "stillImageSource": "-i http://xxx.xxx.xxx.xxx:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=JDogg016&pwd=helen143&",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10


This is my startup.sh file:

#!/bin/sh

#
# Docker Homebridge Custom Startup Script - oznu/homebridge
#
# This script can be used to customise the environment and will be executed as
# the root user each time the container starts.
#
# If using this to install plugins DO NOT use the global flag (-g).
#
# Example installing homebridge plugin:
#
# npm install homebridge-hue
#
# Example installing packages using default image (Alpine Linux):
#
# apk add --no-cache ffmpeg ffmpeg-libs libpcap-dev
#
# If you're running a debian based version of this container please use apt-get to install packages.
#

apk add --no-cache ffmpeg ffmpeg-libs
```

**Environment:**
Homebridge ozone no-avahi
Homebridge UI 4.6.1
Node JS 10.16.3
FFMPEG 0.1.12
Docker Version: 18.09

**Comment by JDogg016** [comment]
Anyone?

**Comment by JDogg016** [comment]
Please?!?!

**Comment by gmakathestig** [comment]
Ive the same issue

[9/13/2019, 8:14:25 PM] [Camera-ffmpeg] Snapshot from Front at 480x270
[9/13/2019, 8:14:25 PM] [Camera-ffmpeg] An error occurs while making snapshot request
[9/13/2019, 8:14:25 PM] [Camera-ffmpeg] Start streaming video from Front with 640x360@132kBit
[9/13/2019, 8:14:25 PM] [Camera-ffmpeg] An error occurs while making stream request
[9/13/2019, 8:14:25 PM] [Camera-ffmpeg] ERROR: FFmpeg exited with code -2

Checked the streams on vlc with no issue

**Comment by JDogg016** [comment]
So since the issue again I’ve done the following: I removed FFMPEG from my homework. I created an entire separate instances home bridge installed FFMPEG So since the issue began I’ve done the following: I removed FFMPEG from my homework. I created an entire separate instance of home bridge installed FFMPEG with Avahi. 

Same result. Error Code 2 and yes o can see the stream in VLC

**Comment by JDogg016** [comment]
Anyone. I feel like error Code 2 should be about the most critical of all errors (after error Code 1 of course). 

This used to work perfectly, I have no idea what I did to break everything.

**Comment by coobin** [comment]
Ive the same issue, how I can solve this problem？
