### ISSUE TITLE
Password-less sudo on synology

### ISSUE THREAD

**Issue by sommertrip** [oznu/docker-homebridge#233]
Hello, 
I have the following problem with updating plugins. 

USER: abc
DIR: /homebridge
CMD: sudo -E -n npm --no-update-notifier install --unsafe-perm --save homebridge-hue@latest

sudo: a password is required

Command failed. Please review log for details.

Following the advice in readme from 

Password-less sudo required
For sudo mode to work password-less sudo is required. You can enable password-less sudo by adding this entry to the bottom of your /etc/sudoers file (use visudo to edit the file!):
homebridge    ALL=(ALL) NOPASSWD: ALL

I have the problem that running homebridge in docker/synology doesn´t show me the option or I don´t know where to find it.

**Comment by oznu** [comment]
Hi @sommertrip,

It looks like you're not running the UI using the [Supported Method](https://github.com/oznu/homebridge-config-ui-x/wiki/Enabling-UI-with-Docker).

> To enable Homebridge Config UI X start the container with the HOMEBRIDGE_CONFIG_UI=1 environment variable. This is the only supported method of running the UI in Docker.

I would recommend updating your docker container to the latest version at the same time.
