### ISSUE TITLE
DOes this guide works with Ubuntu?

### ISSUE THREAD

**Issue by NDNELSON** [oznu/docker-homebridge#234]
Hello I want to know if I can use it inside docker on mi ubuntu O.S. I am running home assistasnt(hassio) with docker and I want to use this for integrate my cameras to homekit. Coul I use the simple install way about this guide?

**Comment by oznu** [comment]
The quick install script is for Raspbian only. However once you get docker  and docker-compose installed you can follow all the other steps from Step 3 onwards.

https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Raspberry-Pi#3-create-docker-compose-manifest
