### ISSUE TITLE
rpi3 with docker-compose, cant login to gui

### ISSUE THREAD

**Issue by itayraviv** [oznu/docker-homebridge#238]
Hi,
I installed homebridge on raspberry pi 3 running docker and docker-compose, i changed the port to different then 8080 (got something else on it), i see the homebridge GUI but i can't log in (tried admin/admin).

container logs:
.
.
homebridge    | Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
homebridge    |                        
homebridge    |     ┌────────────┐     
homebridge    |     │ 031-45-154 │     
homebridge    |     └────────────┘     
homebridge    |                        
homebridge    | [10/16/2019, 7:59:59 PM] Homebridge is running on port 53167.
homebridge    | [10/16/2019, 8:00:01 PM] [Config] Homebridge Config UI X v4.6.2 is listening on :: port 8085
homebridge    | [10/16/2019, 8:00:02 PM] [homebridge-config-ui-x] SyntaxError: /homebridge/auth.json: Unexpected end of JSON input
homebridge    | [10/16/2019, 8:00:02 PM] [homebridge-config-ui-x] Caught Unhandled Rejection Error :: Details Below
homebridge    | SyntaxError: /homebridge/auth.json: Unexpected end of JSON input
homebridge    |     at JSON.parse (<anonymous>)
homebridge    |     at /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/jsonfile/index.js:33:18
homebridge    |     at /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/graceful-fs/graceful-fs.js:90:16
homebridge    |     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

--------
docker-compose.yml section:

  homebridge:
    image: oznu/homebridge:raspberry-pi
    container_name: homebridge
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8085

homebridge config.json:

{
    "bridge": {
        "name": "Homebridge D413",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXXX,
        "pin": "XXX-XX-XXX"
    },
    "accessories": [],
    "platforms": []

screenshot:
![image](https://user-images.githubusercontent.com/50876062/66955808-d0fe3b80-f06b-11e9-9d32-6ff73e2b7c54.png)

Host OS: Raspbian Buster
Docker Version:  19.03.2

Can you please assist?
p.s: I have home-assistant running (still didn't add homekit to it if it matters).

**Comment by oznu** [comment]
```
[homebridge-config-ui-x] SyntaxError: /homebridge/auth.json: Unexpected end of JSON input
```

Delete that file and restart the container.

**Comment by itayraviv** [comment]
perfect ! it worked...
so just to better understand, when using with a docker (and compose) there is no need to configure HB as a systemd or ANY other setup/options? 
Thanks for the help

**Comment by itayraviv** [comment]
great work ! super-easy !
any idea how i now combine it with home assistant so i can control or view HA switches/sensors in homekit? any guide or procedure?

**Comment by itayraviv** [comment]
yes they have, ill look into it later... 
just to understand, from the gui i found a plugin i want, after installation i need to edit the config.json manually? its not added upon installation of plugin?

**Comment by oznu** [comment]
Correct, unless the plugin author has added a `config.schema.json`. Plugins that do have this automatically have a GUI based configuration screen show up upon installation.

https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI
