### ISSUE TITLE
error homebridge-hue@0.5.31: The engine "node" is incompatible with this module. Expected version "6.11.3".

### ISSUE THREAD

**Issue by kappes** [oznu/docker-homebridge#24]
Getting this error with the latest version. any chance for upgrading node?

**Comment by oznu** [comment]
I updated node a few days ago in #23.

If you pull down the latest version you'll be running Homebridge on Node 8.4.0.

**Comment by oznu** [comment]
Ok, that module is causing the issue, homebridge-hue is **requiring** a specific node version.

They have:

```js
  "engines": {
    "node": "6.11.3"
  }
```

Where as they *should* have:

```js
  "engines": {
    "node": ">=6.11.3"
  }
```

Regardless, I can fix this on my end by telling `yarn` to ignore engines, which has the added benefit of removing that pesky warning about homebridge not being a valid engine.

I'll push up this change shortly.

**Comment by oznu** [comment]
Resolved in https://github.com/oznu/docker-homebridge/commit/53efae064126f5c24b17938524cb0e7f616bbce3.

[homebridge-hue](https://github.com/ebaauw/homebridge-hue) now loads correctly using node 8.4.0.

**Comment by kappes** [comment]
can confirm, but will report this also to the plugin author. thanks alot.
