### ISSUE TITLE
sudo fails with 

### ISSUE THREAD

**Issue by stevehoek** [oznu/docker-homebridge#240]
I run docker-homebridge on my SYNOLOGY.  

One of my plugins is the Ring platform.  I noticed that it queries **api.ring.com** every 2 seconds, which is normal, but I would expect the OS to cache that DNS query.  When asking about it in the Homebridge/Ring project, they suggested I install the '**nscd**' service to cache the DNS queries.

I was using the Alpine version of docker-homebridge, but it does not support '**nscd**', so I switched to debian.

I put the following in my startup.sh
```
apt-get update
apt-get install nscd
sudo service nscd start
```
But it does not work, I get this error:
```
sudo: unable to resolve host Homebridge
sudo: unable to send audit message: Unknown error -1
sudo: pam_open_session: System error
sudo: policy plugin failed session initialization

```

Any ideas what is going on with this?  This goes beyond my limited knowledge of Linux :)

**Comment by oznu** [comment]
Docket containers typically don't run systemd so this command won't work:

```
service nscd start
```

You would need to build a custom container and set this up as a run process manually.

**Comment by stevehoek** [comment]
Can you recommend a good guide for how to go about this?
