### ISSUE TITLE
docker-homebridge crashing Hue bridge

### ISSUE THREAD

**Issue by nathankellenicki** [oznu/docker-homebridge#242]
Hi,

Recently I started using docker-homebridge. It's working fine, however I started noticing a weird behaviour with Philips Hue - every so often my lights would show as Unresponsive in HomeKit, Alexa would complain that she couldn't connect to the lights, and the Hue app would stop connecting to the bridge. I noticed that the Bridge was rebooting/crashing every few minutes.

It's been a few weeks but recently I found this thread on the MeetHue Developer forum describing the exact issue. Quite a few people mentioning using oznu/docker-homebridge, and how not using it stops the bridge from crashing so I tried this.

https://developers.meethue.com/forum/t/hue-bridge-v2-reboots-every-5-minutes/5539/25

Sure enough, stopping removing the container makes the Hue Bridge stable. It no longer crashes every few minutes. It seems this was indeed the cause.

Do you have any idea what would cause this? I love this container, and would hate to stop using it, however it makes the Hue Bridge unusable.

Many thanks!

**Comment by oznu** [comment]
Can you try the `no-avahi` variant of the image and see if that makes a difference?

https://github.com/oznu/docker-homebridge/wiki#image-variants

**Comment by nathankellenicki** [comment]
Thanks for the reply! I actually found the no-avahi variant on Dockerhub and gave it a shot:

```
fc3165d9eb44        oznu/homebridge:no-avahi            "/init"                  5 minutes ago       Up 5 minutes                                                                                                                                                                                                  homebridge
```

Unfortunately the issue still exists. It appears to be exactly every 5 minutes the bridge crashes.

**Comment by oznu** [comment]
Does the issue still occur when running with no plugins and with the UI disabled?

**Comment by nathankellenicki** [comment]
That was a good shout! I don't run with the UI, but I run with four plugins: `homebridge-platform-wemo`, `homebridge-camera-ffmpeg`, `homebridge-http-motion-sensor`, and `homebridge-http-switch`. Some debugging and I think `homebridge-platform-wemo` is the culprit! Running without it causes the Hue Bridge to stay alive longer than five minutes.

I guess I have to debug this further, though I suspect `wemo-client`'s use of `node-ssdp` is the cause here.

Thanks for the help!

**Comment by oznu** [comment]
If you figure it out, please keep post an update for others 😄 . It does seem strange the other unrelated network devices could crash the Hue Hub.

**Comment by nathankellenicki** [comment]
I'm afraid I posted too soon, only testing for a few minutes at a time. Even with only the ffmpeg plugin running, it crashed after about 15 minutes.

Homebridge has been down for about an hour now without a crash. So still not sure what the issue is I'm afraid!

**Comment by nathankellenicki** [comment]
See this issue here for more: https://github.com/ebaauw/homebridge-hue/issues/412

**Comment by nathankellenicki** [comment]
So I played some more with it today. Turns out this seems to be a common problem with running Homebridge in Docker on a host that may also be running Avahi/mDNS. The solution was to put my network interface into promiscuous mode, put the container on a macvlan, and give it it's own dedicated IP address. It appears to be stable after this.

**Comment by oznu** [comment]
@nathankellenicki - glad you got it sorted. Any chance you're able to post instructions for what you did? I may add them to the wiki to help out others who have the same problem.

**Comment by nathankellenicki** [comment]
Sure. So while I understand the concept of macvlans and how they work, I have limited experience and knowledge of them, so bear that in mind with this.

Step 1
---

Firstly, you need to choose two spare IP address'es on your network for the container. One for the container itself, and one for the intermediate network to proxy between your network and the macvlan network. You also need a router which allows you to modify its DHCP ranges, to ensure your router doesn't start handing out those two IP addresses to other clients.

Step 2
---

Find the network interface your host machine uses to connect to your network (`ifconfig`). In my case, it's `enp5s0`. Put this interface into promiscuous mode:

`ifconfig enp5s0 promisc`

Then create the aforementioned proxy network (I've called mine `macvlan-proxy`):

`ip link add macvlan-proxy link enp5s0 type macvlan mode bridge`

And assign one of the two IP addresses you've chosen to the proxy network:

`ip addr add 192.168.50.15/32 dev macvlan-proxy`

Bring the proxy network up:

`ip link set macvlan-proxy up`

Finally, add a route between your containers new IP address and the proxy:

`ip route add 192.168.50.16/32 dev macvlan-proxy`

Step 3
---

You need to create the macvlan network within Docker and add the homebridge container to it. In my case, I use docker-compose, so I add the network (which I've called `homebridge-network`) to the networks section, ensuring I specify the interface, subnet, gateway, and chosen IP address:

```
network:
  homebridge-network:
    driver: macvlan
    driver_opts:
      parent: enp5s0
    ipam:
      config:
        - ip_range: 192.168.50.16/32
          gateway: 192.168.50.1
          subnet: 192.168.50.0/24
```

Finally, remove `network: host` from the container and add the new network:

```
    networks:
      - homebridge-network
```

Step 4
---

Bring it all up as normal: `docker-compose up -d`

Extra
---

Persist the network settings. I haven't done this yet.

**Comment by hessijames79** [comment]
Sorry, for reviving the issue.

@nathankellenicki
Do you have a reference on "Turns out this seems to be a common problem with running Homebridge in Docker on a host that may also be running Avahi/mDNS"? It would help me to see if other issues might be connected and also allow me to consider alternate solutions.

Thanks for the tutorial!

Patrick

**Comment by nathankellenicki** [comment]
Sure, there are numerous reports across the web, some specifically referencing this Docker image. One of the main ones is this thread on the official Hue developer forums (registration required):

https://developers.meethue.com/forum/t/hue-bridge-v2-reboots-every-5-minutes/5539/24

Then there's this thread against the homebridge-hue plugin, again referencing this image:

https://github.com/ebaauw/homebridge-hue/issues/412

This thread on the Ubiquity forums doesn't talk about Docker Homebridge, but references certain mDNS settings on Unifi networking equipment causing the same issue:

https://community.ui.com/questions/Weird-mDNS-issue/e4fe9528-cf5d-49f7-90d9-8c5b7c0dae9b

I found others during my search a few months back too, when I was trying to solve this.

Just to note, since I implemented the macvlan stuff I mentioned a while back, the setup has been rock solid, Docker homebridge included. Big fan of this container and your work. :)

**Comment by nathankellenicki** [comment]
Also this thread on the pfSense forums referencing Avahi as the source of the issues:

https://forum.netgate.com/topic/124533/avahi-breaks-apple-homekit-and-philips-hue

**Comment by oznu** [comment]
Thanks @nathankellenicki 

I hope you guys have reported these issues to [Hue](https://meethue.com/). The Hue Bridge crashing due to something else running on the network is very much a "them" problem that they should solve.

**Comment by nathankellenicki** [comment]
@oznu I personally haven't, but I can see from some Hue threads that some folks provided diagnostics info to Philips/Signify, but nothing has been fixed. In fact, that thread at the top is from January 2018, but the latest post is from 8 hours ago from someone asking why it hasn't been fixed yet, so it seems it's not a high priority for them.

I agree it's a "them" problem that they should fix, however sadly as is usually the case, with the amount of reports out there referencing this container, you might have a image problem with people blaming this container. I'm unsure if a change could be made to this container to resolve the issue, at least for users of this container.

In the meantime, hopefully the macvlan stuff above can help some users. :)

**Comment by hessijames79** [comment]
@nathankellenicki:
> In the meantime, hopefully the macvlan stuff above can help some users. :) I also posted a link to this thread in the Hue forum.

I was a bit hesitant to implement your workaround because of the limitation of macvlans unable to communicate with the host. Finally found an elegant solution moving the main ip address of the host to a macvlan interface.

Looks good so far. Thank you again for your research and the documentation.

Patrick
