### ISSUE TITLE
Multiple Instances Of Homebridge Found Installed

### ISSUE THREAD

**Issue by canoben** [oznu/docker-homebridge#244]
I'm having the problem that all of a sudden Homebridge shows me on my devices an old configuration. I'm using the Docker image on a Synology NAS with the Homebridge GUI app installed on the server for easy configuration.

Checking the logs I found the following and I think it's related to the following message:

```
[10/29/2019, 5:32:29 PM] [Config] Multiple Instances Of Homebridge Found Installed
[10/29/2019, 5:32:29 PM] [Config] /homebridge/node_modules/homebridge
[10/29/2019, 5:32:29 PM] [Config] /usr/local/lib/node_modules/homebridge

```
/homebridge is the NAS directory I mapped in the Docker image. AFAIK, I never installed anything in /usr.

What's going on here?

**Comment by oznu** [comment]
This one needs to be removed:

```
/homebridge/node_modules/homebridge
```

Exec into the container and run:

```
cd /homebridge
npm uninstall homebridge
```

**Comment by canoben** [comment]
My container's name is homebridge. Trying to open a terminal in it results in the following error:

`sudo docker exec -it homebridge /bin/bash
Password: 
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown`

Could I alternatively just delete the offending folder using a NAS prompt?

**Comment by oznu** [comment]
Try this.

```
sudo docker exec -it homebridge sh
```

**Comment by canoben** [comment]
Yeah, that worked. But after restarting the container, I'm still getting the same error.

**Comment by oznu** [comment]
What plugins do you have installed?

**Comment by canoben** [comment]
Config UI, Dummy, Rademacher HomePilot and Synology.

**Comment by oznu** [comment]
`homebridge-rademacher-homepilot` is causing the problem:

https://github.com/bombadiltom/homebridge-rademacher-homepilot/blob/master/package.json#L21

`homebridge` is listed as a dependency when it really shouldn't be - it's not being used.

**Comment by canoben** [comment]
Is there something I can do about it, for example should I simply delete the offending line in package.json?

**Comment by oznu** [comment]
I'd recommend raising an issue with the plugin author. 

The message you're seeing is just a warning, and won't cause issues until you try and do an online update of Homebridge via the UI.

**Comment by canoben** [comment]
Well, I regularly do updates via the UI.
So my problem with the old config being used isn't caused by this? Also, I deleted Homebridge from Homekit, but trying to add it again results in a "accessory already added" error.

**Comment by oznu** [comment]
> So my problem with the old config being used isn't caused by this? 

I wouldn't expect it to be.

> Also, I deleted Homebridge from Homekit, but trying to add it again results in a "accessory already added" error.

You'll need to reset homebridge after doing this to allow it to be paired again. In the UI, on the Status page, click the "reset homebridge" link at the very bottom of the page - this will reset homebridge, but won't remove any plugin config you have setup.

**Comment by canoben** [comment]
Oh, didn't know about that. It's working now!

Thanks a lot for your help and your work on the container.
