### ISSUE TITLE
Downgrade node version to 10.16.3

### ISSUE THREAD

**Issue by MaurizioB84** [oznu/docker-homebridge#246]
**Describe Your Problem:**

I found an issues with the restriction introduced by Node 12, TLS 1.0 is not enabled and I cannot connect with my devices (AC).

Rasberry PI on docker-compose
How I can downgrade to node 10.16.3?

many thanks

**Comment by oznu** [comment]
Hi @MaurizioB84,

I tag an archive release before doing major updates to Node.js so users can downgrade if required.

See https://github.com/oznu/docker-homebridge/releases/tag/2.0.0

**Comment by MaurizioB84** [comment]
thanks @oznu ! now works again!

can you provide a version of container with updated Homebridge Config UI X on the old version of node.js?

**Comment by oznu** [comment]
You can update the UI inside the container once setup.

**Comment by oznu** [comment]
Hi @MaurizioB84,

Another option for you would be to enable support for TLS v1.0 in Node.js 12. You can do this by starting the docker containing with this environment variable:

```
NODE_OPTIONS="--tls-min-v1.0"
```

For example:

```
docker run -e NODE_OPTIONS="--tls-min-v1.0" oznu/homebridge
```

***Note:** This is not something this docker container is doing, this is simply using an option Node.js provides that allows you to pass runtime arguments using environment variables. See [NODE_OPTIONS](https://nodejs.org/api/cli.html#cli_node_options_options) for more details.*

***Warning:** If `NODE_OPTIONS` contains any invalid configuration Homebridge and the UI will not start.*

**Comment by MaurizioB84** [comment]
thanks for the suggestion, but how I can use with docker-compose file?
`  homebridge:
    image: oznu/homebridge:2.0.0
    container_name: homebridgeTLS
    restart: always
    network_mode: host
    depends_on:
      - mosquitto
    ports:
      # console
      - 4000:4000
      # Expose public port
      - 51826:51826
      - 6000:6000
      # Avahi
      - 5353:5353/udp
    volumes:
      - ./homebridge/config/:/homebridge
      - ./ssl:/ssl
      # - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Paris
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=4000`
