### ISSUE TITLE
Update docker

### ISSUE THREAD

**Issue by raphaeldavid** [oznu/docker-homebridge#248]
**Describe Your Problem:**
I received an update of the docker today (for Unraid server)
After the update, all my configuration and plugins disappeared
but I made a backup of my configuration...
I reinstall all my plugins and copy my config.json in my config tab.
Why the name and username change ? I need to reinstall everything in the iOS app.

Thank,

**Environment:**

* **Host Operating System**: 
Unraid 6.7.2
* **Docker Version**: 
Lastest
* **Image Tag / Type**: 
Lastest

**Comment by oznu** [comment]
Hi @raphaeldavid,

It sounds like you have not configured your container to mount the `/homebridge` directory to a local volume. Once you do this your Homebridge config and plugins will persist.

**Comment by raphaeldavid** [comment]
In my docker configuration, I already add the variable "/homebridge" with the
value : /mnt/user/appdata/homebridge/

**Comment by oznu** [comment]
Did you add that as an environment variable or a volume mount?

Something like this:

![image](https://user-images.githubusercontent.com/3979615/69287679-3638e400-0c4b-11ea-95a4-33efe0ba56fe.png)

**Comment by raphaeldavid** [comment]
Everything like this post : https://forums.unraid.net/topic/41684-request-homebridge/page/6/
Like a variable
or like a path like this ?
https://ipsassets.unraid.net/uploads/monthly_2018_11/C39BA21E-9ED4-469F-8FDB-BFD7D963975F.thumb.jpeg.eb8c240a83c9c2b5e0cc6303d34b9c80.jpeg

**Comment by oznu** [comment]
After creating the container, does the local `/mnt/user/appdata/homebridge/` or `/mnt/user/appdata/homebridge7)` (as pictured) directory contain the same config that the UI is showing?

**Comment by oznu** [comment]
Network Type should be `Host`.

**Comment by raphaeldavid** [comment]
That is mine
![Capture d’écran, le 2019-11-20 à 18 56 23](https://user-images.githubusercontent.com/10728443/69288412-7d7d9100-0bc7-11ea-99bd-2952eb36f55b.jpg)

**Comment by raphaeldavid** [comment]
If I change /mnt/user/appdata/homebridge/ for a path, nothing works

**Comment by raphaeldavid** [comment]
At the base, when I install the docker, the directory /mnt/user/appdata/homebridge/ is not created.

**Comment by raphaeldavid** [comment]
I found it, you need to configure the docker like this...
Icon URL : https://dashboard.snapcraft.io/site_media/appmedia/2018/10/Logo2x.png
WebUI : http://[IP]:[PORT:8080]
Extra Parameters : -e HOMEBRIDGE_CONFIG_UI=1
Network Type : Host
And add a new Path
- Container path : /homebridge
- Host path : /mnt/user/appdata/homebridge/
