### ISSUE TITLE
execvp (3) failed.: No such file or directory

### ISSUE THREAD

**Issue by martijnverheij** [oznu/docker-homebridge#249]
Hello,

I have my homebridge running on a raspberry pi in a docker container. 
It works perfect and i can control everything with Siri.
Only when i tried to update my plugins i get this error. 
It happens with every plugin i want to update via Config UI X.

Versions:
Homebridge: 0.4.50
Config UI X: 4.6.1

Installed plugins:
- Config UI X
- Nefit Easy
- Edomoticz
- Hue
- Weather
- Samsung Tizen

Homebridge is listening on port 51826
Console on port 80

**Comment by oznu** [comment]
Hi @martijnverheij,

I'm going to need more information to assist you on this one.

https://github.com/oznu/docker-homebridge/blob/master/.github/ISSUE_TEMPLATE/support-request.md

**Comment by martijnverheij** [comment]
Thanks for your quick response. And i fixed also by myself.
Only thing i did was an docker upgrade. So i close this issue
