### ISSUE TITLE
Feature Suggestion: Allow custom plugins

### ISSUE THREAD

**Issue by mneumark** [oznu/docker-homebridge#251]
**Describe Your Problem:**
I forked, tweaked, and published a plugin to npm. I tried looking for it in the interface but it did not show up. It would be nice if there was some way to say "here is the npm package name. I understand you can't find it, trust me, this is legit".

**Environment:**

* **Host Operating System**: Unraid 6.7.2
* **Docker Version**: 18.09.6
* **Image Tag / Type**: latest

**Comment by oznu** [comment]
What's the plugin? The search will only return plugins that match the same pattern Homebridge uses to load plugins.

**Comment by mneumark** [comment]
Actually just tried again and it worked fine. Apparently I was just impatient.
