### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by huntson** [oznu/docker-homebridge#253]
After following your installation to the letter and attempting to start the service, everything appears ok however nothing appears on an iPhone to add.  I looked in the logs and I see a lot of this:

Error: EACCES: permission denied, mkdir '/homebridge/persist'

Perhaps it's an issue?  Note that I've tried a bunch of different permission changes to see if it was affected however no dice.  Also, no plugins installed....yet

**Comment by oznu** [comment]
Hi @huntson,

Can you describe your setup? The issue template has the details I need to help you out.

**Comment by huntson** [comment]
I'm not sure where the issue template is however I've attached some additional config info:

{
    "bridge": {
        "name": "Homebridge 9AB6",
        "username": "0E:2F:AC:96:9A:B6",
        "port": 53431,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": []
}

**Comment by oznu** [comment]
https://github.com/oznu/docker-homebridge/issues/new?assignees=&labels=question&template=support-request.md&title=



**Describe Your Problem:**


**Logs:**


```
Show the Docker container logs here
```

**Docker Start Command:**



```
docker run --net=host ...
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**


**Environment:**

* **Host Operating System**: 
* **Docker Version**: 
* **Image Tag / Type**:

**Comment by huntson** [comment]
After following your installation to the letter and attempting to start the service, everything appears ok however nothing appears on an iPhone to add. I looked in the logs and I see a lot of this:

Error: EACCES: permission denied, mkdir '/homebridge/persist'

Perhaps it's an issue? Note that I've tried a bunch of different permission changes to see if it was affected however no dice. Also, no plugins installed....yet

**Logs:** Attached in zip
[logs.zip](https://github.com/oznu/docker-homebridge/files/3935202/logs.zip)

**Docker start command:** Where would I find this?  I'm just using the start button within the docker app

**Config:**
{
    "bridge": {
        "name": "Homebridge 9AB6",
        "username": "0E:2F:AC:96:9A:B6",
        "port": 53431,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": []
}


**Environment:** 
Synology NAS RS812RP+
DSM 6.2.2 Update 4

Docker 18.09.0-0506

**Comment by oznu** [comment]
What volume have you mapped to `/homebridge`?

On a Synology NAS you can't map a share directly, you need to map a folder within a share.

For example, you will see this error if you try and mount `/volume1/docker`; but it will work if you mount `/volume1/docker/homebridge`.

**Comment by oznu** [comment]
You might also be interested in https://github.com/oznu/homebridge-syno-spk#how-to-install which will setup the container with all the correct settings for you.

**Comment by huntson** [comment]
> What volume have you mapped to `/homebridge`?
> 
> On a Synology NAS you can't map a share directly, you need to map a folder within a share.
> 
> For example, you will see this error if you try and mount `/volume1/docker`; but it will work if you mount `/volume1/docker/homebridge`.

I see.  This wasn't clear from the install instructions.  Using the package with the container was the best choice here and that's what I did.
