### ISSUE TITLE
homebridge-dht: Error: Cannot find module '../build/Release/node_dht_sensor'

### ISSUE THREAD

**Issue by yz88** [oznu/docker-homebridge#256]
Installed homebridge-dht plugin via Hombridge UI with no problems. But Homebridge does not start after installation

Plugin: https://github.com/NorthernMan54/homebridge-dht

homebridge_1  | [12/25/2019, 8:35:09 PM] [Config] Changes to config.json saved.
homebridge_1  | -U /homebridge -P /homebridge/node_modules -C
homebridge_1  | [12/25/2019, 8:35:13 PM] [Config] Homebridge restart request received
homebridge_1  | [12/25/2019, 8:35:13 PM] [Config] Executing restart command: killall -9 homebridge && killall -9 homebridge-config-ui-x
homebridge_1  | Killed
homebridge_1  | Killed
homebridge_1  | -U /homebridge -P /homebridge/node_modules -C
homebridge_1  | [12/25/2019, 8:35:39 PM] Loaded config.json with 2 accessories and 0 platforms.
homebridge_1  | [12/25/2019, 8:35:39 PM] ---
homebridge_1  | [12/25/2019, 8:35:40 PM] Loaded plugin: homebridge-cmdswitch2
homebridge_1  | [12/25/2019, 8:35:40 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
homebridge_1  | [12/25/2019, 8:35:40 PM] ---
homebridge_1  | [12/25/2019, 8:35:40 PM] ====================
homebridge_1  | [12/25/2019, 8:35:40 PM] ERROR LOADING PLUGIN homebridge-dht:
homebridge_1  | [12/25/2019, 8:35:40 PM] Error: Cannot find module '../build/Release/node_dht_sensor'
homebridge_1  | Require stack:
homebridge_1  | - /homebridge/node_modules/homebridge-dht/node_modules/node-dht-sensor/lib/index.js
homebridge_1  | - /homebridge/node_modules/homebridge-dht/index.js
homebridge_1  | - /usr/local/lib/node_modules/homebridge/lib/plugin.js
homebridge_1  | - /usr/local/lib/node_modules/homebridge/lib/server.js
homebridge_1  | - /usr/local/lib/node_modules/homebridge/lib/cli.js
homebridge_1  | - /usr/local/lib/node_modules/homebridge/bin/homebridge
homebridge_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
homebridge_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
homebridge_1  |     at require (internal/modules/cjs/helpers.js:74:18)
homebridge_1  |     at Object.<anonymous> (/homebridge/node_modules/homebridge-dht/node_modules/node-dht-sensor/lib/index.js:1:14)
homebridge_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
homebridge_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
homebridge_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
homebridge_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
homebridge_1  | [12/25/2019, 8:35:40 PM] ====================
homebridge_1  | [12/25/2019, 8:35:40 PM] Loaded plugin: homebridge-dummy
homebridge_1  | [12/25/2019, 8:35:40 PM] Registering accessory 'homebridge-dummy.DummySwitch'
homebridge_1  | [12/25/2019, 8:35:40 PM] ---
homebridge_1  | [12/25/2019, 8:35:41 PM] Loaded plugin: homebridge-config-ui-x
homebridge_1  | [12/25/2019, 8:35:41 PM] Registering platform 'homebridge-config-ui-x.config'
homebridge_1  | [12/25/2019, 8:35:41 PM] ---
homebridge_1  | [12/25/2019, 8:35:41 PM] Loading 0 platforms...
homebridge_1  | [12/25/2019, 8:35:41 PM] Loading 2 accessories...
homebridge_1  | [12/25/2019, 8:35:41 PM] Error: The requested accessory 'Dht' was not registered by any plugin.
homebridge_1  |     at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
homebridge_1  |     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
homebridge_1  |     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
homebridge_1  |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
homebridge_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
homebridge_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
homebridge_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
homebridge_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
homebridge_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
homebridge_1  | [12/25/2019, 8:35:41 PM] Got SIGTERM, shutting down Homebridge...
homebridge_1  | -U /homebridge -P /homebridge/node_modules -C
homebridge_1  | [12/25/2019, 8:36:11 PM] Loaded config.json with 2 accessories and 0 platforms.
homebridge_1  | [12/25/2019, 8:36:11 PM] ---
homebridge_1  | [12/25/2019, 8:36:12 PM] Loaded plugin: homebridge-cmdswitch2
homebridge_1  | [12/25/2019, 8:36:12 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
homebridge_1  | [12/25/2019, 8:36:12 PM] ---
homebridge_1  | [12/25/2019, 8:36:12 PM] ====================
homebridge_1  | [12/25/2019, 8:36:13 PM] ERROR LOADING PLUGIN homebridge-dht:
homebridge_1  | [12/25/2019, 8:36:13 PM] Error: Cannot find module '../build/Release/node_dht_sensor'
homebridge_1  | Require stack:
homebridge_1  | - /homebridge/node_modules/homebridge-dht/node_modules/node-dht-sensor/lib/index.js
homebridge_1  | - /homebridge/node_modules/homebridge-dht/index.js
homebridge_1  | - /usr/local/lib/node_modules/homebridge/lib/plugin.js
homebridge_1  | - /usr/local/lib/node_modules/homebridge/lib/server.js
homebridge_1  | - /usr/local/lib/node_modules/homebridge/lib/cli.js
homebridge_1  | - /usr/local/lib/node_modules/homebridge/bin/homebridge
homebridge_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
homebridge_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
homebridge_1  |     at require (internal/modules/cjs/helpers.js:74:18)
homebridge_1  |     at Object.<anonymous> (/homebridge/node_modules/homebridge-dht/node_modules/node-dht-sensor/lib/index.js:1:14)
homebridge_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
homebridge_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
homebridge_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
homebridge_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
homebridge_1  | [12/25/2019, 8:36:13 PM] ====================
homebridge_1  | [12/25/2019, 8:36:13 PM] Loaded plugin: homebridge-dummy
homebridge_1  | [12/25/2019, 8:36:13 PM] Registering accessory 'homebridge-dummy.DummySwitch'
homebridge_1  | [12/25/2019, 8:36:13 PM] ---
homebridge_1  | [12/25/2019, 8:36:12 PM] [Config] Homebridge Config UI X v4.6.7 is listening on :: port 8080
homebridge_1  | [12/25/2019, 8:36:13 PM] Loaded plugin: homebridge-config-ui-x
homebridge_1  | [12/25/2019, 8:36:13 PM] Registering platform 'homebridge-config-ui-x.config'
homebridge_1  | [12/25/2019, 8:36:13 PM] ---
homebridge_1  | [12/25/2019, 8:36:13 PM] Loading 0 platforms...
homebridge_1  | [12/25/2019, 8:36:13 PM] Loading 2 accessories...
homebridge_1  | [12/25/2019, 8:36:13 PM] Error: The requested accessory 'Dht' was not registered by any plugin.
homebridge_1  |     at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
homebridge_1  |     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
homebridge_1  |     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
homebridge_1  |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
homebridge_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
homebridge_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
homebridge_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
homebridge_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
homebridge_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
homebridge_1  | [12/25/2019, 8:36:14 PM] Got SIGTERM, shutting down Homebridge...
homebridge_1  | -U /homebridge -P /homebridge/node_modules -C
homebridge_1  | [12/25/2019, 8:36:33 PM] Loaded config.json with 2 accessories and 0 platforms.
homebridge_1  | [12/25/2019, 8:36:33 PM] ---
homebridge_1  | [12/25/2019, 8:36:34 PM] Loaded plugin: homebridge-cmdswitch2
homebridge_1  | [12/25/2019, 8:36:34 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
homebridge_1  | [12/25/2019, 8:36:34 PM] ---
homebridge_1  | [12/25/2019, 8:36:34 PM] ====================
homebridge_1  | [12/25/2019, 8:36:34 PM] ERROR LOADING PLUGIN homebridge-dht:
homebridge_1  | [12/25/2019, 8:36:34 PM] Error: Cannot find module '../build/Release/node_dht_sensor'
homebridge_1  | Require stack:
homebridge_1  | - /homebridge/node_modules/homebridge-dht/node_modules/node-dht-sensor/lib/index.js
homebridge_1  | - /homebridge/node_modules/homebridge-dht/index.js
homebridge_1  | - /usr/local/lib/node_modules/homebridge/lib/plugin.js
homebridge_1  | - /usr/local/lib/node_modules/homebridge/lib/server.js
homebridge_1  | - /usr/local/lib/node_modules/homebridge/lib/cli.js
homebridge_1  | - /usr/local/lib/node_modules/homebridge/bin/homebridge
homebridge_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
homebridge_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
homebridge_1  |     at require (internal/modules/cjs/helpers.js:74:18)
homebridge_1  |     at Object.<anonymous> (/homebridge/node_modules/homebridge-dht/node_modules/node-dht-sensor/lib/index.js:1:14)
homebridge_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
homebridge_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
homebridge_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
homebridge_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
homebridge_1  | [12/25/2019, 8:36:34 PM] ====================
homebridge_1  | [12/25/2019, 8:36:34 PM] Loaded plugin: homebridge-dummy
homebridge_1  | [12/25/2019, 8:36:34 PM] Registering accessory 'homebridge-dummy.DummySwitch'
homebridge_1  | [12/25/2019, 8:36:34 PM] ---
homebridge_1  | [12/25/2019, 8:36:34 PM] Loaded plugin: homebridge-config-ui-x
homebridge_1  | [12/25/2019, 8:36:34 PM] Registering platform 'homebridge-config-ui-x.config'
homebridge_1  | [12/25/2019, 8:36:34 PM] ---
homebridge_1  | [12/25/2019, 8:36:34 PM] Loading 0 platforms...
homebridge_1  | [12/25/2019, 8:36:34 PM] Loading 2 accessories...
homebridge_1  | [12/25/2019, 8:36:34 PM] Error: The requested accessory 'Dht' was not registered by any plugin.
homebridge_1  |     at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
homebridge_1  |     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
homebridge_1  |     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
homebridge_1  |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
homebridge_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
homebridge_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
homebridge_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
homebridge_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
homebridge_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
homebridge_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
homebridge_1  | [12/25/2019, 8:36:34 PM] Got SIGTERM, shutting down Homebridge...

Docker compose file:
root@test-pi:~/homebridge# cat docker-compose.yml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=0
      - PUID=0
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
root@test-pi:~/homebridge#

root@test-pi:~/homebridge# cat config/config.json
{
    "bridge": {
        "name": "INTE",
        "username": "0E:88:CE:A7:6C:A3",
        "port": 51309,
        "pin": "031-45-999"
    },
    "accessories": [
        {
            "_comment": "Dht uses BCM_GPIO_PIN_NUMBER",
            "accessory": "Dht",
            "name": "/usr/local/bin/cputemp",
            "service": "Temperature"
        },
        {
            "accessory": "Dht",
            "name": "dht22_1",
            "name_temperature": "Temp Aussen",
            "name_humidity": "Humi Aussen",
            "service": "dht22",
            "gpio": "10",
            "refresh": "300"
        }
    ],
    "platforms": []
}
root@test-pi:~/homebridge#

**Comment by oznu** [comment]
Hi @yz88,

I generally don't recommend using GPIO plugins with this Docker container as it's pretty complicated to pass through the correct device and get the required modules inside the container.

I'd recommend setting up Homebridge using systemd instead: 

https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Raspbian

**Comment by yz88** [comment]
This is an honest statement that will certainly save me a lot of time. I will be running homebridge right on top of Raspberry Pi.
