### ISSUE TITLE
Changing onValue or CloseValue?

### ISSUE THREAD

**Issue by mbaastrup** [oznu/docker-homebridge#257]
I use the oznu bridge for HomeSeer.

My window opener reacts to 
0: Close
1-98: Percent open
99: Open

Current values sent are
0: Close
100: Open

How can I change the parameters sent for a device class like Window?

Best,

Mbaastrup

**Comment by oznu** [comment]
Where are you seeing this? Was this issue intended for this project (homebridge docker image)?

**Comment by mbaastrup** [comment]
When i have the bridge up and running, JSON checked, everything else working, and upon open or close a Window I can see in the log in HomeSeer that the received values are 0 and 100 - I would like it to send 0 and 99 as I can only close the window.
I am using homebridge-homeseer-plugin-2018 plugin - is this where I should be looking for these type of default values?

**Comment by oznu** [comment]
Hi @mbaastrup,

The plugin, homebridge-homeseer-plugin-2018, would be handling this. The author of that one might be able to help.
