### ISSUE TITLE
Homebridge Synology on docker does not support HomeMatic 

### ISSUE THREAD

**Issue by BerkTam** [oznu/docker-homebridge#259]
I have installed Homebridge as shown in this github how-to.

Only installed homebridge-homematic plugin and have been also able to 
add the homebridge to my iPad which worked fine. 

But the plugin does not show any state of the HomeMatic devices. 

Any idea?

**Comment by oznu** [comment]
Hi @BerkTam,

You'd be best off asking the plugin developer here: https://github.com/thkl/homebridge-homematic
