### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by boojew** [oznu/docker-homebridge#26]
Hey - sorry, this may be more of a homebridge question, but I am trying to troubleshoot issues using Homebridge and I cant find the logs as stated in the homebridge docs (.log and .err). I know I can get some logs from docker and the containers folder, but is that all of them or is there additional logging that can be enabled? Thanks

**Comment by oznu** [comment]
All the Homebridge logs are redirected to the docker container stdout.

You can enabled more verbose logging by setting `DEBUG=*` as an environment variable, for example:

```
docker run --net=host -e "DEBUG=*" oznu/homebridge
```

**Comment by boojew** [comment]
Thanks!
