### ISSUE TITLE
Last web UI update crash HomeBridge 

### ISSUE THREAD

**Issue by elkorleone** [oznu/docker-homebridge#262]
I just update the plugin vía web and server dont restart anymore. What happen??

**Comment by elkorleone** [comment]
Log:

 s6-applyuidgid: fatal: unable to exec homebridge-config-ui-x: Exec format error

**Comment by oznu** [comment]
Hi @elkorleone,

Can you please raise a new issue and fill in the issue template so I can help you out with this issue. Without this information I can only guess what the problem might be.

https://github.com/oznu/docker-homebridge/issues/new?assignees=&labels=question&template=support-request.md&title=
