### ISSUE TITLE
Multiple Instances Of Homebridge Found Installed

### ISSUE THREAD

**Issue by scooter133** [oznu/docker-homebridge#263]
I too am seeing this issue, though reading though the other replies to uninstall Homebridge from the foillowing:

> Remove this one /homebridge/node_modules/homebridge.
> 
> Do so by running this in the container:
> 
> npm uninstall homebridge

`[1/16/2020, 3:43:30 AM] [Config] Multiple Instances Of Homebridge Found Installed
[1/16/2020, 3:43:30 AM] [Config] /homebridge/node_modules/homebridge
[1/16/2020, 3:43:30 AM] [Config] /usr/local/lib/node_modules/homebridge `

My issue is that if I modify the configuration, it modifies the files in  /homebridge/node_modules/homebridge, so Im hesitant to delete/uninstall that one?

Thanks!

**Comment by oznu** [comment]
`/homebridge/node_modules/homebridge ` should be removed.

Your config is stored in `/homebridge`.

**Comment by scooter133** [comment]
Thank you for your reply, 
When I run the uninstall command, its still there, even after a reboot. 

Here is the output of the command. 

Thank you!
```
/homebridge # cd node_modules/homebridge
/homebridge/node_modules/homebridge # npm uninstall homebridge
added 54 packages from 36 contributors and audited 79 packages in 6.739s
found 0 vulnerabilities

/homebridge/node_modules/homebridge # ls -la
total 100
drwxr-xr-x   7 abc  abc   4096 Jan 16 17:28 .
drwxr-xr-x 185 abc  abc   4096 Jan 10 00:10 ..
drwxr-xr-x   2 abc  abc   4096 Jan  8 15:51 .github
-rw-r--r--   1 abc  abc     14 Oct 26  1985 CNAME
-rw-r--r--   1 abc  abc  10172 Oct 26  1985 LICENSE
-rw-r--r--   1 abc  abc  13539 Oct 26  1985 README.md
drwxr-xr-x   2 abc  abc   4096 Jan  8 15:51 bin
-rw-r--r--   1 abc  abc    721 Oct 26  1985 config-sample.json
-rw-r--r--   1 abc  abc  12462 Oct 26  1985 index.html
drwxr-xr-x   3 abc  abc   4096 Jan  8 15:51 lib
drwxr-xr-x  55 root root  4096 Jan 16 17:28 node_modules
-rw-r--r--   1 abc  abc  15481 Jan 16 17:25 package-lock.json
-rw-r--r--   1 abc  abc   1673 Jan  8 15:51 package.json
drwxr-xr-x   6 abc  abc   4096 Jan  8 15:51 website
/homebridge/node_modules/homebridge # 
```

**Comment by TheChallinor** [comment]
How can I remove this as PI says its protected and I cannot delete?

**Comment by mikesalz** [comment]
Same problem here.  When I remove it, it comes back.

**Comment by oznu** [comment]
What is the contents of the `package.json` file?

**Comment by mikesalz** [comment]
Content below.  I believe it comes back only when I restart the docker container.  If I restart from within the UI it is not recreated.
```
{
  "_args": [
    [
      "homebridge@0.4.50",
      "."
    ]
  ],
  "_from": "homebridge@0.4.50",
  "_id": "homebridge@0.4.50",
  "_inBundle": false,
  "_integrity": "sha512-V88ME6RLtSGcofXl77KAjlWlmC5O5bRY4BcyBbMjUkGYRdSUcPQUkEsFlGdchpxKoVqyoibHu/mQgN5dQADx7A==",
  "_location": "/homebridge",
  "_phantomChildren": {
    "q": "1.1.2"
  },
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "homebridge@0.4.50",
    "name": "homebridge",
    "escapedName": "homebridge",
    "rawSpec": "0.4.50",
    "saveSpec": null,
    "fetchSpec": "0.4.50"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/homebridge/-/homebridge-0.4.50.tgz",
  "_spec": "0.4.50",
  "_where": ".",
  "author": {
    "name": "Nick Farina"
  },
  "bin": {
    "homebridge": "bin/homebridge"
  },
  "bugs": {
    "url": "http://github.com/nfarina/homebridge/issues"
  },
  "dependencies": {
    "chalk": "^1.1.1",
    "commander": "2.8.1",
    "hap-nodejs": "0.4.51",
    "node-persist": "^0.0.8",
    "qrcode-terminal": "^0.11.0",
    "semver": "5.0.3"
  },
  "description": "HomeKit support for the impatient",
  "engines": {
    "node": ">=4.3.2"
  },
  "homepage": "https://github.com/nfarina/homebridge#readme",
  "license": "ISC",
  "main": "lib/api.js",
  "name": "homebridge",
  "preferGlobal": true,
  "repository": {
    "type": "git",
    "url": "git://github.com/nfarina/homebridge.git"
  },
  "scripts": {
    "dev": "DEBUG=* ./bin/homebridge -D -P example-plugins/ || true"
  },
  "version": "0.4.50"
}

```

**Comment by mikesalz** [comment]
The above is the content of package.json in the \homebridge\node-modules\homebridge. (The second Homebridge instance).  Here is the content of package.json from the parent homebridge folder:

`{
  "dependencies": {
    "homebridge": "^0.4.50",
    "homebridge-delay-switch": "^2.1.0",
    "homebridge-dummy": "^0.4.1",
    "homebridge-harmony": "^1.2.5",
    "homebridge-node-alarm-dot-com": "^1.4.1",
    "homebridge-ring": "^6.1.1"
  }
}
`

**Comment by oznu** [comment]
Remove the `homebridge` dep from `/homebridge/package.json` file; delete `homebridge` from the `node_modules` then restart the container.

**Comment by mikesalz** [comment]
That did the trick!  Thank you @oznu !
