### ISSUE TITLE
How do I restart homebridge service from shell?

### ISSUE THREAD

**Issue by AlfaJackal** [oznu/docker-homebridge#264]
How exactly do I only restart the homebridge service? On my pi I did it via `systemctl restart (stop/start) homebridge`. After that I could also monitor the log via `journalctl -f -au homebridge`.

How can I do that within this docker container on my Synology DSM?

**Comment by oznu** [comment]
Restart the Docker container.

```
docker restart homebridge
```

Replace homebridge with the name of your container. Run `docker ps` to find it.
