### ISSUE TITLE
Noble dependencies and  homebridge-mi-hygrothermograph error

### ISSUE THREAD

**Issue by Vannixxo** [oznu/docker-homebridge#267]
I'm trying to install hannseman/homebridge-mi-hygrothermograph that uses noble without success, anyone succeeded in this?

First, I'm unable to install the noble prerequisites:

sudo apk add bluetooth bluez libbluetooth-dev libudev-dev
(the original command used apt-get but I used apk add as per alpine)

ERROR: unsatisfiable constraints:
bluetooth (missing):
required by: world[bluetooth]
libbluetooth-dev (missing):
required by: world[libbluetooth-dev]
libudev-dev (missing):
required by: world[libudev-dev]

so the only pkg found and installed is "bluez"

I also get numerous errors while installing homebridge-mi-hygrothermograph through the ui, but I can't find homebridge.err in my container

**Comment by RaymondMouthaan** [comment]
The packages you try to install probably have slightly different names in the Alpine package repo. Also try: 

'''
sudo apk add --no-cache <list-of-packages-to-install> 
'''
