### ISSUE TITLE
how update node and npm modules on raspberry ?

### ISSUE THREAD

**Issue by lucyan90** [oznu/docker-homebridge#268]
**Describe Your Problem:**

**Logs:**

```
Show the Docker container logs here
```

**Docker Start Command:**

```
docker run --net=host ...
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Host Operating System**: 
* **Docker Version**: 
* **Image Tag / Type**:

**Comment by oznu** [comment]
Hi @lucyan90,

Please see https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Raspberry-Pi#updating-homebridge--nodejs
