### ISSUE TITLE
Install failure - rPi Zero W

### ISSUE THREAD

**Issue by JangoBritt** [oznu/docker-homebridge#27]
Getting a failure while installing on brand new Raspberry Pi Zero W, running Raspbian Stretch Light

Command was `sudo apt-get update && sudo apt-get install docker-ce`

`invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: core-dump) since Sat 2017-09-23 18:55:21 UTC; 182ms ago
     Docs: https://docs.docker.com
  Process: 16506 ExecStart=/usr/bin/dockerd -H fd:// (code=dumped, signal=SEGV)
 Main PID: 16506 (code=dumped, signal=SEGV)
      CPU: 44ms

Sep 23 18:55:21 homebridge systemd[1]: Failed to start Docker Application C…ine.
Sep 23 18:55:21 homebridge systemd[1]: docker.service: Unit entered failed …ate.
Sep 23 18:55:21 homebridge systemd[1]: docker.service: Failed with result '…mp'.
Sep 23 18:55:22 homebridge systemd[1]: docker.service: Service hold-off tim…art.
Hint: Some lines were ellipsized, use -l to show in full.
dpkg: error processing package docker-ce (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Processing triggers for systemd (232-25+deb9u1) ...
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

Any help would be greatly appreciated.

**Comment by oznu** [comment]
Thanks for raising this issue. I am able to replicate this on the latest version of Raspbian Stretch Light.

According to https://docs.docker.com/engine/installation/linux/docker-ce/debian/ it looks like the Docker repository no longer supports Raspbian, despite it working a month ago.

```
For Raspbian, installing using the repository is not yet supported. 
You must instead use the convenience script.
```

To fix your pi you'll need to uninstall docker-ce:

```
sudo apt-get purge docker-ce
```

Then run the official Docker [convenience script](https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-convenience-script):

```
curl -fsSL get.docker.com | sudo sh
```

I have updated the [install guide wiki](https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Raspberry-Pi) to reflect these changes.

**Comment by jasmas** [comment]
Was the install guide wiki updated back to adding the repo? This appears to be a problem again after the latest update to raspian and docker's pages are once again saying to use the script. I've tried purging but haven't gotten it to work yet. Suspect I need to clean out some repos..
