### ISSUE TITLE
adding openzwave to container image.

### ISSUE THREAD

**Issue by xarbit** [oznu/docker-homebridge#270]
I created a clone of your docker-homebridge repository and built it with open-zwave support... I was wondering if this is something that could actually be added upstream? 
If so, let me know and I'll open a merge-request once done. 

https://github.com/jscurtu/docker-homebridge/tree/add-openZWave

**Comment by oznu** [comment]
Hi @xarbit, 

Nice work, but I prefer for this is something users can add to their `startup.sh` script instead so it does not bloat the container for everyone who may not use this feature.
