### ISSUE TITLE
docker-ce has no installation candidate - installing on raspbian buster

### ISSUE THREAD

**Issue by TootLoose** [oznu/docker-homebridge#276]
Here is a copy/paste of the terminal window when I tried to install using the quick install guide:

pi@raspberry:~ $ ./get-homebridge.sh
[oznu/homebridge installer] Installing on Debian GNU/Linux 10 (buster)...
[oznu/homebridge installer] Installing Docker...
# Executing docker install script, commit: f45d7c11389849ff46a6b4d94e0dd1ffebca32c1
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/debian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=i386] https://download.docker.com/linux/debian buster stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
E: Package 'docker-ce' has no installation candidate

**Comment by oznu** [comment]
Are you sure your running this an offical Raspbian build?

Your logs say:

```
[oznu/homebridge installer] Installing on Debian GNU/Linux 10 (buster)...
```

Where as on Raspbian this should be:

```
[oznu/homebridge installer] Installing on Raspbian GNU/Linux 10 (buster)...
```

Can you post the output of this command?

```
cat /etc/os-release
```

**Comment by NiiWiiCamo** [comment]
I have not tried installing Docker from standard Raspbian Repos in a while, since Docker themselves suggest that you should use the install script: 
[https://docs.docker.com/install/linux/docker-ce/debian/#install-using-the-repository](url)
This might not be the most current way to do it (yay Docker documentation), but it woll work.

**Comment by oznu** [comment]
The quick setup script uses the install script provided by Docker:

https://github.com/oznu/docker-homebridge/blob/master/raspbian-installer.sh#L32

**Comment by oznu** [comment]
Tested this on the latest Raspbian build and it works as expected.
