### ISSUE TITLE
Auto-Update Option for plugins

### ISSUE THREAD

**Issue by buarle** [oznu/docker-homebridge#278]
Hi,

Would it be possible to create an option (ENV variable for docker-compose) to enable automatical  updates for all installed plugins?
Something like watchtower does for the docker images would be an great feature!!

Thanks a lot for this awesome work!
Buarle

**Comment by elkorleone** [comment]
+1

At least a warning by other way like smtp server

**Comment by ceraz68** [comment]
Linked to this I'd be interested in disabling auto-updates for personal plugins, so selective auto-updates would be great.

For example, config-ui tries to look for updates on NPM for my locally developed plugins. Setting private in the plugin package.json had no effect.

[Config] [homebridge-sma-monitor] Failed to check registry.npmjs.org for updates: Request failed with status code 404

Cheers

**Comment by oznu** [comment]
> For example, config-ui tries to look for updates on NPM for my locally developed plugins. Setting private in the plugin package.json had no effect.

I'll fix this in the next release of the UI.

**Comment by ceraz68** [comment]
I tried the update with private set to true in the package.json. Tried with one and then the rest  ...  works great ... thanks :-)

**Comment by mikesalz** [comment]
I noticed this thread was closed, but I'm not sure if the original request was ever addressed.  I would love it if Homebridge could automatically update itself!

**Comment by seidnerj** [comment]
Check this out:
https://github.com/Sunoo/homebridge-plugin-update-check

**Comment by mikesalz** [comment]
> Check this out: https://github.com/Sunoo/homebridge-plugin-update-check

That's interesting. But I guess it doesn't actually do any updating - It just creates a sensor that you can use to alert yourself when an update is available?

I had forgotten about this thread.  A little annoying that @oznu never replied.  I mostly use Home Assistant now, with only a couple of Homebridge plugins remaining for things like Ring.  I would love to completely get off Homebridge someday.

**Comment by thomaswitt** [comment]
I agree. Auto Update is an essential feature, because you don't want to log in daily and see what has changed and if you need to update.
