### ISSUE TITLE
Testers Wanted: New UI Features For Docker

### ISSUE THREAD

**Issue by oznu** [oznu/docker-homebridge#279]
I'm looking for a few testers who currently use the [oznu/homebridge](https://hub.docker.com/repository/docker/oznu/homebridge) docker image with [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x) enabled.

I'm planning on changing the way the homebridge process is managed inside the container when the UI is enabled, this will enable extra features such as:

* The ability to clear just the Homebridge accessory cache from the UI
* The ability to set the Homebridge `-R` remove orphans Homebridge flag in addition to the existing `-D` debug,  and `-I` insecure mode Homebridge flags from the UI.
* The ability to set the `DEBUG` and `NODE_OPTIONS` environment variables from the UI

### How To Test

If you are interested in testing, you can pull down the `hb-service` tag.

```bash
# alpine
oznu/homebridge:hb-service
oznu/homebridge:hb-service-no-avahi

# debian
oznu/homebridge:hb-service-debian
oznu/homebridge:hb-service-debian-no-avahi
```

If you're using `docker-compose` just update the image in the `docker-compose.yml` file to one of the tags above and run:

```
docker-compose pull
docker-compose up -d
```

### Things To Test

1. Did your existing DEBUG and INSECURE MODE settings persist?
2. Did Homebridge start?
3. Did the UI start on the same port as before?

Please comment below if you were able to successfully test without issue, or if you encountered issues.

### After Testing

After you have finished testing or once these changes have been merged, make sure you roll back the image tag to what is was before.

**Comment by HunterDG** [comment]
Sorry I’m late, been sick, opened this in a browser tab but wasn’t willing to test till I felt better.  Still interested?
