### ISSUE TITLE
Can't start Homebridge (cannot import name ReadTimeoutError)

### ISSUE THREAD

**Issue by mctomski** [oznu/docker-homebridge#28]
Hi - sorry, I don't know where to go with this, I'm just following the instructions! I've tried google and that's not working for me, any suggestions please?

**docker-compose up -d**
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    from . import errors
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/errors.py", line 15, in <module>
    from requests.packages.urllib3.exceptions import ReadTimeoutError
ImportError: cannot import name ReadTimeoutError

**pip freeze**
backports.ssl-match-hostname==3.5.0.1
blinker==1.3
cached-property==1.3.1
chardet==2.3.0
colorama==0.3.2
docker==2.5.1
docker-compose==1.16.1
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
enum34==1.1.6
Flask==0.10.1
functools32==3.2.3.post2
gpiozero==1.4.0
html5lib==0.999
ipaddress==1.0.18
itsdangerous==0.24
Jinja2==2.7.3
jsonschema==2.6.0
lxkeymap==0.1
MarkupSafe==0.23
mcpi==0.1.1
ndg-httpsclient==0.3.2
numpy==1.8.2
picamera==1.13
picraft==1.0
pifacecommon==4.2.1
pifacedigitalio==3.1.0
pigpio==1.35
Pillow==2.6.1
pyasn1==0.1.7
pygame==1.9.2a0
pygobject==3.14.0
pyinotify==0.9.4
pyOpenSSL==0.13.1
pyserial==2.6
python-apt==0.9.3.12
PyYAML==3.12
requests==2.4.3
RPi.GPIO==0.6.3
RTIMULib==7.2.1
sense-emu==1.0
sense-hat==2.2.0
six==1.8.0
smbus==1.1
spidev==3.0
texttable==0.9.1
twython==3.1.2
urllib3==1.9.1
websocket-client==0.44.0
Werkzeug==0.9.6

**Comment by mctomski** [comment]
Tried reinstalling homebridge, which I have up and running, my error has now changed! No actively pursing this, but will leave it open in case anyone has interest

Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    from . import errors
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/errors.py", line 10, in <module>
    import six
ImportError: No module named six

**Comment by oznu** [comment]
Thanks for raising this, looking at the errors you posted it seems like this issue: 

https://github.com/docker/compose/issues/4953

I'll run through the setup guide again from the start to make sure the setup instructions are still correct.

**Comment by oznu** [comment]
I was able replicate this on a fresh install of Raspbian Stretch Lite by installing the same version modules you provided using `pip freeze` - some of which are quite out of date.

How to upgrade all pip dependencies (use with caution if you're running other packages):

https://stackoverflow.com/questions/2720014/upgrading-all-packages-with-pip

Or try re-installing docker-compose (this worked for me):

```
pip install -U docker-compose
pip uninstall docker-py; pip uninstall docker; pip install docker
```

If that still fails you can raise the problem on the [docker/compose](https://github.com/docker/compose/issues) issue tracker as this is not really a problem with the oznu/homebridge docker container.
