### ISSUE TITLE
ffmpeg please help

### ISSUE THREAD

**Issue by dswee999** [oznu/docker-homebridge#280]
I've installed ffmpeg via npm install and added to apk add --no-cache ffmpeg ffmpeg-libs to start up script but I still get no live stream and the error of missing ffmpeg in the logs when trying to live stream. Please help!

**Comment by oznu** [comment]
@dswee999,

Are you running the latest version of this image? It now includes ffmpeg.

**Comment by dswee999** [comment]
I ran the update I think. Sorry I’m new to this so I may have done it wrong. Is there a way I can tell?



On Mar 7, 2020, at 12:05 AM, oznu <notifications@github.com> wrote:

﻿

@dswee999<https://github.com/dswee999>,

Are you running the latest version of this image? It now includes ffmpeg.

**Comment by oznu** [comment]
With logs, environment details, how you started the container and what commands you ran to update I can help you out.

**Comment by dswee999** [comment]
I ran npm install update. Logs show I have 4.12.0 UX I? I’m running the docker on a raspberry pi.



On Mar 7, 2020, at 12:09 AM, oznu <notifications@github.com> wrote:

﻿

With logs, environment details, how you started the container and what commands you ran to update I can help you out.

**Comment by oznu** [comment]
You need to update the Docker container.

If you setup using `docker-compose`, go to the directory containing your` docker-compose.yml` file and run:

```
docker-compose pull homebridge
docker-compose up -d
```

**Comment by dswee999** [comment]
Can I do that with the terminal in the docker?



On Mar 7, 2020, at 12:15 AM, oznu <notifications@github.com> wrote:

﻿

You need to update the Docker container.

If you setup using docker-compose, go to the directory containing your docker-compose.yml file and run:

docker-compose pull homebridge
docker-compose up -d

**Comment by oznu** [comment]
No

**Comment by dswee999** [comment]
Ok. I’m not sure how to get to that directory



On Mar 7, 2020, at 12:21 AM, oznu <notifications@github.com> wrote:

﻿

No

**Comment by dswee999** [comment]
Ok, I got the docker updated via terminal on my Mac. Now when I try to live view it still says camera not responding but the snapshots are working. In the log it doesn’t say anything about FFmpeg just shows were its waiting for livestream data and then it says stopped livestream. I don’t see an actual error in the log.

Thank you for your help!

On Mar 7, 2020, at 12:21 AM, oznu <notifications@github.com<mailto:notifications@github.com>> wrote:


No

**Comment by oznu** [comment]
Hi @dswee999,

Good to see you got the image updated and ffmpeg installed.

I'm not familar with camera plugins, you're probably better off raising an issue on the GitHub page of the plugin you are using, or one of the community support forums such as the Homebridge Reddit or Discord.
