### ISSUE TITLE
Error: Service name is already in use on the network

### ISSUE THREAD

**Issue by ceraz68** [oznu/docker-homebridge#281]
**Describe Your Problem:**
I often get the warning "Error: Service name is already in use on the network" at restart of homebridge in synology docker.  I enabled debugging in config-ux-i but no obvious clue as to where the problem comes from. I'm willing to dig further but maybe someone has come across this problem to focus my search.  I use multiple instances of mqttthing plugin and first thought it might be the fakelgato history logging but that doesn't seem to be the problem.

Strangely it always seems to happen at the same point of the restart. The Siemens dryer is my plugin and my code is:

this.client.on('connect', function(){
	self.client.subscribe(self.power_topic);
	self.client.subscribe(self.light_topic);
	self.log("I subscribed to " + self.power_topic + " and " + self.light_topic);
	});
this.client.on('message', function (topic, message) .....

power_topic is a plug, light_topic is an mqtt controlled light

Any hints where to look for the service names ?
Thanks

**Logs:**
[3/8/2020, 6:39:51 PM] [Bosch Washer] I subscribed to tele/BlitzWolf2/SENSOR and shellies/shelly1pm-60974E/relay/0
[3/8/2020, 6:39:51 PM] [Siemens Dryer] I subscribed to tele/gosund1/SENSOR and shellies/shelly1pm-60974E/relay/0
[3/8/2020, 6:39:51 PM] Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:223:5)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:223:5)
    at UDP.onMessage [as onmessage] (dgram.js:874:8)
[3/8/2020, 6:39:52 PM] Got SIGTERM, shutting down Homebridge...

**Docker Start Command:**
standard synology docker with config-ui-x

**Environment:**

* **Host Operating System**: Synology
* **Docker Version**: Synology docker

Node.js Version | v12.14.1
npm v6.13.4

**Comment by oznu** [comment]
Either the `no-avahi` tag, or changing the name of the bridge in the `config.json` might help.

https://github.com/oznu/docker-homebridge/wiki#image-variants

**Comment by ceraz68** [comment]
thanks oznu, I'll try both options and report back ... a lot of devices to add back to home app &  HomeKit automations to rebuild!

**Comment by oznu** [comment]
I don't think a rename of the bridge will break the existing HomeKit connection.

**Comment by oznu** [comment]
Swapping the container tag definitely won't as long as you map the same volume.

**Comment by ceraz68** [comment]
Wilco, I'll start with the no-avahi tag then.

So after stopping the existing 'latest' container, I simply point the new 'no-avahi' container to the my existing folder located in '/volume1/docker/homebridge' without touching the cached accessories nor persist folder?

**Comment by oznu** [comment]
Correct.

Make sure you copy all the existing settings such as the host networking options etc.

If you used the .spk you can just install it again (no need to uninstall first), and select the no-avahi image and it will replace the container with  that tag.

**Comment by ceraz68** [comment]
Great, I'm working with DSM docker so currently downloading 'oznu/homebridge:no-avahi' image and will rebuild the container.

**Comment by ceraz68** [comment]
Didn't work for me, constant reboots. Now back to the normal homebridge and working to isolate a plugin.

**Comment by ceraz68** [comment]
OK eventually found my issue. Some code had been uncommented within a plugin which ended up creating additional instances of a service with the same name. Pity homebridge doesn't report with which plugin causes such errors.
Thanks for helping me out and learnt more  about the no-avahi tag :-)

**Comment by ceraz68** [comment]
Just to come back to this. My suspected plugin was not the root cause. I still get random "Error: Service name is already in use on the network" when i relaunch the container or restart config ui-x. The container and/or config-ui-x keeping restarting until the error disappears. Sometimes one or two restarts, sometimes none and then it's stable.

I've being trying to isolate with debug by setting the variable in docker HOMEBRIDGE_DEBUG=1, checking 'Enable/disable debug level logging' in config-ui-x, turning off Bonjour on the Synology, launching a container with no-avahi. But the routine generating the error message is not identified. In the Synology docker package terminal window I can access early login information.

It's above my competence but you may be able to spot something. I run a bond on the two Ethernet interfaces of the synology, creating bond0. There are warnings about NSS and mDNS.

I'll learn to live with the random errors.

WITH CONFIG-UI-X 4.13.0

[cont-init.d] 50-plugins: exited 0.                                                                                                      
[cont-init.d] 55-config-ui: executing...                                                                                                 
Enabling homebridge-config-ui-x...                                                                                                       
[cont-init.d] 55-config-ui: exited 0.                                                                                                    
[cont-init.d] done.                                                                                                                      
[services.d] starting services                                                                                                           
Starting dbus-daemon                                                                                                                     
Starting cron                                                                                                                            
[services.d] done.                                                                                                                       
Starting Avahi daemon                                                                                                                    
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).                                                                                  
Successfully dropped root privileges.                                                                                                    
avahi-daemon 0.7 starting up.                                                                                                            
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!                                                                 
Loading service file /etc/avahi/services/sftp-ssh.service.                                                                               
Loading service file /etc/avahi/services/ssh.service.                                                                                    
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***          
Registering new address record for fe80::42:ff:fee6:8a3 on docker0.*.                                                                    
Registering new address record for 172.17.0.1 on docker0.IPv4.                                                                           
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.                                                          
New relevant interface docker0.IPv4 for mDNS.                                                                                            
Joining mDNS multicast group on interface bond0.IPv4 with address 192.168.0.2.                                                           
New relevant interface bond0.IPv4 for mDNS.                                                                                              
Network interface enumeration completed.                                                                                                 
Registering new address record for fe80::211:32ff:fe17:9795 on bond0.*.                                                                  
Registering new address record for 192.168.0.2 on bond0.IPv4.                                                                            
Server startup complete. Host name is DiskStation.local. Local service cookie is 2236653032.                                             
-U /homebridge -P /homebridge/node_modules -C                                                                                            
Service "DiskStation" (/etc/avahi/services/ssh.service) successfully established.                                                        
Service "DiskStation" (/etc/avahi/services/sftp-ssh.service) successfully established.

(...then loads config/plugins)

WITH CONFIG-UI-X 4.13.2

+ homebridge-config-ui-x@4.13.2                                                                                                          
added 5 packages from 4 contributors, removed 52 packages and updated 20 packages in 223.402s                                            
[cont-init.d] 55-config-ui: exited 0.                                                                                                    
[cont-init.d] done.                                                                                                                      
[services.d] starting services                                                                                                           
Starting cron                                                                                                                            
Starting dbus-daemon                                                                                                                     
[services.d] done.                                                                                                                       
Starting Avahi daemon                                                                                                                    
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).                                                                                  
Successfully dropped root privileges.                                                                                                    
avahi-daemon 0.7 starting up.                                                                                                            
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!                                                                 
Loading service file /etc/avahi/services/sftp-ssh.service.                                                                               
Loading service file /etc/avahi/services/ssh.service.                                                                                    
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***          
                                                                                                                                         
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.                                                          
New relevant interface docker0.IPv4 for mDNS.                                                                                            
Joining mDNS multicast group on interface bond0.IPv4 with address 192.168.0.2.                                                           
New relevant interface bond0.IPv4 for mDNS.                                                                                              
Network interface enumeration completed.                                                                                                 
Registering new address record for fe80::42:ff:fee6:8a3 on docker0.*.
Registering new address record for 172.17.0.1 on docker0.IPv4.      
Registering new address record for fe80::211:32ff:fe17:9795 on bond0.*.                                                                  
Registering new address record for 192.168.0.2 on bond0.IPv4.                                                                            
Server startup complete. Host name is DiskStation.local. Local service cookie is 2885146306.                                             
-U /homebridge -P /homebridge/node_modules -C                                                                                            
Service "DiskStation" (/etc/avahi/services/ssh.service) successfully established.                                                        
Service "DiskStation" (/etc/avahi/services/sftp-ssh.service) successfully established.   

(...then loads config/plugins)
