### ISSUE TITLE
FFmpeg_omx hardware encoding

### ISSUE THREAD

**Issue by nope89** [oznu/docker-homebridge#282]
**Is your feature request related to a problem? Please describe:**

FFmpeg on RPi 3+ too slow for homekit live video

**Describe the solution you'd like:**

Support for FFmpeg hardware encoding inside docker for use with plugins like Nest plugin

**Comment by oznu** [comment]
Hi @nope89,

omx decoding inside a container is troublesome as the container does not have access to the hardware it needs directly.

If you need omg decoding then you're probably better off following this guide to setup Homebridge without Docker on your raspberry pi:

https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Raspbian

**Comment by nope89** [comment]
Thanks for your quick and clear reply, i was afraid that would be the problem. I ordered a RPi 4 to try how the software decoding will go on the newer hardware. Else I can try to use your suggestion but I do like your piece of programming with the nice webgui and stuff.. Thanks again!
