### ISSUE TITLE
Ability to test homebridge beta

### ISSUE THREAD

**Issue by mgcrea** [oznu/docker-homebridge#288]
Do you think it would be possible to somehow test newly released versions of homebridge (maybe using an environment var with a post-init script reinstalling the given version). Wanted to try `homebridge@0.4.54-beta.15` (see https://github.com/homebridge/homebridge/issues/2459)

**Comment by oznu** [comment]
Yes that's fine, you can do it using the startup script or just run the commands inside the container.

**Comment by mgcrea** [comment]
Thanks, indeed the `startup.sh` script works.

**Comment by oznu** [comment]
Just remember to remove it when the new version of Homebridge is released, otherwise you might see your install being downgraded 😄
