### ISSUE TITLE
Parameterize HOMEBRIDGE_VERSION

### ISSUE THREAD

**Issue by kavehv** [oznu/docker-homebridge#294]
**Describe Your Problem:**
Cannot specify which homebridge version to install.  This should be relatively trivial to implement, but it would be nice to be able to specify the homebridge version tag (i.e. beta, etc).

**Comment by oznu** [comment]
Homebridge is pre-installed. If you wish to install a certain version you can add this sort of line to the `startup.sh` file and restart the container:
```
npm install -g --unsafe-perm homebridge@0.4.53
```
