### ISSUE TITLE
Update Nodjs Version in docker containers

### ISSUE THREAD

**Issue by Ivanverdonck** [oznu/docker-homebridge#296]
**Describe Your Problem:**
Update Node.js verion like mentioned in latest homebridge release:
The minimum Node.js version required is now v10.17.0.

Kind regards,
Ivan.

**Comment by oznu** [comment]
Update your Docker image and you will have the latest Node.js version and Homebridge release 😄.

**Comment by Ivanverdonck** [comment]
hi oznu, 
thansk for the quick response.

I use the ":no-avahi" version (because on my synology the ":latest" gives host-name issues)
after an update i get following versions:
Homebridge: 1.0.0
NoseJs: 12.16.2
NPM: 6.14.4

Kind regards,

**Comment by Ivanverdonck** [comment]
Sorry my fault... 12.16.2 is higher than the required 10.17.0....

This topic can be closed.
