### ISSUE TITLE
Access /dev/ttyUSB0 from homebridge docker

### ISSUE THREAD

**Issue by vdsc007** [oznu/docker-homebridge#297]
I would like to use the RFlink from homebridge docker and the RFlink plugin but homebridge is not able to access the RFlink device plug in on the synology usb slot and mounted under device /dev/ttyUSB0 

**Logs:**

Homebridge log :

Unhandled rejection Error: Error: No such file or directory, cannot open /dev/ttyUSB0```

Show the Docker container logs here

2020-04-29 09:11:03 | stdout | Unhandled rejection Error: Error: No such file or directory, cannot open /dev/ttyUSB0
-- | -- | --

I use the docker app from diskstation, I don't know the start commande

**Homebridge Config:**

{
            "platform": "RFLink",
            "name": "RFLink test Platform",
            "bridges": [
                {
                    "serialport": "/dev/ttyUSB0",
                    "devices": [
                        {
                            "name": "ELRO",
                            "protocol": "AB400D",
                            "address": "4a",
                            "channels": [
                                {
                                    "channel": 1,
                                    "type": "Lightbulb",
                                    "name": "Desk"
                                },
                                {
                                    "channel": 2,
                                    "type": "Switch",
                                    "name": "TV"
                                },
                                {
                                    "channel": 3,
                                    "type": "Switch",
                                    "name": "Radio"
                                },
                                {
                                    "channel": 4,
                                    "type": "StatelessProgrammableSwitch",
                                    "name": "Button"
                                }
                            ]
                        }
                    ],
                    "delay": 500,
                    "repeat": 0
                }
            ]
        }

* **Host Operating System**: synology DS418Play DSM 6.2
* **Docker Version**: docker 17.05

**Comment by oznu** [comment]
You need to pass through the usb device:

https://docs.docker.com/engine/reference/commandline/run/#add-host-device-to-container---device

https://docs.docker.com/compose/compose-file/#devices

I'm not sure the Synology DSM app will let you do this, so you may have to create the container at the command line.

**Comment by vdsc007** [comment]
I’m a newbie in docker, thus, can you give me the run command used in your package in order to add the —device option ?

**Comment by pagaille** [comment]
Take care : `--device=/dev/ttyUSB0` works, but in order to access it your user must usually be in the `dialout` group. It looks like specifying `--group-add=dialout` to the docker run call is not working, probably because the `PUID=<UID> -e PGID=<GID>` environment variables are overwriting them. Setting `PGID=20` (20 being the dialout group #) works but will probably lead to other permission problems ie to access files on volumes. Any advice on how to add multiple groups (ie 1000 and 20) ?
