### ISSUE TITLE
Hangs on latest release

### ISSUE THREAD

**Issue by drewcovi** [oznu/docker-homebridge#298]
**Describe Your Problem:**
Running on raspberry pi using the debian-raspberry-pi image, the latest update no longer loads. I have to manually stop it.

**Logs:**
```
homebridge    | 
homebridge    | -------------------------------------
homebridge    | GID/UID
homebridge    | -------------------------------------
homebridge    | User uid:    1000
homebridge    | User gid:    1000
homebridge    | -------------------------------------
homebridge    | 
homebridge    | [cont-init.d] 10-adduser: exited 0.
homebridge    | [cont-init.d] 20-set-timezone: executing... 
homebridge    | [cont-init.d] 20-set-timezone: exited 0.
homebridge    | [cont-init.d] 30-packages: executing... 
homebridge    | Installing extra packages for ubuntu linux:  wget
homebridge    | /usr/lib/apt/methods/http: relocation error: /usr/lib/apt/methods/http: symbol _Z12MaybeAddAuthR6FileFdR3URI version APTPKG_5.0 not defined in file libapt-pkg.so.5.0 with link time reference
homebridge    | /usr/lib/apt/methods/http: relocation error: /usr/lib/apt/methods/http: symbol _Z12MaybeAddAuthR6FileFdR3URI version APTPKG_5.0 not defined in file libapt-pkg.so.5.0 with link time reference
homebridge    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
homebridge    | [s6-init] ensuring user provided files have correct perms...exited 0.
homebridge    | [fix-attrs.d] applying ownership & permissions fixes...
homebridge    | [fix-attrs.d] done.
homebridge    | [cont-init.d] executing container initialization scripts...
homebridge    | [cont-init.d] 10-adduser: executing... 
homebridge    | usermod: no changes
```

**Environment:**

* **Host Operating System**: Raspbian Lite
* **Docker Version**: Docker version 19.03.4, build 9013bf5
* **Image Tag / Type**: debian-raspberry-pi

**Comment by oznu** [comment]
Checking. In the mean time you can change the tag to `oznu/homebridge:3.1.0-no-avahi` to undo some recent changes.

**Comment by oznu** [comment]
3.1.0 was probably what you were on before todays update. I made that release before making changes.

**Comment by drewcovi** [comment]
@oznu does the latest image have omx enabled for ffmpeg?

**Comment by oznu** [comment]
No, omx is not enabled.

**Comment by drewcovi** [comment]
@oznu I'm going to close this as it seems closely associated with my startup.sh script that uses wget... it's obviously a pretty common binary, and appears broken based on the items above, but I can use a local package rather than pulling it down and avoid this issue in the future.

**Comment by drewcovi** [comment]
Thank you again for your hard work on this. It's an incredible project.
