### ISSUE TITLE
Alexa Version

### ISSUE THREAD

**Issue by c-o-m-m-a-n-d-e-r** [oznu/docker-homebridge#30]
Hey,
is it possible to install : https://github.com/NorthernMan54/homebridge-alexa

**Comment by oznu** [comment]
It should be possible. Try this:

**Step 1:** Create a new container with a local volume as normal

```
docker run  --net=host --name homebridge -v </path/to/config>:/homebridge oznu/homebridge 
```

This will generate the default container files in your mounted homebridge config folder.

**Step 2:** Find the file named `startup.sh` in the mounted config folder and add this line to the bottom:

```
yarn global add https://github.com/NorthernMan54/homebridge
```

**Step 3:** Restart the container

```
docker restart homebridge
```

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Hey,
thanks ... solved it today.

Thanks for the Image!!

**Comment by jeylites** [comment]
@oznu 
Hope all is well!

I'm trying to install "homebridge-alexa" through the UI web browser but can't seem to get it installed. Is there something I'm missing?

Currently, have 5 instances running. Are we suppose to install homebridge-alexa on all instances or just one?


`
+ homebridge-alexa@0.1.72
updated 1 package in 293.939s

Command succeeded!.

[nodesecurity.io] Scanning plugin for vulnerabilities...

module.js:549
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/nsp/bin/nsp'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

The plugin has still been installed. Use at your own risk.
Security scan returned possible vulnerabilities.`

**Comment by jeylites** [comment]
well, I guess I answered my own question. Got the following turned on and it worked only on one of the homebridge that's running  homebridge-alexa. Guess will have to do the same for all instances.

![screen shot 2019-02-13 at 7 32 28 pm](https://user-images.githubusercontent.com/9190080/52799653-37822280-30b5-11e9-8bb0-e6dd503aee46.png)
