### ISSUE TITLE
Homebridge won't start when required as a peerDependency

### ISSUE THREAD

**Issue by mgcrea** [oznu/docker-homebridge#303]
**Describe The Bug:**

I've recently updated my plugin to depend explicitly on homebridge@>=1.0.0 that enables me to drop the hacky node-hapjs dep. However it won't start this way:

https://github.com/mgcrea/homebridge-tydom/blob/v0.18.1/package.json 

Any ideas? Adding an explicit dependency might fix it but shouldn't be required, no?

[**Logs:**]()

```
homebridge    | [5/10/2020, 10:51:25 AM] ====================
homebridge    | [5/10/2020, 10:51:25 AM] ERROR LOADING PLUGIN homebridge-tydom:
homebridge    | [5/10/2020, 10:51:26 AM] Error: Cannot find module 'homebridge'
homebridge    | Require stack:
homebridge    | - /homebridge/node_modules/homebridge-tydom/lib/platform.js
homebridge    | - /homebridge/node_modules/homebridge-tydom/lib/index.js
homebridge    | - /usr/local/lib/node_modules/homebridge/lib/plugin.js
homebridge    | - /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
homebridge    | - /usr/local/lib/node_modules/homebridge/lib/api.js
homebridge    | - /usr/local/lib/node_modules/homebridge/lib/index.js
homebridge    | - /usr/local/lib/node_modules/homebridge/lib/cli.js
homebridge    | - /usr/local/lib/node_modules/homebridge/bin/homebridge
homebridge    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
homebridge    |     at Function.Module._load (internal/modules/cjs/loader.js:840:27)
homebridge    |     at Module.require (internal/modules/cjs/loader.js:1019:19)
homebridge    |     at require (internal/modules/cjs/helpers.js:77:18)
homebridge    |     at Object.<anonymous> (/homebridge/node_modules/homebridge-tydom/src/platform.ts:1:1)
homebridge    |     at Module._compile (internal/modules/cjs/loader.js:1133:30)
homebridge    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
homebridge    |     at Module.load (internal/modules/cjs/loader.js:977:32)
homebridge    |     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
homebridge    |     at Module.require (internal/modules/cjs/loader.js:1019:19)
homebridge    | [5/10/2020, 10:51:26 AM] ====================

```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

Using an up-to-date docker oznu/homebridge:latest image

```
homebridge    | [5/10/2020, 10:51:19 AM] [HB Supervisor] Homebridge Storage Path: /homebridge
homebridge    | [5/10/2020, 10:51:19 AM] [HB Supervisor] Homebridge Config Path: /homebridge/config.json
homebridge    | [5/10/2020, 10:51:19 AM] [HB Supervisor] Logging to /homebridge/homebridge.log
homebridge    | [5/10/2020, 10:51:20 AM] [HB Supervisor] OS: Linux 5.3.0-51-generic x64
homebridge    | [5/10/2020, 10:51:20 AM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
homebridge    | [5/10/2020, 10:51:20 AM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
homebridge    | [5/10/2020, 10:51:20 AM] [HB Supervisor] Starting Homebridge with extra flags: -P /homebridge/node_modules
homebridge    | [5/10/2020, 10:51:22 AM] [HB Supervisor] Started Homebridge v1.0.4 with PID: 356
```

**Workaround**

Fixed with `ln -s /usr/local/lib/node_modules/homebridge /homebridge/node_modules/homebridge-tydom/node_modules/homebridge` for now.

**Comment by mgcrea** [comment]
Linked issue https://github.com/homebridge/homebridge/issues/2569

**Comment by sman591** [comment]
I added `homebridge` to the `package.json` dependencies as another workaround, though now I get the warning that there's two homebridge installs

**Comment by oznu** [comment]
Homebridge plugins must not import dependencies from Homebridge. Using types is ok - these are removed when you compile your TypeScript.

Also beware we are removing the non-type exports from Homebridge in the next release.

https://github.com/homebridge/homebridge/blob/beta/CHANGELOG.md#for-developers

> Homebridge now only exports types that are safe to use in your code and won't result in the homebridge library being a runtime dependency. If you have been using types correctly then you will not be impacted by this change.

**Comment by oznu** [comment]
Homebridge plugins must not import dependencies from Homebridge. Using types is ok - these are removed when you compile your TypeScript.

Also beware we are removing the non-type exports from Homebridge in the next release.

https://github.com/homebridge/homebridge/blob/beta/CHANGELOG.md#for-developers

**Comment by mgcrea** [comment]
Hum, too bad, looks like I'll revert to require hap-nodejs directly, I need a few enums and constructors from it and I won't refactor the code to pass around a `homebridge.hap` var when it can be statically imported, imo that makes no sense and is a bad design choice.

**Comment by oznu** [comment]
Const enums are exported as normal and can be safely used.

**Comment by sman591** [comment]
@oznu Thanks for calling this out! That easily explains it.

For const enums: if only types are exported and `homebridge` is a devDependency, do you know how we'd import the const enum?

**Comment by oznu** [comment]
> For const enums: if only types are exported and homebridge is a devDependency, do you know how we'd import the const enum?

You can import and use them as normal when homebridge is a devDependency. All references to const enums are replaced with their value when the code is compiled before publishing.
