### ISSUE TITLE
Allow ffmpeg to use hardware accelerated transcoding for camera-ffmpeg

### ISSUE THREAD

**Issue by maisun** [oznu/docker-homebridge#305]
Hi,
Thanks for the docker image, it works great.
I'm trying to get hardware accelerated transcoding for camera-ffmpeg, but notice the installed ffmpeg doesn't support VAAPI. I googled around and found an article here:
https://timothybasanov.com/2018/12/08/hardware-accelerated-h264-encoding-synology-nas.html
I have tried the commands and managed to get HW accelerated transcoding to work. Would it be possible to "replace" the default ffmpeg with the one that supports VAAPI and hardware accelerated transcoding? Thank you

**Comment by ifeign** [comment]
Very interested in this! It would help me migrate Homebridge over to my Synology so I can finally repurpose my Pi

**Comment by malhal** [comment]
I was looking into this too but turns out you don't even need it, change the video codec to copy so it doesn't even do any re-encoding of the stream:

<img width="377" alt="Screenshot 2020-06-13 at 13 05 24" src="https://user-images.githubusercontent.com/916912/84568336-9e315200-ad76-11ea-8d77-ef4589f2a2d9.png">

My camera url is the one in Surveillance Station, IP Camera, right click camera, share stream path. It is already connected to the camera and doing recording so no point in homebridge also connecting to the camera when Surveillance Station is capable of sharing its stream.

**Comment by maisun** [comment]
> I was looking into this too but turns out you don't even need it, change the video codec to copy so it doesn't even do any re-encoding of the stream:
> 
> <img alt="Screenshot 2020-06-13 at 13 05 24" width="377" src="https://user-images.githubusercontent.com/916912/84568336-9e315200-ad76-11ea-8d77-ef4589f2a2d9.png">
> 
> My camera url is the one in Surveillance Station, IP Camera, right click camera, share stream path. It is already connected to the camera and doing recording so no point in homebridge also connecting to the camera when Surveillance Station is capable of sharing its stream.

Copy works for some devices, but looks like other devices asks for different resolution and therefore transcoding is needed. In my setup only 720P camera works on all devices, Full HD cameras only work on iPhone/Mac but not iPad. So there are still cases HW transcoding is needed.

**Comment by malhal** [comment]
I've got a 2018 iPad Pro 11" and copy 1080P is working in live view in the Home app.

**Comment by maisun** [comment]
> I've got a 2018 iPad Pro 11" and copy 1080P is working in live view in the Home app.

Would you mind posting your configuration? In my case the iOS device keeps asking for resolution 1280x720 despite I set maxWidth=1920 and maxHeight=1080

**Comment by malhal** [comment]
I checked my log and it seems the iPad asks for 720p but its happy to receive 1080p. Sorry I have never noticed that before but at least now you can look for other reasons why yours can't connect.
`Start streaming video from Hallway with 1280:720@30fps (299kBit)`

```
{
                    "name": "Hallway",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://syno:123456123456123456123456@localhost:554/Sms=1.unicast",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 30,
                        "maxBitrate": 3000,
                        "vcodec": "copy",
                        "audio": true
                    }
                }
```

**Comment by maisun** [comment]
> I checked my log and it seems the iPad asks for 720p but its happy to receive 1080p. Sorry I have never noticed that before but at least now you can look for other reasons why yours can't connect.
> `Start streaming video from Hallway with 1280:720@30fps (299kBit)`
> 
> ```
> {
>                     "name": "Hallway",
>                     "videoConfig": {
>                         "source": "-rtsp_transport tcp -re -i rtsp://syno:123456123456123456123456@localhost:554/Sms=1.unicast",
>                         "maxWidth": 1920,
>                         "maxHeight": 1080,
>                         "maxFPS": 30,
>                         "maxBitrate": 3000,
>                         "vcodec": "copy",
>                         "audio": true
>                     }
>                 }
> ```

Hi, the config looks very standard. Can I ask what's the bitrate your camera is sending and is it CBR or VBR? Thanks in advance!

**Comment by oznu** [comment]
This container uses https://github.com/homebridge/ffmpeg-for-homebridge,  I'll accept a PR on that project that adds hardware decoding in a portable way (binaries must be static).

Build script:

https://github.com/homebridge/ffmpeg-for-homebridge/blob/master/build-ffmpeg
