### ISSUE TITLE
how to give a dely on homebridge restart

### ISSUE THREAD

**Issue by allwyn007** [oznu/docker-homebridge#308]
**Describe Your Problem:**

**Logs:**

```
Show the Docker container logs here
```

**Docker Start Command:**

```
docker run --net=host ...
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Host Operating System**: 
* **Docker Version**: 
* **Image Tag / Type**:

**Comment by oznu** [comment]
Server restart or homebridge restart?

**Comment by allwyn007** [comment]
my home bridge gets disconnected with fibaro hcl controller whenever the controller restarts... please suggests a way that whenver fibaro homecenter lite restart after 5 minutes homebridge(raspberry pi)should also restart

**Comment by allwyn007** [comment]
this issue iam facing.. so if delay is put i can overcome this issue

**Comment by bugs181** [comment]
> my home bridge gets disconnected

How exactly does your homebridge get disconnected? If this is due to the "fibaro hcl controller" then you need open an a feature request on it's plugin page. What you're asking for is for the plugin to reconnect to your controller. Restarting homebridge isn't the best way to go about this.

**Comment by oznu** [comment]
You could add this to the `startup.sh` script, to delay starting homebridge by 5 minutes:

```
sleep 300
```
