### ISSUE TITLE
Homebridge not visible in Home APP

### ISSUE THREAD

**Issue by Prabhakar1980** [oznu/docker-homebridge#309]
Hoembridge ui is up and running. Able to control the device from the home bridge ui accessories.

Problem is the home bridge is not visible in Home app.

I have installed the docker and homebridge on Raspberry Pi.

Please suggest me to fix the issue. Every thing installed on the easy install option.

**Comment by oznu** [comment]
Try resetting Homebridge. 

https://github.com/homebridge/homebridge/wiki/Connecting-Homebridge-To-HomeKit#how-to-reset-homebridge
