### ISSUE TITLE
New image error with config.json

### ISSUE THREAD

**Issue by gawindx** [oznu/docker-homebridge#311]
After getting the new container version (oznu / homebridge: debian), my config.json file is overwritten and replaced with a new one.
This happens again after each restart of the container.

**Comment by gawindx** [comment]
After a few tries, it seems that some config-ui parameters have changed.
here are the ones i was using and after keeping those from the default file, it seems to work fine.
`        {
            "name": "Config",
            "port": 8089,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "debug": false,
            "platform": "config"
        }`

**Comment by oznu** [comment]
I'm glad you got it working.

It will only replace the config if it contains invalid JSON it can not recover from any other way - it stores a backup in your storage folder with `.invalid`.
