### ISSUE TITLE
Docker RUN with DOCKERFILE

### ISSUE THREAD

**Issue by DonMaverick** [oznu/docker-homebridge#312]
Hello OZNU,
I don't really have an issue.
But I would like to work without a composer, just a dockerfile and the RUN command.
But I can't get it started. 
Could you help me?

Dockerfile:
- FROM oznu/homebridge:raspberry-pi

I tried "run."
- docker run -d -p 8080:8080 --restart always -v config:/homebridge --name homebridge pi_homebridge_v1.0 
-e PGID=1000 
-e PUID=1000 
-e HOMEBRIDGE_CONFIG_UI=1 
-e HOMEBRIDGE_CONFIG_UI_PORT=8080

**Comment by ifeign** [comment]
https://hub.docker.com/r/oznu/homebridge/dockerfile

**Comment by DonMaverick** [comment]
Thank you very much...
And what does the RUN command look like?

Thanks a lot :-)

**Comment by thoschworks** [comment]
You cannot run a container from the Dockerfile. The Dockerfile is the recipe to build the Docker image. And with `docker run` you can only run already built images.

Just add `oznu/homebridge:raspberry-pi` at the end of your `docker run` and Docker will pull the image from Docker Hub.

Don't forget the "\\" at the end of the lines (accept the last).

**Comment by oznu** [comment]
https://github.com/oznu/docker-homebridge#usage
