### ISSUE TITLE
After restart have to reauthorize homebridge app at Ecobee

### ISSUE THREAD

**Issue by jhuebsch** [oznu/docker-homebridge#313]
Whenever the docker image restarts or goes down and brought back up I have to reauthorize homebridge app at Ecobee. The Homebridge plugin repo has this closed issue about it. 
https://github.com/vojtamolda/homebridge-ecobee3-sensors/issues/10

Anyone else running into this issue?
The first reply give a pretty strong clue to what might be occurring but as this is all managed by this docker image I'm not sure how to fix it.

**Comment by ifeign** [comment]
Is there even a need for this? The sensors have showed up in HomeKit natively since 2017

**Comment by jhuebsch** [comment]
There is a version of the Ecobee 3 that lacks HomeKit support, I have that version.

**Comment by ifeign** [comment]
> There is a version of the Ecobee 3 that lacks HomeKit support, I have that version.

What?? Which variant, never heard of this

**Comment by oznu** [comment]
The plugin should store credentials in the homebridge storage folder, not some random location.

The plugin can get the path by calling [`api.user.storagePath()`](https://developers.homebridge.io/#/api/reference#apiuserstoragepath).
