### ISSUE TITLE
Website to Camera plugin

### ISSUE THREAD

**Issue by KampsRoger** [oznu/docker-homebridge#318]
How can i use the homebridge-docker with a plugin called "Homebridge Website To Camera". This plugin needs "/usr/bin/chromium-browser".

**Comment by oznu** [comment]
Alpine image (default), add the `chromium` package via the `startup.sh` script:

```
apk add chromium
```

Ubuntu image, add the `chromium` package via the `startup.sh` script:

```
apt-get update
apt-get install -y chromium-browser
```

**Comment by DonMaverick** [comment]
Hi Oznu,

i ḱnow this case is closed. But i am unable fix this installation.
I use the Composer:

nano docker-compose.yml
-------------------------
version: '2'
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
------------------------
I am unable to install cromium

i tried via terminal:
---------------------------
/homebridge # apk add chromium
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/armhf/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/armhf/APKINDEX.tar.gz
ERROR: unable to select packages:
  chromium (no such package):
    required by: world[chromium]
/homebridge # 
---------------------------

Where i find the startup.sh?
Where is my mistake?

BR
DON

**Comment by harryslapalot** [comment]
I have the same issue. I also would like to use Website to Camera plugin.
I tried to edit startup.sh. That alone did not help. What is the chromium path to specify in the plugin settings?
In the log I get "Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT"
Any ideas?
