### ISSUE TITLE
Avahi still there

### ISSUE THREAD

**Issue by r2ixuz** [oznu/docker-homebridge#324]
Hello,

I am using the latest oznu/homebridge:no-avahi Docker image with "network_mode: host" activated. On the host I run Avahi for netatalk.

But when Avahi on the host starts it still has a problem: avahi-daemon[20858]: *** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***

And it is true:

~ # netstat -anp|grep 5353
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           8207/homebridge
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           8207/homebridge
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           8195/hb-service
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           5641/avahi-daemon:
udp6       0      0 :::5353                 :::*                                5641/avahi-daemon:

Why is Homebridge running in Docker with no-avahi tag still using this port?

**Comment by oznu** [comment]
Are you sure you are running the `no-avahi` tag?

I have just pulled and tested the image and confirmed it is not running.

```
/homebridge # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 s6-svscan -t0 /var/run/s6/services
   27 root      0:00 s6-supervise s6-fdholderd
   28 root      0:00 s6-supervise docker-cmd
  357 root      0:00 s6-supervise cron
  358 root      0:00 s6-supervise hb-service-logs
  359 root      0:00 s6-supervise homebridge-config-ui-x
  361 root      0:00 /usr/sbin/crond -f -S -l 5 -c /etc/crontabs
  363 root      0:00 sh /usr/bin/with-localenv sh ./run
  364 abc       0:00 tail -f --follow=name /homebridge/homebridge.log
  370 root      0:00 sh ./run
  389 root      0:01 {node} hb-service
  401 abc       0:00 {node} homebridge
  436 root      0:00 sh
  441 root      0:00 ps aux
```

Perhaps the `avahi-daemon` you are seeing with netstat is the one on the host?

**Comment by r2ixuz** [comment]
I am not really familiar with Avahi, but as I understand mDNS is a component of it. And this has a problem on start because homebridge is also using UDP port 5353 via "hb-service" and "homebridge" process. The "avahi-daemon" process from my netstat is that one of my host.

My ps aux list looks the same like yours.

I am pretty sure I am using the no-avahi image:

~ # docker images -a|grep homebridge
oznu/homebridge            no-avahi            30057a2810b4        2 weeks ago         589MB

**Comment by oznu** [comment]
> And this has a problem on start because homebridge is also using UDP port 5353 via "hb-service" and "homebridge" process. 

Homebridge will always use 5353, (irrespective of if it's running in Docker or if Avahi is already running on the host)  this is required for it to work.

**Comment by r2ixuz** [comment]
OK thanks for clarification. The strange thing is that everything is working as expected. (netatalk on host and homebridge in Docker)

Only this error message from the host confused me.
