### ISSUE TITLE
Possible to install 2nd instance of homebridge

### ISSUE THREAD

**Issue by jamesngob** [oznu/docker-homebridge#334]
**Describe Your Problem:**

Hello, I would like to install another homebridge instance on the QNAP docker
Is it possible?
Thank you
**Logs:**

```
Show the Docker container logs here
```

**Docker Start Command:**

```
docker run --net=host ...
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Host Operating System**: 
* **Docker Version**: 
* **Image Tag / Type**:

**Comment by oznu** [comment]
Hi @jamesngob,

Yes you can. It's as simple of creating a second Docker container. You just need to change the target of the [`/homebridge` volume mount](https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-QNAP#set-the-volume-mount), and the [`HOMEBRIDGE_CONFIG_UI_PORT`](https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-QNAP#set-environment-variables) to something different from your existing container.
