### ISSUE TITLE
Error when updating plugins

### ISSUE THREAD

**Issue by seppelicous** [oznu/docker-homebridge#337]
**Describe Your Problem:**
From one day to another every update of a plugin throws this error:
`DIR: /homebridge
CMD: npm install --save homebridge-camera-ui@latest

npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@eaDir/.DS_Store@SynoResource": name can only contain URL-friendly characters
`
I restarted the docker container several times and I also pulled a new docker image but still get the same error.
I can update the plugins via terminal, but Homebridge UI X still shows an outdated version of the plugin.

**Logs:**

```
[0;37m[11/23/2020, 11:19:50 AM] [0m[0;36m[Homebridge UI][0m Running Command: npm install --save homebridge-camera-ui@latest
[37m[11/23/2020, 11:19:51 AM] [39m[36m[OpenSprinkler] [39m[90mpolling...[39m
[37m[11/23/2020, 11:19:51 AM] [39m[36m[OpenSprinkler] [39m[90mqueueing up next poll...[39m
[37m[11/23/2020, 11:19:53 AM] [39m[36m[Hue] [39m[90mPhilips hue: bridge request 6: get /lights[39m
[37m[11/23/2020, 11:19:53 AM] [39m[36m[Hue] [39m[90mPhilips hue: bridge request 6: ok[39m
[37m[11/23/2020, 11:19:56 AM] [39m[36m[OpenSprinkler] [39m[90mpolling...[39m
[37m[11/23/2020, 11:19:56 AM] [39m[36m[OpenSprinkler] [39m[90mqueueing up next poll...[39m
[0;37m[11/23/2020, 11:19:58 AM] [0m[0;36m[Homebridge UI][0m [0;31mCommand failed. Please review log for details.[0m
```

```
Show the Docker container logs here
```
same as above

**Docker Start Command:**

Completely configured via Synology Docker App. 
Homebridge is running in bridge mode.
Docker mounts /homebridge
```
docker run --net=host ...
```

**Homebridge Config:**

```json
Get the same error with a complete blank, standard config```

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Host Operating System** Synology DSM 6 (918+)
* **Docker Version**:  I have no idea which version is installed, it is the native Synology Docker App
* **Image Tag / Type**: latest version from 11/23

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by oznu** [comment]
Delete `/homebridge/node_modules/@eaDir`.

Inside the container run:

```
rm -rf /homebridge/node_modules/@eaDir
```

**Comment by seppelicous** [comment]
Perfect, that worked. I already deleted all eadir folders, but deleting package-lock.json solved the issue! Thanks for the lightning fast support!

**Comment by oznu** [comment]
It's DSM creating the `@eaDir` folders, you may want to remove those on launch using the "startup.sh" script.

**Comment by etsyno** [comment]
downloaded homebridge for 918+ when i scan the QR to add accessory or type in homekit setup code keep getting message accessory is not reachable. Reset network settings on iphone but no change
