### ISSUE TITLE
Support DSM 7.0

### ISSUE THREAD

**Issue by wmar** [oznu/docker-homebridge#339]
Any plan to support DSM 7.0?
**Describe Your Problem:**

**Logs:**

```
Show the Docker container logs here
```

**Docker Start Command:**

```
docker run --net=host ...
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Host Operating System**: 
* **Docker Version**: 
* **Image Tag / Type**:

**Comment by elmocito** [comment]
Any update here?

**Comment by dennypage** [comment]
DSM 7 isn't released yet, so your question is probably a bit premature. That being said, see the 2nd comment in issue #375

**Comment by mkuerten** [comment]
Now that DSM 7 is officially released, could this come back on the agenda?

**Comment by elmocito** [comment]
> Now that DSM 7 is officially released, could this come back on the agenda?

I guess @oznu just closed it. So I see no chance for the spk. According to him the manual install also works...

**Comment by mkuerten** [comment]
Sorry, yes, I just finished the manual install and it works great

**Comment by elmocito** [comment]
> Sorry, yes, I just finished the manual install and it works great

Did you just upgrade of DSM and it worked directly? SynOCR and this Package make me scared to upgrade. #nevertoucharunningsystem

**Comment by mkuerten** [comment]
Unfortunately no, I needed to update Docker first and then do a manual install of Homebridge. I installed the second instance of Homebridge in a new directory, installed the plug-ins again and copied my old config.json into the new directory (plus restart of course). Then I deleted the Homebridge from the iOS Home app and added it the new Homebridge as a new accessory. I'm not very deep with my computer knowledge, so don't be scared, if I can do it you can to. Good luck!
