### ISSUE TITLE
Raspberry Pi 3B+ docker-compose "line 1: Not: command not found"

### ISSUE THREAD

**Issue by BlackDiceagain** [oznu/docker-homebridge#349]
I have a Raspberry Pi 3B+ with the newest Raspberry Pi OS an the newest Docker version. I want to use the Raspberry Pi with Homebridge to control my smarthome devices. 
I stuck at step 4. When i enter "docker-compose up -d" i get this message "/usr/local/bin/docker-compose: line 1: Not: command not found". What can i do to run docker-compose?

**Comment by CombTech** [comment]
I found downloading the Raspberry Pi Homebridge image and running from that worked smoothly, however, the Raspberry Pi is then solely used for Homebridge, as I have several Unifi cameras it allows all the resources to be used for Homebridge.

**Comment by CSchmidtDD** [comment]
@BlackDiceagain 

Please make sure you follow from Step 1:  Install docker and docker-compose first, before you use those components.
Even if you have docker installed, `docker-compose` on the other hand will not be included and must be installed separately.

How to do that on RaspbianOS, follow a tutorial here: https://dev.to/elalemanyo/how-to-install-docker-and-docker-compose-on-raspberry-pi-1mo
or refer to the official docker-compose documentation that is linked under [Step 1](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Docker#step-1-ensure-docker-compose-is-installed) here: https://docs.docker.com/compose/install/#alternative-install-options

After installation of docker-compose, you are able to use the command properly in the console.
