### ISSUE TITLE
Feature request: Support for docker healthcheck command

### ISSUE THREAD

**Issue by volschin** [oznu/docker-homebridge#352]
Feature request:
Docker supports a healthcheck in this way:

```
HEALTHCHECK --interval=12s --timeout=12s --start-period=30s \  
 CMD node /healthcheck.js
```
**Describe Your Problem:**

Would be nice if you could implement such functionality. I have seen, that config-UI contains some healthcheck in the code.

**Comment by edasque** [comment]
I would love that as well.

**Comment by EpsilonAlpha** [comment]
The Problem still exists! My Homebridge gets slower and slower over time, so I need a command, I can put into the health check which looks up if the homebridge (not the UI or and "extras") is responding in a short amount of time to requests.
 
Does anyone have a solution for that?

**Comment by EpsilonAlpha** [comment]
Yeah, let's see when the performance degrades again and if health check kicks in. I set the timeout on purpose just on 2 second, because when the performance issue appears, i face response times on my apple clients from around 7 seconds.
 
Will see, keep you updated

**Comment by EpsilonAlpha** [comment]
Okay, something keeps me positive on the health check: I upgraded the homebridge ui, and the homebridge was restarting, the health check failed, even the ui was back because the homebridge itself, wasn't loaded yet.
 
the next health check was successful. So we are on a good way 😎

**Comment by luc-ass** [comment]
This sounds like a quite simple solution. Is is possible to get the accessoryId of any other accessory, so that we do not need extra sensors?

**Comment by S474N** [comment]
I think, that will be usefull function.

**Comment by UNiXMIT** [comment]
I know this is closed but thanks for the solution. Shame there isn't a native solution.

**Comment by janreinhardt** [comment]
I would like to see a healthcheck for this as well!

**Comment by NorthernMan54** [comment]
This was implemented years ago, look at the docker compose sample

**Comment by janreinhardt** [comment]
> This was implemented years ago, look at the docker compose sample

Nope, that is not an implementation. That is just a check via `curl` if there is any output on port 8581.

**Comment by UNiXMIT** [comment]
> > This was implemented years ago, look at the docker compose sample
> 
> Nope, that is not an implementation. That is just a check via `curl` if there is any output on port 8581.

It’s a request to the hb service. If it’s up and responding you get a 200 response. If not then the curl request fails.

**Comment by volschin** [comment]
> It’s a request to the hb service. If it’s up and responding you get a 200 response. If not then the curl request fails.

Not exactly. It is a call to the UI component, but it could be in rare cases that the UI is running but the homebridge server itself is hanging.

**Comment by UNiXMIT** [comment]
> > It’s a request to the hb service. If it’s up and responding you get a 200 response. If not then the curl request fails.
> 
> Not exactly. It is a call to the UI component, but it could be in rare cases that the UI is running but the homebridge server itself is hanging.

Ah OK the program name got me confused
`tcp6       0      0 :::8581                 :::*                    LISTEN      118/hb-service `
