### ISSUE TITLE
Operating system complained of resource exhaustion; did I open too many sockets? RAM-Overflow!

### ISSUE THREAD

**Issue by MarkM500** [oznu/docker-homebridge#354]
**Describe Your Problem:**
Ram-Overflow. System hangs. Infinite number of messages in log. 

**Logs:**
[TuyaAccessory] Operating system complained of resource exhaustion; did I open too many sockets?
```
Show the Docker container logs here
Where to find?

**Environment:**

* **Host Operating System**:  synology linux
* **Docker Version**: 18.09
* **Image Tag / Type**: 

System runs normally. Log normally with command 8s...
After ours system hangs. Message like above in homebridge log. New start, system runs for hours, hangs...

Thanks for any help to solve the problem.
Mark

**Comment by oznu** [comment]
Multiple issues across several projects for the same issue isn't really helpful. The log message is from Tuya so the issue should go there.

Closing in favour of the issue you opened there: https://github.com/iRayanKhan/homebridge-tuya/issues/208
