### ISSUE TITLE
Unable to Extract Docker Image

### ISSUE THREAD

**Issue by cargueta001** [oznu/docker-homebridge#362]
Hello @oznu 
Thanks so much for all the time and work you put into this.
I’m trying to do the latest update for the docker image and I’m unable to get past the extract point due to “no space left on device” (see attached image).
I’ve tried to look up various solutions but haven’t had any success thus far.
![6188F888-FB13-4739-B688-FA3856D249CC](https://user-images.githubusercontent.com/48275759/112234489-dca74780-8bf9-11eb-8667-30509137288c.jpeg)

**Comment by oznu** [comment]
> no space left on device

Your disk (hdd, sd card) is full.

**Comment by cargueta001** [comment]
I’ve verified that the SD Card has 5GB of storage left.
Should I reformat and install or are there other options?

**Comment by cargueta001** [comment]
Issue resolved by using command:
docker system prune
