### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ddong3000** [oznu/docker-homebridge#364]
**Describe Your Problem:**
![519E065B-F918-4427-9C10-45D341CA32D8](https://user-images.githubusercontent.com/54649785/112403982-d1b3fa80-8d52-11eb-8150-ece5bd739032.png)

**Logs:**

```
Show the Docker container logs here
```

**Docker Start Command:**

```
docker run --net=host ...
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

OS | Alpine Linux (3.12.4)
raspberrypi
nodejs v14.16.0
NPM v6.14.11
Homebridge v1.3.4
ConfigUI v4.41.0

**Comment by bwp91** [comment]
This was an issue with the ewelink plugin that has been fixed in the latest version.

**Comment by ddong3000** [comment]
Oh thanks for your reply!
