### ISSUE TITLE
Hostname does not update

### ISSUE THREAD

**Issue by JLafranca** [oznu/docker-homebridge#365]
**Describe Your Problem:**
When updating my Synology NAS 'Servername' and changing 'DSM_HOSTNAME' in Docker, the logs show an error with an old 'servername'

**Screenshots:**

<img width="516" alt="Schermafbeelding 2021-03-27 om 15 17 38" src="https://user-images.githubusercontent.com/75937213/112723619-d4a81a00-8f0f-11eb-985e-f3b0f57175c5.png">
<img width="399" alt="Schermafbeelding 2021-03-27 om 15 17 00" src="https://user-images.githubusercontent.com/75937213/112723624-d70a7400-8f0f-11eb-817b-291d29c908c4.png">
<img width="691" alt="Schermafbeelding 2021-03-27 om 15 16 52" src="https://user-images.githubusercontent.com/75937213/112723627-d96cce00-8f0f-11eb-8527-12a91784e0f9.png">

**Environment:**
* **Host Operating System**: Synology NAS (latest update)
* **Docker Version**: 18.09 (latest)

I have tried rebooting Docker and the image, but with no luck. Updating the image resulted in a servername 'homebridge' in the widget overview in the UI, but obviously my servername (via Server > Info in my NAS) is: 'Lafranca'.

Although my accessories work fine, any help would be appreciated.

BW,
Jeff

**Comment by CLARENNE-Q** [comment]
Same issue Here:

`[5/21/2021, 8:51:22 PM] Homebridge v1.3.4 (Homebridge 26DC) is running on port 52017.
hostname: oznu-homebridge: Host not found`

**Comment by bkonings** [comment]
Hi, seeing the same issue.

Looking at the source it seems that DSM_HOSTNAME applies to Ahavi, this file seems to refer to the DSM_HOSTNAME parameter:

https://github.com/oznu/docker-homebridge/blob/master/root/etc/cont-init.d/40-dbus-avahi

`
# fix for synology dsm - see #35  if [ ! -z "$DSM_HOSTNAME" ]; then    sed -i "s/.*host-name.*/host-name=${DSM_HOSTNAME}/" /etc/avahi/avahi-daemon.conf  else    sed -i "s/.*host-name.*/#host-name=/" /etc/avahi/avahi-daemon.conf  fi
`

As I switched the mDNS Advertiser to Ciao this does not apply.
There seem to be no side effects (besides the error), would be nice to have a similar fix for Ciao mDNS.

**Comment by nVuln** [comment]
I got same issue
I'm using DSM 7

**Comment by mbierman** [comment]
following

**Comment by Rastusik** [comment]
I have the same issue, and I'm also using Synology DSM 7

**Comment by mbierman** [comment]
I had a problem here too. Three similar sounding things that are not the same: 

1. **--name=homebridge** the name of the container
2. **--hostname=** name of your Synology
3. **--env=DSM_HOSTNAME** Also the name of your Synology (at least in my case) 

```
rgs=(
    --name=homebridge
    --hostname=pigpen
    --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    --env=QEMU_ARCH=x86_64
    --env=S6_KEEP_ENV=1
    --env="$nodeVersion"
    --env="$homebridgeVersion"
    --env="$configuiVersion"
    --env=HOMEBRIDGE_CONFIG_UI=1
    --env=HOMEBRIDGE_CONFIG_UI_PORT=8080
    --env=ENABLE_AVAHI=0
    --env=DSM_HOSTNAME=pigpen
    --env=TZ=America/Los_Angeles
    --volume=/volume1/docker/homebridge:/homebridge:rw
    --volume=/homebridge
    --network=host
    --workdir=/homebridge
    --restart=always --log-driver=db --detach=true  -t oznu/homebridge:latest
    )
```

**Comment by dppeak** [comment]
any updates on this?

**Comment by skynan22** [comment]
When I execute "docker inspect <container_name>" on synology shell, there is a difference in the Config section between the values of DSM_HOSTNAME ("snas2") and Hostname ("homebridge"). Is that a Problem and if so how to change Hostname variable? 

<img width="649" alt="Bildschirmfoto 2021-09-17 um 09 35 04" src="https://user-images.githubusercontent.com/6624641/133746735-c8ca08b9-04b7-42f6-9711-2c3644f90fc8.png">
d

**Comment by mbierman** [comment]
@skynan22 see https://github.com/oznu/docker-homebridge/issues/365#issuecomment-882115539

**Comment by AvHal** [comment]
> **Describe Your Problem:** When updating my Synology NAS 'Servername' and changing 'DSM_HOSTNAME' in Docker, the logs show an error with an old 'servername'
> 
> **Screenshots:**
> 
> <img alt="Schermafbeelding 2021-03-27 om 15 17 38" width="516" src="https://user-images.githubusercontent.com/75937213/112723619-d4a81a00-8f0f-11eb-985e-f3b0f57175c5.png">
> 
> <img alt="Schermafbeelding 2021-03-27 om 15 17 00" width="399" src="https://user-images.githubusercontent.com/75937213/112723624-d70a7400-8f0f-11eb-817b-291d29c908c4.png">
> 
> <img alt="Schermafbeelding 2021-03-27 om 15 16 52" width="691" src="https://user-images.githubusercontent.com/75937213/112723627-d96cce00-8f0f-11eb-8527-12a91784e0f9.png">
> 
> **Environment:**
> 
> * **Host Operating System**: Synology NAS (latest update)
> * **Docker Version**: 18.09 (latest)
> 
> I have tried rebooting Docker and the image, but with no luck. Updating the image resulted in a servername 'homebridge' in the widget overview in the UI, but obviously my servername (via Server > Info in my NAS) is: 'Lafranca'.
> 
> Although my accessories work fine, any help would be appreciated.
> 
> BW, Jeff

The only thing that worked for me is.

Duplicate the docker settings to a new docker.
===> Give the docker the name of your server/NAS name <===
Start the docker.
Shutdown the docker and change the name to whatever you want.

**Comment by bccheung** [comment]
> > **Describe Your Problem:** When updating my Synology NAS 'Servername' and changing 'DSM_HOSTNAME' in Docker, the logs show an error with an old 'servername'
> > **Screenshots:**
> > <img alt="Schermafbeelding 2021-03-27 om 15 17 38" width="516" src="https://user-images.githubusercontent.com/75937213/112723619-d4a81a00-8f0f-11eb-985e-f3b0f57175c5.png">
> > <img alt="Schermafbeelding 2021-03-27 om 15 17 00" width="399" src="https://user-images.githubusercontent.com/75937213/112723624-d70a7400-8f0f-11eb-817b-291d29c908c4.png">
> > <img alt="Schermafbeelding 2021-03-27 om 15 16 52" width="691" src="https://user-images.githubusercontent.com/75937213/112723627-d96cce00-8f0f-11eb-8527-12a91784e0f9.png">
> > **Environment:**
> > 
> > * **Host Operating System**: Synology NAS (latest update)
> > * **Docker Version**: 18.09 (latest)
> > 
> > I have tried rebooting Docker and the image, but with no luck. Updating the image resulted in a servername 'homebridge' in the widget overview in the UI, but obviously my servername (via Server > Info in my NAS) is: 'Lafranca'.
> > Although my accessories work fine, any help would be appreciated.
> > BW, Jeff
> 
> The only thing that worked for me is.
> 
> Duplicate the docker settings to a new docker. ===> Give the docker the name of your server/NAS name <=== Start the docker. Shutdown the docker and change the name to whatever you want.

It seems like the hostname used by homebridge is taken from the container name rather than the DSM_HOSTNAME environment variable? I just managed to change the hostname by simply shutting down the container, renaming the container to my NAS server name, and resetting the container. Once the container started, the host name changed.

**Comment by mbierman** [comment]
> It seems like the hostname used by homebridge is taken from the container name rather than the DSM_HOSTNAME

Seems to me that is a bug.

**Comment by cramerry** [comment]
Same issue, DSM 7.  Any guidance how to fix yet?

**Comment by mbierman** [comment]
@bccheung 
> I just managed to change the hostname by simply shutting down the container, renaming the container to my NAS server name, and resetting the container. Once the container started, the host name changed.

I changed the name of the container and restarted and homebridge was still called, "homebridge" not my NAS name. Were there any other steps that you completed?

**Comment by oznu** [comment]
The `DSM_HOSTNAME` only changes the name for the Avahi process that may be running inside the container.

It does not change the host name of the container.
