### ISSUE TITLE
npm out of date

### ISSUE THREAD

**Issue by mbierman** [oznu/docker-homebridge#366]
**Describe Your Problem:**
Current docker image uses npm v6.14.11 but 7.7.6 is latest.

**Logs:**
NA

**Docker Start Command:**

```
docker run --name=homebridge \
        --hostname=homebridge \
        --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
        --env=QEMU_ARCH=x86_64 \
        --env=S6_KEEP_ENV=1 \
        --env=NODE_VERSION=12.16.3 \
        --env=HOMEBRIDGE_VERSION=1.0.4 \
        --env=CONFIG_UI_VERSION=4.17.1 \
        --env=HOMEBRIDGE_CONFIG_UI=1 \
        --env=HOMEBRIDGE_CONFIG_UI_PORT=8080 \
        --env=ENABLE_AVAHI=0 \
        --env=DSM_HOSTNAME=pigpen \
        --env=TZ=America/Los_Angeles \
        --volume=/volume1/docker/homebridge:/homebridge:rw \
        --volume=/homebridge \
        --network=host \
        --workdir=/homebridge \
        --restart=always \
        --log-driver=db \
        --detach=true \
        -t \
        oznu/homebridge:latest"
```

**Homebridge Config:**
NA

**Screenshots:**

![image](https://user-images.githubusercontent.com/1205471/112896840-c08d2580-9093-11eb-8401-8ad0f791be94.png)

**Environment:**
* **Node.js Version**: 14.16.0
* **NPM Version**: 6.14.11
* **Homebridge Version**: 1.3.4
* **Homebridge Config UI X Version**: v4.40.1
* **Operating System**: Docker
* **Process Supervisor**: Docker 
* **Alpine Linux**:3.12.4

**Comment by oznu** [comment]
Npm is pinned to the LTS version, which is currently 6.4.11.

https://nodejs.org/en/download/

> Latest LTS Version: 14.16.0 (includes npm 6.14.11)
