### ISSUE TITLE
[Question] Command for restarting homebridge server from inside the container

### ISSUE THREAD

**Issue by bluefangs** [oznu/docker-homebridge#368]
No problem as such, I would like to have a switch exposed inside of home app to restart homebridge service. Similar to how clicking on the power icon in the top right corner of the homebridge ui triggers a homebridge service restart. Please note, I do not want to restart the entire docker container. I just want to mimic the homebridge service restart inside the running container.

`http://<homebridge_ip>:<homebridge_port>/restart` causes the service to restart. What is the command line equivalent of this?

**Comment by oznu** [comment]
Send a SIGTERM to the homebridge process.

**Comment by bluefangs** [comment]
Super! Also, how will I know that the service restart has finished? So that I can configure this as a command2 switch. As in, once the service is up again, show the switch as "on"

**Comment by oznu** [comment]
The kill command will exit immediately. You might have to do some other things to work out if it's running again.

**Comment by bluefangs** [comment]
This will do:

```
/homebridge # netstat -tulpn | grep -i 51803
```
