### ISSUE TITLE
Qnap hombridge install

### ISSUE THREAD

**Issue by 8aws** [oznu/docker-homebridge#369]
I try several times in the last months with the official container in Qnap and following the web instructions but getting always the same error

s6-applyuidgid: fatal: unable to exec tail: Permission denied

it fails at start, and not get any error idea in the log file cause not write more than the GitHub hello text. I've check the permissions on homebridge folder and it looks correct.

[HB Supervisor] Homebridge Storage Path: /homebridge                                                                           
[5/18/2021, 10:07:16 AM] [HB Supervisor] Homebridge Config Path: /homebridge/config.json                                                                
[5/18/2021, 10:07:16 AM] [HB Supervisor] Logging to /homebridge/homebridge.log                                                                          
s6-applyuidgid: fatal: unable to exec tail: Permission denied        

thanks in advance

**Comment by oznu** [comment]
Make sure you're mounting a folder one level down from your QNAP share. You cannot mount on the root of a share.

**Comment by 8aws** [comment]
it's mounted under datavol1/container/homebridge but at same level of container-station-data

**Comment by rjperry36** [comment]
@oznu if the config has been setup as datavol1/container/homebridge. Is that correct?

**Comment by williezou** [comment]
I got the same error, how do you solve the issue?

**Comment by williezou** [comment]
> 
I got the same error, how do you solve the issue?

**Comment by 8aws** [comment]
I fix some time ago but can't remember, but possibly was something about folder permissions. I create a new folder under the main Container folder and install from there. All works ok
