### ISSUE TITLE
Support for DSM 7

### ISSUE THREAD

**Issue by elmocito** [oznu/docker-homebridge#375]
Due to the fact that the major release of DSM 7 will be by the end of the month, it would be awesome to get the support of the oznu homebridge container.
For me it was not working on the RC... :-(

**Comment by cpapazoglou** [comment]
Following this method 
https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology#1-download-docker-image
worked great for me 🤞

**Comment by classicjazz** [comment]
I upgraded my Synology to DSM 7.0 release. It continues to run the docker instance of Homebridge without any apparent issues. 

But... the Synology package for Homebridge is flagged as needing attention: "the package version installed is incompatible with your DSM"

**Comment by joshuachung** [comment]
I upgraded my Synology to DSM 7.0 release(DSM 7.0-41890). It say its HomeBridge is stopped but in fact its running.

**Comment by oznu** [comment]
DSM 7 is supported using the manual method, the SPK is not supported.
