### ISSUE TITLE
DSM 7 instructions

### ISSUE THREAD

**Issue by mschwartz** [oznu/docker-homebridge#378]
**Describe Your Problem:**
Instructions for installing on DSM 7 are almost non-existent.  It would be ideal to have step by step instructions how to use docker directly as suggested.

**Comment by boris1993** [comment]
Running with docker compose is the same as in DSM6.x

**Comment by sledmonkey** [comment]
The package center is showing it as stopped and says it's incompatible with with your DSM.  It is still running in the docker manager.  Looks to be a cosmetic bug?
![image](https://user-images.githubusercontent.com/1825335/128617243-f9aac15a-1263-4022-b877-bd2992b30947.png)

**Comment by panthertom** [comment]
same here. Any experience with restarting home bridge itself? Does it work properly after a reboot?
Thanks!

**Comment by bkonings** [comment]
After reinstalling the docker package this issue was resolved for me:
https://archive.synology.com/download/Package/Docker

Reboot also working fine after initially having this issue (on a NAS that officially has no docker support)

**Comment by shidevil** [comment]
How do we remove the homebridge syno package without removing the docker container? any instruction on that?

**Comment by rudibarani** [comment]
I duplicated the Docker for safety and just deinstalled the Synology package. It did not affect the running docker image of Homebridge.
