### ISSUE TITLE
Node.js v14.17.x

### ISSUE THREAD

**Issue by aschoepe** [oznu/docker-homebridge#380]
I saw that I can update the docker installation this way.

docker stop homebridge
docker pull oznu/homebridge:latest
docker start homebridge

Currently contains the oznu/homebridge:latest Node.js v14.15.1

I have seen that updates to Node.js 14.17.3 have already been built in the master. Can I access it already via the way described above with another token? Or do I have to wait for the next release? There is a package I would like to install, but it requires Node.js >= v14.17.0.

Best
Alex

**Comment by oznu** [comment]
```
I saw that I can update the docker installation this way.

docker stop homebridge
docker pull oznu/homebridge:latest
docker start homebridge
```

This will not work. You need to recreate the container or use `docker-compose` and run:

```
docker-compose pull homebridge
docker-compose up -d
```
