### ISSUE TITLE
Broadcast homebridge.local from docker container

### ISSUE THREAD

**Issue by Soneji** [oznu/docker-homebridge#381]
Hi

I would like to be able to broadcast the `homebridge.local` domain name with avahi, just like it is done when I installed homebridge directly on my pi (using the sd card image), is it possible to do this with the docker version of homebridge?

Do I need to expose any specific volmes?

I found this file, but would love to know if I'm going in the right direction
https://github.com/oznu/docker-homebridge/blob/a98e2338217159bd7dc03dd3b77849c0094cff03/root/defaults/avahi-daemon.conf#L2

Thanks in advance

**Comment by Soneji** [comment]
Hi, please don't close this issue. I still have this problem

**Comment by jspv** [comment]
It's undocumented, but the docker argument `-e DSM_HOSTNAME myhostname` will configure avahi to advertise `myhostname.local`. 

Note: you will need be running your docker in either `host` networking or `macvlan` networking for mDNS/Avahi to work.
