### ISSUE TITLE
Multiple instances of Homebridge on Docker Synology seem to share accessories

### ISSUE THREAD

**Issue by g33z3riley** [oznu/docker-homebridge#382]
Hi there - amazing work on homebridge - I love it! 
I've got 7 instances of Homebridge running in Docker on my Synology NAS and in each case have created them with a volume /homebridge(x) x=1-7 and created a new folder for each. I've also changed the ports in the config as soon as I first start it. When I start up homebridge the log always says hostname: oznu-homebridge(x): Host not found. I've noticed also that the config in the system information window for all the instances seems to have the same config file i.e. /homebridge/config.json and each instance shows all of the accessories from all of the homebridges rather than just the accessories I've created in that particular instance. 
I've also noticed that the folder I created for the homebridge container is empty in each case.
Have I done something wrong when I'm creating the homebridge instances?

<img width="1271" alt="Screen Shot 2021-08-04 at 5 19 09 am" src="https://user-images.githubusercontent.com/86230495/128074173-622160c8-8bc3-4a00-bc1c-34b11d6c1fb8.png">

<img width="930" alt="Screen Shot 2021-08-04 at 5 16 34 am" src="https://user-images.githubusercontent.com/86230495/128074233-59dbb924-1e50-4e2c-854b-ac3cd155871a.png">

<img width="1082" alt="Screen Shot 2021-08-04 at 5 11 47 am" src="https://user-images.githubusercontent.com/86230495/128074263-0c730800-699e-48ab-8f63-c9be3ab8b837.png">

**Comment by thecem** [comment]
In docker container there is no folder with homebridge(X).
Every of your dockers are clones so only the outside world need to be numbered. In docker use it without number…

**Comment by g33z3riley** [comment]
Ah great thank you! Is it normal for the accessories to show up in all the homebridge instances? I imagined only the accessories created within the homebridge instance would show up but instead every homebridge shows every accessory.

**Comment by g33z3riley** [comment]
Sorry I just realised what you meant. I was trying to add a number to the volume Mount where I didn't need to. Sorry I'm new to all this

**Comment by superpower10** [comment]
> In docker container there is no folder with homebridge(X).
> Every of your dockers are clones so only the outside world need to be numbered. In docker use it without number…

Sorry, but I don’t understand it. What do I have to do exactly to get two different instances of homebridge with different plugins, etc.
