### ISSUE TITLE
Node.js 14.17.6 

### ISSUE THREAD

**Issue by blu-e-man** [oznu/docker-homebridge#387]
Please support node.js 14.17.6.
Thank you!

**Comment by psdc-create** [comment]
Hi - I have the same issue. I have a plug-in that requires 14.17.6. I've tried every work around I can think of but I must be missing something. Please help.

**Comment by BorussiaPlayer17** [comment]
Not upgrading my Homebridge-Hue Plugin because of required node.js version 14.17.6. Waiting for update.

**Comment by Fish2** [comment]
also running hue and need  v14.17.6 LTS

**Comment by bpoetzschke** [comment]
Created PR https://github.com/oznu/docker-homebridge/pull/389 to bump the node version.

**Comment by oznu** [comment]
Thanks @bpoetzschke!
