### ISSUE TITLE
Cannot start service homebridge: OCI runtime create failed

### ISSUE THREAD

**Issue by shrowner** [oznu/docker-homebridge#39]
I appreciate all your work here.  It looks great!  However, I am unable to get the docker container to start.  Please see the terminal output below:

pi@raspberrypi:~/homebridge $ docker-compose up -d
Starting homebridge_homebridge_1 ...
Starting homebridge_homebridge_1 ... error

ERROR: for homebridge_homebridge_1  Cannot start service homebridge: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/81c92b582a1966519a9e6f4ff71e1be5c0faa42c141dc2c184327750c71fb38b/log.json: no such file or directory): docker-runc did not terminate sucessfully: unknown

ERROR: for homebridge  Cannot start service homebridge: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/81c92b582a1966519a9e6f4ff71e1be5c0faa42c141dc2c184327750c71fb38b/log.json: no such file or directory): docker-runc did not terminate sucessfully: unknown
ERROR: Encountered errors while bringing up the project.

pi@raspberrypi:~/homebridge $ docker-compose restart homebridge
Restarting homebridge_homebridge_1 ... error

ERROR: for homebridge_homebridge_1  Cannot restart container 81c92b582a1966519a9e6f4ff71e1be5c0faa42c141dc2c184327750c71fb38b: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/81c92b582a1966519a9e6f4ff71e1be5c0faa42c141dc2c184327750c71fb38b/log.json: no such file or directory): docker-runc did not terminate sucessfully: unknown

pi@raspberrypi:~/homebridge $ docker-compose logs -f
Attaching to homebridge_homebridge_1
homebridge_homebridge_1 exited with code 128

pi@raspberrypi:~/homebridge/config $ docker-compose pull homebridge
Pulling homebridge (oznu/homebridge:raspberry-pi)...
raspberry-pi: Pulling from oznu/homebridge
Digest: sha256:d6f0653b085cf16b6b0cf05813f21f0226f253e630170d320611cb5f155e00f7
Status: Image is up to date for oznu/homebridge:raspberry-pi

**Comment by oznu** [comment]
It looks like the latest release of Docker and Raspbian don't get along.

Can you post the output from the `docker --version` and `uname -a` commands?

I wasn't able to replicate the exact error you received when running through a fresh build, but did encounter [this](https://github.com/moby/moby/issues/35587) error which should be [fixed](https://github.com/moby/moby/pull/35645) when the next version of Docker is released.

Downgrading to Docker 17.10.0 fixed the issue I was having. Can you try downgrading to a known-good version of Docker and see if this fixes your problem as well?

```
sudo apt-get install -y docker-ce=17.10.0~ce-0~raspbian --allow-downgrades
```
