### ISSUE TITLE
update Node.js v14.18.0 or later

### ISSUE THREAD

**Issue by danielschafer** [oznu/docker-homebridge#391]
Please support Node.js v14.18.0 or later.
It is needed for Phillips hue plugin.
Thank you!

**Comment by oznu** [comment]
The current image is on 14.18.0.

**Comment by vskal** [comment]
I also need to update the Node.js
As far as I understand, for Homebridge installations in Alpine Docker it is not that simple.

I need to recreate the container so I stopped my working container.
I created a new Docker container by installing the latest oznu/homebridge with different port and name
However the Node.js is still showing 14.15.4

Can we please have some advice on how to recreate the container with an updated Node.js ?
