### ISSUE TITLE
Synology installation DSM 7 - please state this clearly in your WIKI

### ISSUE THREAD

**Issue by Marcus4Aspern** [oznu/docker-homebridge#393]
After I have followed the step by step guide I ran into an issue: The Homebridge service repeatedly stopped because of E/A Errors und no write permission. At first I didn´t find any solution in the internet. Then I realized what my fault has been: At the step "Volume - add folder" I chose one of my public folders, not the docker one - after haven chosen docker/Homebridge an not data/Homebridge, all worked out OK. So please state that you have to chose docker as top folder. Thanks

**Comment by oznu** [comment]
I don't have a system capable or running DSM 7 right now; however the wiki can be edited by anyone - so if you're able to make the changes that would be appreciated.
