### ISSUE TITLE
Nodejs update

### ISSUE THREAD

**Issue by no-Legend** [oznu/docker-homebridge#394]
**Describe Your Problem:**
Some homebridge plugins need a newer version of nodejs 
Would be greate to use an env variable to use select the nodejs and other software version.

**Comment by gregnorz** [comment]
We really need a new Docker image. node.js is out of date, even the latest commit to bump Homebridge to 1.3.6 is behind (Homebridge is at 1.3.8 as of this writing). npm needs to be bumped as well. Is it possible to get a release soon? The last one was nearly a year ago.

**Comment by blu-e-man** [comment]
> We really need a new Docker image. node.js is out of date, even the latest commit to bump Homebridge to 1.3.6 is behind (Homebridge is at 1.3.8 as of this writing). npm needs to be bumped as well. Is it possible to get a release soon? The last one was nearly a year ago.
> 
> Edit to note that I'm going by the GitHub releases. I assume what's in Docker Hub is more current, but it would be nice if they were in sync!

I would also love it if there was a new Docker image.

**Comment by oznu** [comment]
Node.js is already on the latest LTS version: 

https://github.com/oznu/docker-homebridge/blob/master/Dockerfile#L2

An image with Homebridge 1.3.8 is being built now 😄 

Feel free in the future to submit a PR to update the versions; this will make it possible for me to update the image while I'm away from the computer for a few days.

**Comment by gregnorz** [comment]
Thanks for the update, @oznu! Going forward, would you recommend monitoring releases here on GitHub or via Docker Hub? And I'll keep in mind that I should PR a change like this in the future.
