### ISSUE TITLE
Latest version of Docker image seems to break some plugins

### ISSUE THREAD

**Issue by raspberrycoulis** [oznu/docker-homebridge#397]
**Describe Your Problem:**
Updating the Docker container to the latest (v1.3.6) may have a permission issue as it causes an issue outlined [here](https://github.com/merdok/homebridge-webos-tv/issues/405), which is apparently not caused by the plugin.

**Logs:**
```
Error: EACCES: permission denied, mkdir '/root/.lgtv2'
```

**Environment:**

* **Host Operating System**: Synology DSM 6.2.4-25556 Update 2
* **Docker Version**: 20.10.10, build b485636
* **Image Tag / Type**: latest

**Comment by oznu** [comment]
The plugin should not attempt to write outside the homebridge storage directory. Commented on linked issue.

**Comment by raspberrycoulis** [comment]
So the plug-in developer points towards you and you point us back to the plug-in developer?
