### ISSUE TITLE
Feature Request: Have versioned image tags

### ISSUE THREAD

**Issue by rafaelgaspar** [oznu/docker-homebridge#398]
**Describe Your Feature Request:**

Not having versioned tags means that for people using Kubernetes to deploy our homebridge containers we always need to inform the image SHA256 for every version.

So it would be nice to have the possibility of referencing it by version, and would also make update automations through something like FluxCD possible.

**Comment by oznu** [comment]
Versioned images will be created with the build date as the tag.

eg. `docker pull oznu/homebridge:2021-11-25`

See https://github.com/oznu/docker-homebridge/pkgs/container/homebridge for all tags.
