### ISSUE TITLE
Segmentation fault (core dumped) after two days - Synology DSM 7 Docker

### ISSUE THREAD

**Issue by DonkeyKongJr** [oznu/docker-homebridge#400]
**Describe Your Problem:**
I installed the latest Docker Image from Homebridge on my DS1621+ Synology with DSM 7 a couple of days ago and everything worked fine. Suddenly today in the morning the Homebridge stopped working and is neither available via HomeKit not the Configuration UI. The networking settings are HOST and the mapped volume is docker/homebridge -> /homebridge. Auto restart is set to true as well. I tried to restart everything, but still no luck.

**Logs:**
For the logs see the screenshot below.

**Screenshots:**

![image](https://user-images.githubusercontent.com/29427429/143856146-ca8051ad-8e53-41f6-bc4d-f15505ae55c0.png)

**Environment:**

* **Host Operating System**: Synology DSM 7
* **Docker Version**: 20.10.3-1239 (latest Docker for Synology)
* **Image Tag / Type**:  latest

**Comment by cgmckeever** [comment]
@DonkeyKongJr Any insight into this .. Im having the container drop daily, Im on a PI, so not sure if its a resourcing issue.
