### ISSUE TITLE
homebridge-yeelighter v2.3.18 needs node.js 16.6.0

### ISSUE THREAD

**Issue by nexuscan** [oznu/docker-homebridge#410]
**Describe Your Problem:**
using lates version of homebridge and using homebridge-yeelighter v2.3.13
I am try to update to homebridge-yeelighter v2.3.18 but is says:
The homebridge-yeelighter plugin recommends running on Node.js v16.6.0 or later.
You are currently running Node.js v14.18.0.
Are you sure you want to update homebridge-yeelighter?

is there way to update node.js verson to 16.6.0 ?

**Logs:**

```
Show the Docker container logs here
```

**Docker Start Command:**

```
docker run --net=host ...
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Host Operating System**: 
* **Docker Version**: 
* **Image Tag / Type**:

**Comment by patricksmith0330** [comment]
Use command `sudohb-service update-node`

**Comment by setheryb** [comment]
Running that command, at least from my Synology gives me this response

`✖ Updating Node.js on Alpine Linux / Docker is not supported by this command.
✖ To update Node.js you should pull down the latest version of the oznu/homebridge Docker image.`

Seems like the update needs to be made at the level of the image.

**Comment by S474N** [comment]
There is new version with Node.js v16.13.2
