### ISSUE TITLE
npm install need ssh

### ISSUE THREAD

**Issue by mcnahum** [oznu/docker-homebridge#414]
I choose to re-install one of my hombridge docker on my Synology and I have a new error ...

I installed the container, copied my config.json file and start it.
of course I got a "No plugin was Sound for the platform "BroadlinkRM" in your config. json. Please make sure the corresponding plugin da installed correctly." as it was not installed. moved to the Homebridge UI to install my plugin ... and there is my surprise:

/homebridge # npm install --save homebridge-broadlink-rm@latest
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/lprhodes/homebridge-platform-helper.git
npm ERR! ssh -oStrictHostKeyChecking=accept-new: line 1: ssh: not found
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-26T16_27_48_758Z-debug.log
/homebridge # sudo npm install --save homebridge-broadlink-rm@latest
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/lprhodes/homebridge-platform-helper.git
npm ERR! ssh -oStrictHostKeyChecking=accept-new: line 1: ssh: not found
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-26T16_28_00_220Z-debug.log

I did it multiple time .. and it's the same issue.

Is it normal or a bug?
What next? install ssh?

**Comment by felsus** [comment]
I observe the same problem and I don't understand how to solve that.
Perhaps I made something wrong but I tried to install ssh, installed some key from GitHub...but nothing worked. At the moment I am not able to install home bridge addons

**Comment by tritter** [comment]
@felsus did you find a solution?

**Comment by rbronco21** [comment]
Here's my result. The approved Arlo plugin is broken and hasn't been updated for a couple years.

```
root@d60b74dc4268:/homebridge $ npm install lcalvy/homebridge-arlo
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/lcalvy/homebridge-arlo.git
npm ERR! No user exists for uid 99
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

**Comment by felsus** [comment]
> @felsus did you find a solution?
@tritter 
No, not really. Tried it a couple of days ago, but didn't worked out.
