### ISSUE TITLE
Node.js v16.14.2 needed for Plugin Homebridge ZP

### ISSUE THREAD

**Issue by jr7216** [oznu/docker-homebridge#425]
Node.js v16.14.2 needed for Plugin Homebridge ZP

**Comment by Fish2** [comment]
Hue and samsung tv needs the same

**Comment by Spy-1** [comment]
please updat container with Node 16.14.2 and NPM 8.5.5

**Comment by JasSmiths** [comment]
Agree, I keep getting spammed to say there’s a NodeJS and NPM update

**Comment by Faasteer** [comment]
Jablotron and some others plugins need this update too. Please help us. :)

**Comment by blue-kaleidoscope** [comment]
Yup, I am also affected unfortunately. :-/

**Comment by AlexG-78** [comment]
I found a hacky workaround for my Synology Docker container. I updated node manually to 16.4.2

1. Login via ssh then type: `docker exec -it homebridge /bin/sh`
2. Edit the repositories file for apk `vi /etc/apk/repositories`
3. Change the repositories version to 3.15
`http://dl-cdn.alpinelinux.org/alpine/v3.15/main`
`http://dl-cdn.alpinelinux.org/alpine/v3.15/community`
4. Then do
`apk update`
`apk install node`
`mv /usr/local/bin/node /usr/local/bin/node_old`
`ln -s /usr/bin/node /usr/local/bin/`
5. run `node -v`
v16.14.2
6. restart your container and you can update your plugins.
This solution works for me until the new image is deployed to docker repo

**Comment by blue-kaleidoscope** [comment]
Does not work on my container unfortunately. In step 4 after the update step I had to use
`apk add node` instead of `apk install node` as install is not available on my container. Isn't it weird that this command works on your system?

Anyway, here is my output with `add`

`/homebridge # apk add node
ERROR: unable to select packages:
  node (no such package):
    required by: world[node]`

Any ideas?

**Comment by Fish2** [comment]
I did nodejs and that worked

**Comment by Fish2** [comment]
Also on another note alpine, s6 and [ffmpeg-for-homebridge](https://github.com/homebridge/ffmpeg-for-homebridge)

Also nodejs container tag is also not inline with what is inside the container.

**Comment by S474N** [comment]
New HB with nodejs v16.14.2 is available on DockerHub ;)

https://hub.docker.com/r/oznu/homebridge/tags

**Comment by jr7216** [comment]
HB with nodejs v.16.14.2 is available.
