### ISSUE TITLE
Restarting docker container results in multiple failures

### ISSUE THREAD

**Issue by evilsparc** [oznu/docker-homebridge#43]
I'm experiencing an issue with the image/container where any form of restart (manual or auto/policy) results in the system complaining about duplicate accessories (`Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory`). Stopping the container, removing /persist and /accessories before starting again seems to help, but then it seems as though HomeKit doesn't recognize the bridge anymore and I have to go through a removal/setup process on one of my devices to bring it all back.

Please tell me I'm doing something stupid and help me understand how to make the container/devices persist across restarts.

Host is a ReadyNAS box (v6.9.1.. which is Debian 8.9) with Docker CE 17.09. I build the container using:
`docker create --net=host --name=homebridge -e PUID=98 -e PGID=98 -e TZ=America/Los_Angeles -v /home/admin/docker-homebridge-config:/homebridge --restart unless-stopped oznu/homebridge`. I use this because I don't have Docker Compose installed on the host. The only plugin I have installed (using the yarn method) is Tplinksmarthome v3.10. I also have Portainer installed and thought maybe it was issuing funky commands behind the scenes that were causing me trouble, but the issue persists when using native CLI commands to start/stop/restart.

**Comment by oznu** [comment]
Hi @evilsparc,

I'm fairly sure this one is going to be an issue with the `homebridge-tplink-smarthome` plugin since there are several existing issues and a mention in the [README](https://github.com/plasticrake/homebridge-tplink-smarthome#uuid-errors) about the problem.

```
https://github.com/plasticrake/homebridge-tplink-smarthome/issues/46
https://github.com/plasticrake/homebridge-tplink-smarthome/issues/27
https://github.com/plasticrake/homebridge-tplink-smarthome/issues/22
```

Mounting the `/homebridge` volume should be the only thing you have to do for your HomeKit config to persist between restarts.

**Comment by evilsparc** [comment]
I reviewed the readme (which is where I think I learned about clearing the caches) but don’t know why I didn’t check the issues section of that repo. Apologies for missing that one. I’ll close this out and keep tabs using one of the issues you so kindly linked. Thank you!
