### ISSUE TITLE
NEWBIE QUESTION: Can this act as hub to replace my iPad?

### ISSUE THREAD

**Issue by paradoxgrowth** [oznu/docker-homebridge#436]
Hi I am new to homebridge (and a bit to HomeKit). So sorry for the dumb question! I was able to get this container up and running on my QNAP and was wondering if it could act as my hub. I am currently using an older iPad as a hub and it is unreliable. I am sure there has to be an addin or something I could install. After searching google and the pluggins I don't really see anything. 

Thanks so much for building this, creating great installation instructions and finally your help!

**Comment by oznu** [comment]
It cannot. You'll need an iPad or Apple TV or HomePod to act as your home hub.
