### ISSUE TITLE
Notice: Removing Alpine Linux variant 

### ISSUE THREAD

**Issue by oznu** [oznu/docker-homebridge#437]
From the next release this image will no longer build the **Alpine Linux** variants of the image, only **Ubuntu-based** images will be available.  Ubuntu does not support arm6, as a result this image will no longer be compatible with Raspberry Pi 1 and Raspberry Pi Zero W devices. The project will continue to build images for amd64, aarch64 and arm7 (Raspberry Pi 2 or later).

Currently the `latest` tag is an **Alpine Linux** based image, this will change to an **Ubuntu Linux** based image. For most users this change should be transparent.

Additionally `AVAHI` will be enabled by default in all images, this can be disabled with `-e ENABLE_AVAHI=0`.

If you have any custom start up scripts that use `npm` or `apk`, these will need to be updated to work with `pnpm` and `apt` respectively.

**Comment by oznu** [comment]
Additionally, the option to run **without** the Homebridge UI will be removed.

**Comment by danieletorelli** [comment]
Hello, first of all I'd like to thank you for the great job you're doing. Much appreciated.

May I ask you what are the reasons behind this choice?

**Comment by oznu** [comment]
When this image was first created, the Debian base images were much more bloated.

I've also had to manually compile Node.js for Alpine/muslibc as there was not a reliable source of binaries or base images that were kept up-to-date (even the offical node:alpine base images were often broken for arm builds).

Moving everything to Ubuntu also allows the image to take advantage of the Homebridge Debian package, which reduces the complexity of this image.

https://github.com/homebridge/homebridge-apt-pkg

**Comment by danieletorelli** [comment]
> When this image was first created, the Debian base images were much more bloated.
> 
> 
> 
> I've also been having to manually compile Node.js for Alpine/muslibc as there is not a reliable source of binaries or base images that are kept up-to-date (the offical node:alpine base images were often broken for arm builds).
> 
> 
> 
> Moving everything to Ubuntu also allows the image to take advantage of the Homebridge Debian package, which reduces the complexity of this image.
> 
> 
> 
> https://github.com/homebridge/homebridge-apt-pkg

That absolutely makes it a reasonable decision.

Thank you very much for the clarification 🙂

**Comment by oznu** [comment]
Thanks, if you want to test the next version, it's currently available under the `apt` tag.

It should be in an in-place upgrade for most people, but I'd do a backup first :)

**Comment by oznu** [comment]
Actually, disregard testing it at the moment. The UI needs some changes first.
