### ISSUE TITLE
homebridge-people not working. how 2 debug 

### ISSUE THREAD

**Issue by hackatonic** [oznu/docker-homebridge#44]
Hey there,
i am very satisfied, but homebridge people doesn't recognize any of my devices. Not with IP or Hostname, so i wanted to try do debug this but don't know how. Ping command in docker container is working and my devices can be pinged out of de container. 
I thing this must be a problem with this Docker Container becaus on my RasPi it worked formerly.

Thanks for any hint =)

**Comment by oznu** [comment]
I tested the [ping](https://www.npmjs.com/package/ping) library which the [homebridge-people](https://github.com/PeteLawrence/homebridge-people) plugin uses and it does work inside an alpine docker container.

Enabling [homebridge debug mode](https://github.com/nfarina/homebridge#plugin-development) might give you more insight into what's going on. This can be done by setting the `DEBUG` env var.

```
docker run --net=host -e "DEBUG=*" oznu/homebridge
```

Are you running this in docker on the raspberry pi as well?

**Comment by hackatonic** [comment]
oh i forgot to mention that i run it on my Synology ;) 
Now i run the docker existing container wir added env option DEBUG=* 
... but cant see anything that could help 

[2017-12-13 12:48:49] [People] Initializing People platform...
[2017-12-13 12:48:49] [People] Initializing platform accessory 'Nils iPhone1'...
[2017-12-13 12:48:49] [People] Initializing platform accessory 'Nils iPhone 2'...
[2017-12-13 12:48:49] [People] Initializing platform accessory 'Nils MBP'...
[2017-12-13 12:48:49] [People] Initializing platform accessory 'Nils MBP 2'...
[2017-12-13 12:48:49] [People] Initializing platform accessory 'Anyone'...
[2017-12-13 12:48:49] [People] WebHook: Started server on port '51828'.

but don't recognize my Devices. 

Sadly i don't know how to debug or to trigger recognition

and i have to add this to startup.sh otherwise it won't start a second time ... 
rm /homebridge/accessories/cachedAccessories

no on my RasPi i installed Node etc by myself not in docker so i guess it must be s.th. with the docker container or my Synology. That't because i opened an issue here. 
P.S.  i'm not sure if the people version is the same i used on my RasPi.

**Comment by idominik94** [comment]
> oh i forgot to mention that i run it on my Synology ;)
> Now i run the docker existing container wir added env option DEBUG=*
> ... but cant see anything that could help
> 
> [2017-12-13 12:48:49] [People] Initializing People platform...
> [2017-12-13 12:48:49] [People] Initializing platform accessory 'Nils iPhone1'...
> [2017-12-13 12:48:49] [People] Initializing platform accessory 'Nils iPhone 2'...
> [2017-12-13 12:48:49] [People] Initializing platform accessory 'Nils MBP'...
> [2017-12-13 12:48:49] [People] Initializing platform accessory 'Nils MBP 2'...
> [2017-12-13 12:48:49] [People] Initializing platform accessory 'Anyone'...
> [2017-12-13 12:48:49] [People] WebHook: Started server on port '51828'.
> 
> but don't recognize my Devices.
> 
> Sadly i don't know how to debug or to trigger recognition
> 
> and i have to add this to startup.sh otherwise it won't start a second time ...
> rm /homebridge/accessories/cachedAccessories
> 
> no on my RasPi i installed Node etc by myself not in docker so i guess it must be s.th. with the docker container or my Synology. That't because i opened an issue here.
> P.S. i'm not sure if the people version is the same i used on my RasPi.
> 
> I also disabled IPv6 on my router to prevent any bugs

Do you got it working?

**Comment by BitTourette** [comment]
@idominik94 nope. i have no all Home Automations on a separate Raspberry
