### ISSUE TITLE
Notice: Removing various startup options

### ISSUE THREAD

**Issue by oznu** [oznu/docker-homebridge#440]
From the next release of this image, the following startup options will be **removed**:

* `PACKAGES` - use the startup.sh script instead, you can edit this in the Homebridge UI
* `HOMEBRIDGE_CONFIG_UI` - the UI is now required to use this container and will always be enabled
* `HOMEBRIDGE_CONFIG_UI_PORT` - set the UI port via the config.json directly
* `HOMEBRIDGE_INIT_PORT` - set the homebridge port in the config.json directly
* `TERMINATE_ON_ERROR` - no longer required, `hb-service` will take care of managing the homebridge process
* `HOMEBRIDGE_INSECURE` - you can set this option via the Homebridge UI
* `HOMEBRIDGE_DEBUG` - you can set this option via the Homebridge UI
* `PUID` - no longer available
* `PGID` - no longer available

Additionally, the `crontab` service will no longer run inside the container.

**Comment by davidzyx** [comment]
Is there a particular reason behind the removal of `PUID`, `PGID` and instead replacing them with [`1000`](https://github.com/oznu/docker-homebridge/commit/010799ad21e3f18a597165ff3d45c7fbac734704#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R35)?

**Comment by crahan** [comment]
I just noticed that the `homebridge` user (`UID` 1000) has now been removed as well in the most recent `Dockerfile` version and everything now runs as `root`. I'm curious as to the reason for this decision as it impacts files created on the host OS through the volume mounts.
