### ISSUE TITLE
Notice: Replacing `npm` with `pnpm`.

### ISSUE THREAD

**Issue by oznu** [oznu/docker-homebridge#442]
From the next release of this image, plugins will be installed via `pnpm` instead of `npm` to move thing inline with other "new" Homebridge installs.

The next release will be based on the Homebridge Debian/Ubuntu APT package which uses `pnpm`.

Using `pnpm` instead `npm` speeds things up considerably; as an example, when updating the Homebridge UI on a Raspberry Pi Zero W; using `npm` takes 5-10 minutes, while `pnpm` takes about 45 seconds. 

If your `startup.sh` script contains `npm` commands, these should be removed or replaced. Homebridge will no longer load plugins installed globally using the `npm install -g` command.

When upgrading to the next image, your `node_modules` folder will be deleted and all your plugins re-installed as per the contents of the `package.json` file using `pnpm`.

**Comment by jun6lee** [comment]
Same issue with QNAP. There's no pnpm available locally or via Entware for us.
