### ISSUE TITLE
Update Node 15.5.1 - config-ui-x 4. 46.0

### ISSUE THREAD

**Issue by Spy-1** [oznu/docker-homebridge#447]
### Feature Description

Please update docker files with Node 15.5.1 - config-ui-x 4. 46.0

**Comment by oznu** [comment]
This is currently in the pre-release tag here:

https://github.com/oznu/docker-homebridge/releases/tag/2022-06-02

**Comment by Spy-1** [comment]
i´m using the homebridge:ubuntu container.
When will the homebridge:latest will be changed  from Alpine to ubuntu?

**Comment by oznu** [comment]
When enough people have tested 2022-06-02 I'll push it to latest/ubuntu. This image has a lot of users and it's a lot of changes so I'm playing it safe.

**Comment by Spy-1** [comment]
How to test without changing my running configuration with homebridge:ubuntu.
Within Synology Docker i don´t see the prerelease Image?!

**Comment by oznu** [comment]
The changes have been pushed to latest/ubuntu. See release notes for depreciated tags.
