### ISSUE TITLE
homebridge-config-ui not work

### ISSUE THREAD

**Issue by cuihaijun** [oznu/docker-homebridge#45]
docker exec Homebridge yarn add homebridge-config-ui
I installed this plugin, but the path in the plugin is/usr/lib/node_modules, not compatible with your Homebridge, what is the solution?

**Comment by oznu** [comment]
I was testing this personally recently actually, it's a bit complicated to get even half working as the plugin makes a lot of assumptions.

### If you want to hack around:

I have got this sort of working using this fork that has many improvements, including the ability to specify where the homebridge plugins are installed

https://github.com/shidevil/homebridge-config-ui

Remove existing plugin:

```
yarn remove homebridge-config-ui
```

Install:

```
yarn add https://github.com/shidevil/homebridge-config-ui.git
```

Update config.json:

```js
"platforms": [
    {
        "name": "Config"
        "platform": "config",
        "port": 8080,
        "base": "/homebridge/node_modules",
        "temp": "/tmp/fake-temp",
        "log": "/homebridge/config.json",
        "restart": "pkill homebridge",
    }
]
```

Add this to the bottom of the [`startup.sh`](https://github.com/oznu/docker-homebridge/blob/master/root/defaults/startup.sh) file which is located in your mounted `/homebridge` volume:

```bash
# Create a file which homebridge-config-ui can use to report a fake cpu temp
echo "0" > /tmp/fake-temp

# Stop the container terminating when homebridge is restarted by homebridge-config-ui
echo "#!/bin/sh" > /etc/services.d/homebridge/finish

# link the global homebridge install to the local homebridge folder
( sleep 30 ; [ -L /homebridge/node_modules/homebridge ] || ln -s /usr/local/share/.config/yarn/global/node_modules/homebridge /homebridge/node_modules/homebridge ; echo "INFO :: homebridge-config-ui ready!") &
```

### What still does not work:

* Installing plugins - it just doesn't.
* Viewing the log - the logs are sent to `/dev/stdout`, not a file, so the container can't read its own log history.

### Next steps...

This plugin looks like it could be quite good and might help my Synology users who don't like using the command line to do things like adding plugins and editing config. I might fork shidevil's fork and make a few minor changes that will make it work properly.

**Comment by cuihaijun** [comment]
I was using Synology Docker, did not find this
/usr/local/share/.config/yarn/global/node_modules/homebridge
my Homebridge is configured like this
docker run-d--name=homebridge--net=host-e dsm_hostname=diskstation-v/volume2/docker/homebridge:/homebridge:rw-v Etc/localtime:/etc/localtime:ro Oznu/homebridge:latest
Can you help me again?

**Comment by oznu** [comment]
@cuihaijun see https://github.com/oznu/homebridge-config-ui-x

Get the latest version of oznu/homebridge from the docker registry. Delete your existing container and recreate it with the freshly downloaded one.

```
docker rm -f homebridge
docker pull oznu/homebridge:latest
docker run [ your settings here ] oznu/homebridge:latest
```

Install:

```
docker exec homebridge yarn add homebridge-config-ui-x
```

Config:

```js
"platforms": [
    {
        "platform": "config",
        "name": "Config",
        "port": 8080,
        "log": "/homebridge/logs/homebridge.log"
    }
]
```

✅  Restarting Homebridge 
✅  Installing and removing plugins 
✅  Updating plugins 
✅  Updating to a newer version of Homebridge
✅  Edit config.json using the advanced config editor
✅  Viewing logs

**Comment by cuihaijun** [comment]
Thank you very much, install successfully according to your steps
