### ISSUE TITLE
What is env HOMEBRIDGE_CONFIG_UI supposed to do?

### ISSUE THREAD

**Issue by benzman81** [oznu/docker-homebridge#454]
### Current Situation

I tried ti set HOMEBRIDGE_CONFIG_UI=0 as I thought it would deactivate the config ui, but it doesn't. What's the variable for?

### Docker Config

```yml
not relevant
```

### Host Operating System

Synology DSM

### Host Architecture

x86_64 / amd64

**Comment by oznu** [comment]
It does nothing. It was removed in a recent release.

https://github.com/oznu/docker-homebridge/issues/440

**Comment by benzman81** [comment]
Thanks you for clarifying.
