### ISSUE TITLE
Do not start avahi-daemon unless Avahi is the mDNS advertiser.

### ISSUE THREAD

**Issue by traviswparker** [oznu/docker-homebridge#457]
### Feature Description

Would it be possible to disable avahi-daemon unless it is selected as the advertiser? I'm running docker-homebridge on a NAS that also runs Avahi. When avahi-daemon starts in the container, it causes the NAS's advertised services to disappear until avahi-daemon in the container is disabled.

**Comment by oznu** [comment]
Other plugins and services make use of avahi, not just the homebridge advertiser. You can disable it via `-e ENABLE_AVAHI=0`
