### ISSUE TITLE
ffmpeg-for-homebridge missing on updates and fresh installs

### ISSUE THREAD

**Issue by mav808** [oznu/docker-homebridge#459]
### Describe The Bug

Both on updating from previous version and a completely fresh install the ffmpeg-for-homebridge module is missing; it is not being installed.  Manually installing by running `npm i ffmpeg-for-homebridge` from inside the container fixes the issue.

The Dockerfile has instructions for installing the module so I'm assuming it was not removed deliberately and it not being installed is a bug.

### Docker Config

```yml
Default
```

### Logs

```text
[6/24/2022, 11:19:07 PM] [homebridge-unifi-protect] Unable to find FFmpeg at: '/homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg'. Please make sure that you have a working version of FFmpeg installed.
```

### Host Operating System

Synology DSM 7

### Host Architecture

x86_64 / amd64

**Comment by oznu** [comment]
Uninstalling / reinstalling the plugin will sort it out.
