### ISSUE TITLE
Can not find the config.json on WD PR4100

### ISSUE THREAD

**Issue by kaiatkins** [oznu/docker-homebridge#46]
I have installed in docker on my WD PR4100 and it shows up on my iPhone and I can add the home bridge just can not see the plugins and noe sure how to get to the config.json and also how to verify the plugins

I installed 

docker create --name=homebridge --net=host -e PGID=1001 -e PUID=1001 --restart=always -v /mnt/HD/HD_a2/docker-config/homebridge-config:/config -e TZ=Asia/Phnom_Penh oznu/homebridge

then added plugin

docker exec homebridge yarn add homebridge-tado-ac

but get this result

root@NAS config # docker exec homebridge yarn add homebridge-tado-ac
yarn add v1.3.2
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning homebridge-config-ui-x@1.1.10: The engine "homebridge" appears to be invalid.
warning homebridge-dummy@0.2.0: The engine "homebridge" appears to be invalid.
warning homebridge-tado-ac@2.2.10: The engine "homebridge" appears to be invalid.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ homebridge-tado-ac@2.2.10
warning No license field
Done in 4.80s.

also when adding the config ui

docker exec homebridge yarn add homebridge-config-ui-x

yarn add v1.3.2
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
warning homebridge-config-ui-x > read-last-lines > fs-promise@0.5.0: Use mz or fs-extra^3.0 with Promise Support
[2/4] Fetching packages...
warning homebridge-dummy@0.2.0: The engine "homebridge" appears to be invalid.
warning homebridge-tado-ac@2.2.8: The engine "homebridge" appears to be invalid.
warning homebridge-config-ui-x@1.1.10: The engine "homebridge" appears to be invalid.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 143 new dependencies.
├─ abbrev@1.1.1
├─ accepts@1.3.4
├─ ajv@5.5.2
├─ any-promise@1.3.0
├─ array-flatten@1.1.1
├─ asn1@0.2.3
├─ assert-plus@1.0.0
├─ async-limiter@1.0.0
├─ asynckit@0.4.0
├─ aws-sign2@0.7.0
├─ aws4@1.6.0
├─ balanced-match@1.0.0
├─ bcrypt-pbkdf@1.0.1
├─ bluebird@3.5.1
├─ body-parser@1.18.2
├─ boom@4.3.1
├─ brace-expansion@1.1.8
├─ bytes@3.0.0
├─ caseless@0.12.0
├─ co@4.6.0
├─ combined-stream@1.0.5
├─ commander@2.12.2
├─ concat-map@0.0.1
├─ content-disposition@0.5.2
├─ content-type@1.0.4
├─ cookie-parser@1.4.3
├─ cookie-signature@1.0.6
├─ cookie@0.3.1
├─ core-util-is@1.0.2
├─ crc@3.4.4
├─ cryptiles@3.1.2
├─ dashdash@1.14.1
├─ debug@2.6.9
├─ delayed-stream@1.0.0
├─ depd@1.1.1
├─ destroy@1.0.4
├─ ecc-jsbn@0.1.1
├─ ee-first@1.1.1
├─ encodeurl@1.0.1
├─ escape-html@1.0.3
├─ etag@1.8.1
├─ express-session@1.15.6
├─ express@4.16.2
├─ extend@3.0.1
├─ extsprintf@1.3.0
├─ fast-deep-equal@1.0.0
├─ fast-json-stable-stringify@2.0.0
├─ finalhandler@1.1.0
├─ forever-agent@0.6.1
├─ form-data@2.3.1
├─ forwarded@0.1.2
├─ fresh@0.5.2
├─ fs-extra@0.26.7
├─ fs-promise@0.5.0
├─ fs.realpath@1.0.0
├─ fs@0.0.1-security
├─ getpass@0.1.7
├─ glob@7.1.2
├─ graceful-fs@4.1.11
├─ har-schema@2.0.0
├─ har-validator@5.0.3
├─ hawk@6.0.2
├─ hoek@4.2.0
├─ hogan-express@0.5.2
├─ hogan.js@3.0.2
├─ homebridge-config-ui-x@1.1.10
├─ http-errors@1.6.2
├─ http-signature@1.2.0
├─ iconv-lite@0.4.19
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ ipaddr.js@1.5.2
├─ is-typedarray@1.0.0
├─ isstream@0.1.2
├─ jsbn@0.1.1
├─ json-schema-traverse@0.3.1
├─ json-schema@0.2.3
├─ json-stringify-safe@5.0.1
├─ jsonfile@2.4.0
├─ jsprim@1.4.1
├─ klaw@1.3.1
├─ media-typer@0.3.0
├─ merge-descriptors@1.0.1
├─ methods@1.1.2
├─ mime-db@1.30.0
├─ mime-types@2.1.17
├─ mime@1.4.1
├─ minimatch@3.0.4
├─ ms@2.0.0
├─ mz@2.7.0
├─ negotiator@0.6.1
├─ nopt@1.0.10
├─ oauth-sign@0.8.2
├─ object-assign@4.1.1
├─ on-finished@2.3.0
├─ on-headers@1.0.1
├─ once@1.4.0
├─ parseurl@1.3.2
├─ passport-local@1.0.0
├─ passport-strategy@1.0.0
├─ passport@0.4.0
├─ path-is-absolute@1.0.1
├─ path-to-regexp@0.1.7
├─ pause@0.0.1
├─ performance-now@2.1.0
├─ proxy-addr@2.0.2
├─ punycode@1.4.1
├─ qr-image@3.2.0
├─ qs@6.5.1
├─ random-bytes@1.0.0
├─ range-parser@1.2.0
├─ raw-body@2.3.2
├─ read-last-lines@1.3.0
├─ request-promise-core@1.1.1
├─ request-promise@4.2.2
├─ request@2.83.0
├─ rimraf@2.6.2
├─ safe-buffer@5.1.1
├─ semver@5.4.1
├─ send@0.16.1
├─ serve-static@1.13.1
├─ setprototypeof@1.1.0
├─ sntp@2.1.0
├─ sshpk@1.13.1
├─ statuses@1.3.1
├─ stealthy-require@1.1.1
├─ stringstream@0.0.5
├─ tail@1.2.3
├─ thenify-all@1.6.0
├─ thenify@3.3.0
├─ tough-cookie@2.3.3
├─ tunnel-agent@0.6.0
├─ tweetnacl@0.14.5
├─ type-is@1.6.15
├─ uid-safe@2.1.5
├─ ultron@1.1.1
├─ unpipe@1.0.0
├─ utils-merge@1.0.1
├─ uuid@3.1.0
├─ vary@1.1.2
├─ verror@1.10.0
├─ wrappy@1.0.2
└─ ws@3.3.3
warning No license field
Done in 17.76s.

**Comment by oznu** [comment]
> docker create --name=homebridge --net=host -e PGID=1001 -e PUID=1001 --restart=always -v /mnt/HD/HD_a2/docker-config/homebridge-config:/config -e TZ=Asia/Phnom_Penh oznu/homebridge

The containr volume mount should be `/homebridge` rather than `/config`. The `config.json` and all other required files will be created the first time you launch the container.

**Comment by kaiatkins** [comment]
It worked, thank you so much!
