### ISSUE TITLE
Verified By Homebridge

### ISSUE THREAD

**Issue by rbronco21** [oznu/docker-homebridge#465]
### Current Situation

I haven't been able to get your plugin installed, but it should probably replace the currently broken verified plugin. I don't know if I can go through the process for you, but I'd be willing to if you and Homebridge are ok with that.

https://github.com/homebridge/verified

### Docker Config

```yml
N/A
```

### Host Operating System

Unraid

### Host Architecture

x86_64 / amd64

**Comment by oznu** [comment]
This is the Homebridge Docker image project; not a plugin.
