### ISSUE TITLE
Restore From Backup - Devices: No Response

### ISSUE THREAD

**Issue by VeniceNerd** [oznu/docker-homebridge#466]
### Current Situation

I had oznu/hombridge up and running on my raspberry pi for several years. I recently build an Unraid server and wanted to move hombridge on there. I installed the container and imported the backup I made on the raspberry pi install. Everything looks fine in the logs (all devices are found), however, in HomeKit all of the devices show "no response".

Is it not possible to move from one machine to another? I am using  a different webUI port on my unraid, though. Not sure if that is the problem?

### Docker Config

```yml
Installed from the Unraid app store. homebridge
geoff.gibby's Repository
```

### Host Operating System

Unraid

### Host Architecture

x86_64 / amd64

**Comment by VeniceNerd** [comment]
I THINK I may have solved the issue by setting the network mode to "host". Is it not possible to host Homebridge in a custom docker network?

**Comment by oznu** [comment]
`--net=host` / `network_mode: host` is required.
