### ISSUE TITLE
Samba?

### ISSUE THREAD

**Issue by j-burton** [oznu/docker-homebridge#473]
### Feature Description

I've installed Homebridge WOL,
during my setup I have tried to go to the console and run the command
net rpc shutdown -f -t 0 --ipaddress 10.0.10.13 --user user%passwword
getting a result of
bash: net: command not found

I'm not sure what I'm doing, but it seems I need to install Samba?

**Comment by clickbg** [comment]
Here is what I use to install the Samba RPC tools - set this in your startup script:

`apt-get update && apt-get -y install samba-common-bin wakeonlan `

I also prefer the wakeonlan utility rather than the plugin method of WoL but you can remove it if you don't need it.
