### ISSUE TITLE
Enable resolved support from V1.6.0

### ISSUE THREAD

**Issue by Fish2** [oznu/docker-homebridge#481]
### Feature Description

Enable suport for systemd-resolved as in v1.6.0

followed setup guide from homebridge but still get 

`[Homebridge 04B6] The selected advertiser, "resolved", isn't available on this platform. Reverting to "bonjour-hap"`

**Comment by oznu** [comment]
The docker container does not run systemd-resolved; as such this option won't be available when running Docker.

**Comment by Fish2** [comment]
@oznu would this be something that could be added to this image ?

**Comment by oznu** [comment]
No, systemd inside Docker is not really feasible

**Comment by Fish2** [comment]
Ok thanks for getting back that’s a shame
