### ISSUE TITLE
Change wiki page for TrueNAS to avoid disabling mDNS

### ISSUE THREAD

**Issue by xurtis** [oznu/docker-homebridge#494]
### Describe The Bug

I've managed to work around this by setting a static IP on a dedicated host interface, selecting that interface, and switching to Avahi in the settings. Not sure how much of this entire setup is required.

### Docker Config

```yml
/init
```

### Host Operating System

Other (specify in description)

### Host Architecture

x86_64 / amd64

**Comment by Nusephived** [comment]
Hello @xurtis, I'm trying to do the same thing, can you to back up your words with screenshots please?
So if I understand, we need multiple physical interfaces? One for TrueNAS and another for Homebridge?

**Comment by DragonWoot** [comment]
Yeah I can't seem to get this working. The NIC I try to passthrough doesn't even come up on the attached switch when attached to the docker. If I let it pull from DHCP it works fine, but attaching it to the docker instance stays dark...
