### ISSUE TITLE
TrueNAS Scale documentation improvement

### ISSUE THREAD

**Issue by half2me** [oznu/docker-homebridge#522]
### Describe The Bug

I was following along with the guide here: https://github.com/homebridge/docker-homebridge/wiki/Homebridge-on-TrueNAS-Scale

I have a few suggestions to make this guide better.
First of all the guide offers a hacky way to get things to work by creating a 2nd NIC, then adding a startup script to remove the default one, including having to use enable `CAP_NET_ADMIN`.

The biggest problem with this approach is that homebridge is not able to communicate with other services running in the kubernetes cluster. In my particular case I use zigbee2mqtt, and I have mosquitto running in the cluster, but homebridge is unable to access it.

Instead, I recommend to just leave both interfaces active, make sure to enable Kubernetes DNS instead of ignoring it, and simply telling homebridge to only advertise on `net1` and not `eth0`. You also need to pick an mDNS Advertiser other than bonjour HAP, such as avahi which can actually support specifying the interface to advertise on instead of just automatically picking the first one it sees.

This way homebridge is properly advertised on the secondary NIC, but you also get the first NIC to access k8s, and it is setup with your default gw etc.

This is how I have it setup and its working very well.

### Docker Config

```yml
n/a
```

### Logs

```text
n/a
```

### Host Operating System

Other (specify in description)

### Host Architecture

x86_64 / amd64

**Comment by half2me** [comment]
ping

**Comment by maximvoven** [comment]
I second this change recommendation. Also I discovered this issue due to the startup script changes failing to disable eth0 even though instructions were followed to the letter. This led me to be unable to connect iOS device to the bridge.

Truenas: TrueNAS-SCALE-23.10.0.1
Homebridge: 2308.0.1

The configurations that @half2me  apparently changed are in the photo bellow.
![image](https://github.com/homebridge/docker-homebridge/assets/33429176/fcaf6cb8-d3cf-4974-87e9-1afffcadf13a)

I think we should make a pull request to replace Step 3. Replacing "We must remove that interface on container startup, through Homebridge's startup script configuration (this is why we need the CAP_NET_ADMIN capability)." with "We must configure the advertising interface to to be net1 and change the mDNS advertiser to Avahi to honor the configuration override" The remainder of the instructions should be modified to include the above image as well as to direct the user to change the settings using the gui.

**Comment by half2me** [comment]
Since I wrote this, I have things running perfectly with this setup at home.

**Comment by Suncuss** [comment]
> I second this change recommendation. Also I discovered this issue due to the startup script changes failing to disable eth0 even though instructions were followed to the letter. This led me to be unable to connect iOS device to the bridge.
> 
> Truenas: TrueNAS-SCALE-23.10.0.1 Homebridge: 2308.0.1
> 
> The configurations that @half2me apparently changed are in the photo bellow. ![image](https://private-user-images.githubusercontent.com/33429176/291115557-fcaf6cb8-d3cf-4974-87e9-1afffcadf13a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTgwMjgsIm5iZiI6MTcwMzIxNzcyOCwicGF0aCI6Ii8zMzQyOTE3Ni8yOTExMTU1NTctZmNhZjZjYjgtZDNjZi00OTc0LTg3ZTktMWFmZmZjYWRmMTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNTU2MzNmYTdkMDY0Yjk3ZGZmODE4NTMzZWQyOTJlYWMxN2E4YTZlZDI5Njc3MmU2Y2Y1ZTU4NDk2YTgzZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.twpE2T8ZZ1gcYAAKATpJTM3aGMmQ0482SAOUwaZP28U)
> 
> I think we should make a pull request to replace Step 3. Replacing "We must remove that interface on container startup, through Homebridge's startup script configuration (this is why we need the CAP_NET_ADMIN capability)." with "We must configure the advertising interface to to be net1 and change the mDNS advertiser to Avahi to honor the configuration override" The remainder of the instructions should be modified to include the above image as well as to direct the user to change the settings using the gui.

Take a look at the log, in my case, i found that it try to run those command, but the operation failed becuase of permission, it shows in the logs. I change the Capability to `NET_ADMIN`, that did the work. Now i successfully added the hub to homeKit, but none of the accesories are shwoing up even though i can see and control themin the homebridge WebUI.

**Comment by half2me** [comment]
Is there anything I can do to add this?

**Comment by NorthernMan54** [comment]
@half2me The wiki pages should editable by everyone. If not pls let me know

**Comment by donavanbecker** [comment]
@half2me Feel free to update the wiki you are wanting to change and let us know when you are done.

**Comment by half2me** [comment]
> @half2me Feel free to update the wiki you are wanting to change and let us know when you are done.

thanks @donavanbecker, I've made the changes to the wiki.
