### ISSUE TITLE
 1.7.0 requires Node.js v18.15.0 or later but Docker image has Node.js v18.13.0

### ISSUE THREAD

**Issue by aberkvam** [oznu/docker-homebridge#524]
### Analysis

I get the following message when trying to update to the recently-released Homebridge 1.7.0:

Homebridge v1.7.0 requires Node.js v18.15.0 or later. You are currently running Node.js v18.13.0.

The "How To Update Node.js" wiki says "Users running in Docker should update Node.js by pulling down the latest version of the Homebridge Docker Image."  But I have the latest image, which is 10 months old.  https://hub.docker.com/r/oznu/homebridge/

### Expected Behavior

Docker image would have Node.js v18.15.0 or later prepackaged

### Steps To Reproduce

Try updating to Homebridge 1.7.0 from the official Docker container.

### Logs

```markdown
N/A
```

### Configuration

```json
N/A
```

### Environment

- OS: DSM 6
- Software: Homebridge v1.6.1
- Node: v18.13.0
- npm: 8.19.3

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

oznu/homebridge            latest              4602d8486a4c        9 months ago        913MB

**Comment by ebaauw** [comment]
They moved to https://hub.docker.com/r/homebridge/homebridge, but I don’t know what version of NodeJS they use there.

**Comment by NorthernMan54** [comment]
FYI - docker-homerbidge uses the Homebridge APT package internally, which includes NodeJS v18.18.2

**Comment by NorthernMan54** [comment]
I also mentioned the docker image location move on the `How to Update NodeJS` page.

**Comment by aberkvam** [comment]
Thanks for the hint about the oznu-homebridge -> homebridge-homebridge move and the updating of the documentation.  (It would be nice if there was a depreciation notice at https://hub.docker.com/r/oznu/homebridge/ too...)

That led me down another rabbit hole because the version of Docker that comes with Synology DSM 6 is too ancient to support the latest homebridge-homebridge image format.  Updating to DSM 7 (a long-overdue headache) got me a newer Docker that could load the homebridge-homebridge image, which could then update to homebridge 1.7.0.  Problem(s) solved.  Thanks.
