### ISSUE TITLE
GHCR mirror

### ISSUE THREAD

**Issue by moenzuel** [oznu/docker-homebridge#527]
### Describe The Bug

I believe with the move of the repo the ghcr mirror broke as the oznu version has not seen an update and there are no packages here.

### Docker Config

```yml
n/a
```

### Logs

```text
n/a
```

### Host Operating System

Raspberry Pi OS - Latest

### Host Architecture

x86_64 / amd64

**Comment by NorthernMan54** [comment]
Please check your location for the GHCR Mirror, we had moved the dockers images into the homebridge domain, and the address for GHCR is

```
docker pull ghcr.io/homebridge/homebridge:latest
```

**Comment by caius** [comment]
One thing that caught me out is the published tags have massively been cut down now it's moved. eg, `oznu/homebridge:2023-01-08` doesn't become `homebridge/homebridge:2023-01-08`, it seems to be `homebridge/homebridge:latest` now and no date-based images to pin to.

**Comment by NorthernMan54** [comment]
We just published a fix for this, so this can be closed
