### ISSUE TITLE
Node.js Upgrade

### ISSUE THREAD

**Issue by Agosh13** [oznu/docker-homebridge#528]
### Feature Description

Upgrade Ubuntu Node JS to 20, some plugin like homebridge require it:

> The plugin "homebridge-ewelink" requires Node.js version of ^18.18.2 || ^20.8.1 which does not satisfy the current Node.js version of v18.13.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF

**Comment by NorthernMan54** [comment]
In the homebridge-apt-pkg, we are holding the NodeJS version to 18.x until spring 2024.  This is to allow users with an older os installation ( Buster or older ) to update their OS, prior to forcing the update to everyone.

**Comment by hjbugajski** [comment]
@Agosh13 if you switch your Docker image from `oznu/homebridge` to `homebridge/homebridge`, you'll be able to upgrade Homebridge plugins since that new image has a higher node version. [They recently changed the location.](https://github.com/homebridge/docker-homebridge#important-update)
