### ISSUE TITLE
Homebridge 1.7.0 not available on Dockerhub

### ISSUE THREAD

**Issue by LarsFronius** [oznu/docker-homebridge#529]
### Current Situation

It looks like the docker build for the 1.7.0 image failed. (for homebridge/homebridge:latest) As such the current homebridge version is not available on Dockerhub.

### Logs

https://github.com/homebridge/docker-homebridge/actions/runs/6755792330/job/18368367219

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

It looks like the image build failed and as such the 1.7.0 update wasn't pushed to dockerhub.

**Comment by NorthernMan54** [comment]
We updated the image earlier today

**Comment by LarsFronius** [comment]
I can confirm that I can now pull the new image! Thank you so much!

**Comment by LarsFronius** [comment]
Looks like the image (`homebridge/homebridge:latest`) was updated, but is still not containing homebridge 1.7.0.

**Comment by LarsFronius** [comment]
Looks like the new image version is now pulled, but it does not update a 1.6.1 installation on restart.

**Comment by LarsFronius** [comment]
Went into the data volume and updated the homebridge version in the `package.json` manually and restarted the image- which resulted in homebridge being updated. Is this something the image should take care of? I did not find an upgrade guide for the docker installation except for pulling a new image, so this additional step came as a surprise.

**Comment by andrasg** [comment]
> Went into the data volume and updated the homebridge version in the `package.json` manually and restarted the image- which resulted in homebridge being updated. Is this something the image should take care of? I did not find an upgrade guide for the docker installation except for pulling a new image, so this additional step came as a surprise.

I had the same, I had to set the version in the `dependencies` section of `package.json` to `^1.6.1`, and then deleted the `node_modules` folder to trigger a reinstall.

I would also think it would make sense to document this todo around the update process. My understanding is that on first install, when the `/homebridge` mount is empty, a new `package.json` will be generated with the following content:

```json
{
  "dependencies": {
    "homebridge": "1.7.0"
  }
}
```

As the version does not have the `^` in it, it will block further automatic updates.

How is this supposed to auto-update with a new version of the container image?
