### ISSUE TITLE
Docker hub url is incorrect

### ISSUE THREAD

**Issue by ifeign** [oznu/docker-homebridge#530]
### Feature Description

The url at the top of the repo needs to be updated to https://hub.docker.com/r/homebridge/homebridge/

**Comment by NorthernMan54** [comment]
Are you referring to this one?

![image](https://github.com/homebridge/docker-homebridge/assets/19808920/79771e50-b39e-4424-bfc2-3c1fe9b99983)

I updated it a few hours ago
