### ISSUE TITLE
[Regression] No versioned tags available

### ISSUE THREAD

**Issue by rafaelgaspar** [oznu/docker-homebridge#531]
### Describe The Bug

Previous issue: https://github.com/homebridge/docker-homebridge/issues/398

It seams we've lost versioned images after the migration to `homebridge/homebridge`.

Like was mentioned in the original ticket, it's not best practice to just have latest and don't have versioned image tags, it makes it really hard to reference images, detect new versions, etc.

### Host Operating System

Other (specify in description)

### Host Architecture

x86_64 / amd64

**Comment by NorthernMan54** [comment]
I went and took a look and can see that previously releases were tagged by date.  But looked at the publish script, and it appears to publish based on branch name [script](https://github.com/homebridge/docker-homebridge/blob/latest/.github/workflows/main.yml)

Any thoughts on tweaks to resolve this ?

**Comment by rafaelgaspar** [comment]
Sure, I can open a PR.

**Comment by NorthernMan54** [comment]
I just published this so it should be resolved and can be closed
