### ISSUE TITLE
AppleTV upgrade caused problems

### ISSUE THREAD

**Issue by MSDaytona** [oznu/docker-homebridge#54]
Yesterday evening I upgraded my AppleTV to the very latest iOS. Since then my Wemo devices which I am running under Homebridge are not responding anymore. Everything was working fine until the upgrade. Knowing that the AppleTV is the HomeKit hub......
Any ideas ?

**Comment by oznu** [comment]
Try deleting the `accessories` and `persist` folders in your `/homebridge` mount and make sure you're running the latest version of the Docker image.

**Comment by MSDaytona** [comment]
Sorry, doesn't work

**Comment by oznu** [comment]
I have upgraded my Apple TV to tvOS 11.2.5 (release 2018/01/23) and was not able to replicate this.

This issue might be better off posted in the main [Homebridge repo](https://github.com/nfarina/homebridge) since it's a Homebridge to HomeKit issue.

**Comment by MSDaytona** [comment]
Thanks for responding. I deleted everything related and started the set-up from scratch. Now it’s working like a charm.
Must have done something wrong originally. Sorry for having wasted your time
