### ISSUE TITLE
docker publish should has a version tag not just ubuntu

### ISSUE THREAD

**Issue by kis87988** [oznu/docker-homebridge#541]
### Describe The Bug

As title, I believe the docker image release should have a tag, otherwise you will have hard time to track what version install under the docker image in the future 

### Docker Config

```yml
N/A
```

### Host Operating System

Synology DSM 6

### Host Architecture

x86_64 / amd64

**Comment by NorthernMan54** [comment]
Humm, I think we are publishing tags ? - https://hub.docker.com/r/homebridge/homebridge/tags

**Comment by kis87988** [comment]
hmmm. Interesting, yesterday I checked the `latest` tag was 3 months ago. Today it becomes `2023-12-28` to match the `latest` tag. However, shouldn't we match the `homebridge` version number as tag?

**Comment by NorthernMan54** [comment]
The push today is a bit of a coincidence, as another collaborator made a change today that triggered the build script.

Are you sure the previous tag was 3 months ago, I thought it was Nov 28th ?  My last update

**Comment by donavanbecker** [comment]
> Today it becomes `2023-12-28` to match the `latest` tag. However, shouldn't we match the `homebridge` version number as tag?

There is more then just homebridge that is include in this docker image. so matching up with the homebridge version wouldn't make sense.

**Comment by kis87988** [comment]
check via `docker image` I did `docker pull homebridge/homebridge:latest` yesterday.
```
homebridge/homebridge              latest    6fe8959f69b5   4 weeks ago     966MB
```

**Comment by NorthernMan54** [comment]
Am thinking we can close this

**Comment by NorthernMan54** [comment]
Just published a formal refresh today, and noticed the tags not working as expected.  So needed to redo the publish.  @kis87988 You may have seen the same issue. Tks for reporting this
