### ISSUE TITLE
Is Docker-Hombridge a limited version of Homebridge, with which you cannot control a second Raspberry with a .sh command?

### ISSUE THREAD

**Issue by Hagit60** [oznu/docker-homebridge#556]
### Current Situation

.

### Docker Config

```yml
.
```

### Host Operating System

Raspberry Pi OS - Latest

### Host Architecture

x86_64 / amd64

**Comment by NorthernMan54** [comment]
Docker-homebridge is a full version of homebridge, bundled into a docker container.

**Comment by Hagit60** [comment]
NothernMan 54, thanks for your reply. I've tried several plugins to reach from Docker-homebridge a second Raspberry pi to execute an .sh command. With terminal . SH script commands on the first Rpi (with Docker-homebridge) the second Rpi listens. But commands from Docker-homebridge do not reach the second Rpi. Homebridge Ui logs write .SH script not found,  When created a new Docker-homebridge container included the mnt/shared .sh file Homebridge logs write file not found. An idea's?
