### ISSUE TITLE
Why docker?

### ISSUE THREAD

**Issue by VeniceNerd** [oznu/docker-homebridge#56]
Sorry I’m a n00b to the Pi! I currently have homebridge running on my Mac but want to try a Homebridge Pi Installation instead. I have two questions about docker-homebridge:

1) what’s the benefit of installing homebridge inside of docker instead of just installing it straight onto the Pi as described here: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

2) is this the same build as the “original” homebridge built? Once installed will an update always pull the latest homebridge data directly or will it first have to be integrated into this package again? I guess what I’m asking is this: if docker-homebridge is no longer maintend does that mean I won’t be getting any further homebridge updates?

Lastly I’m wondering if there any downsides to using homebridge inside of docker. 

Thanks so much! ;)

**Comment by oznu** [comment]
Thanks for your question.

I think most of this has been answered before here: https://github.com/oznu/docker-homebridge/issues/21

This image does use the same build as the "original" Homebridge, it's just Homebridge inside installed a Docker container. While I do publish updates each time a new version of Homebridge is released, the end-users can also update Homebridge themselves just by running the relevant `npm install -g` command.

> Lastly I’m wondering if there any downsides to using homebridge inside of docker.

When running on a Raspberry Pi I would not use Docker if a plugin I was using required access to the GPIO pins.

**Comment by VeniceNerd** [comment]
Great overview, thank you. I’m sure this will help new users understand the benefit of docker. I enjoy running multiple instances of homebridge on the same pi!
