### ISSUE TITLE
Unable to add to HomeKit

### ISSUE THREAD

**Issue by vascott1** [oznu/docker-homebridge#566]
### Current Situation

Just got a NAS that supports docker. It is UGreen. I installed the container and it is working well. My old homebridge pi is powered off. I restored a backup of that to this version. From the Web UI I can control all of my devices. After removing the old bridge from HomeKit I am trying to add the new one and consistently get "Accessory Not Found" 

I am new to Docker so am not sure what I would need to submit here for help. Sorry about that. I can say I took defaults all the way through and am set to Bridge for networking. When I go the Web UI for homebridge, I am using the "external" IP of the NAS. Same as I use for shares, etc and port is 46693.

I am sure this is something simple so forgive the docker newbie question.

Thanks!

### Docker Config

```yml
I am not sure how to find this information.
```

### Host Operating System

UGreen NAS running UGOS (it's new)

### Host Architecture

x86_64 / amd64

**Comment by NorthernMan54** [comment]
Do you have this flag set ? https://github.com/homebridge/docker-homebridge?tab=readme-ov-file#compatibility

**Comment by vascott1** [comment]
The solution was to put the container in “host” mode and not “bridge” I did that through the gui but might be the same thing. Got it working and it is great   
  

  
Thanks :)
  
  
  
  
  
  
  

  
  
>

**Comment by muffn** [comment]
> Do you have this flag set ? https://github.com/homebridge/docker-homebridge?tab=readme-ov-file#compatibility

I have the same Issue comming from TrueNAS, according to the [guide](https://github.com/homebridge/docker-homebridge/wiki/Homebridge-on-TrueNAS-Scale) it shouldn't be necessary to set the flag, did I miss something? I can't find a way to set the host mode in the TrueNAS UI. I did the other changes noted in there.
