### ISSUE TITLE
How to change timezone

### ISSUE THREAD

**Issue by VeniceNerd** [oznu/docker-homebridge#57]
Hey,

I have this up an running now but the timestamps in my logs are all incorrect. Do you know how to change the timezone of the docker image after install? I saw some instructions on how to set it during install but I'm unsure what SSH command to issue inside the docker image so that it will set the time zone to Los Angeles.

Thanks so much!

**Comment by oznu** [comment]
Timezones are set via the `TZ` env var.

https://github.com/oznu/docker-homebridge/blob/master/README.md#parameters

**Comment by VeniceNerd** [comment]
@oznu I found that page. Unfortunately, I couldn't figure out what exact command to type into ssh to change the timezone. This is my first time to raspberry and docker so I'm learning.

I already have both of my Homebridge instances up and running each in one separate docker image. So I'm trying to figure out the exact command I need to enter to just update the timezone but leave everything else the same.

Any other tips you may have for me? It's not that big of a deal I guess but it would be awesome to have the logs in the correct time.

Thanks!

**Comment by oznu** [comment]
Find your timezone code here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Then put it into your existing `docker-compose.yml` file like this:

```
version: '2'
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    environment:
      - TZ=Australia/Sydney
      - PGID=1000
      - PUID=1000
    volumes:
      - ./volumes/homebridge:/homebridge
```

_Don't copy the whole thing, just add the relevant`TZ` line to your working setup._

Finally, run `docker-compose up -d` again to apply the change.

**Comment by VeniceNerd** [comment]
Thank you for taken the time to explain all of this. Worked perfectly and I am slowly starting to understand how this works. Appreciate all of your help on these forums.

**Comment by Hochiss** [comment]
Pardon! could you tell me where's docker-compose.yml? 
I put the TZ parameter into the container homebridge's env variable, restart not working, 
BTW: I install it i Synology NAS, would be nice to TZ settings from system.

**Comment by oznu** [comment]
@Hochiss, make sure your timezone was exactly the same as one of the ones listed [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). If that does not work then you may need to recreate the container with the new variable (not just edit the existing containers environment); Synology allowing you to edit an existing containers environment is a bit of a strange thing in the Docker world.

[Homebridge SPK](https://github.com/oznu/homebridge-syno-spk#how-to-install) automatically sets the timezone correctly.

**Comment by Hochiss** [comment]
@oznu thanks for your fast response! It would be nice if you have told me where's the file with shh into NAS or login to docker ...
I am afraid it spk would remove my previous setups/plugins...

**Comment by oznu** [comment]
@Hochiss - there is no `docker-compose.yml` file if you set it up via the Synology DSM Docker interface.

**Comment by Hochiss** [comment]
in fact I just installed the spk and my preious setup all gone and Synology report homebridge started but http://mysynoNAS:8581/ is not accessible. 
how to debug? I saw the homebridge docker is running and can login...

**Comment by jocamero** [comment]
Having the same issue.  Have TZ set in container settings.  Running `date` via Docker Terminal  returns correct time.  Time is correct via `tail -f /homebridge/logs/homebridge.log` Logs in the Docker Log tab are still set to UTC.  Is this a Synology Docker issue?

**Comment by oznu** [comment]
@jocamero - yes, the additional timestamps displayed in the synology docker app aren't controlled by the TZ variable. If the time is correct in the `/homebridge/logs/homebridge.log` file and running the `date` command inside the docker container, then the `TZ` variable is doing its job.

**Comment by tablatronix** [comment]
Not working for me..
`    environment:
    - TZ=America/Chicago
`

Sytem Information
Timezone | GMT+0000

**Comment by tablatronix** [comment]
I cant get this to work..

```
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:no-avahi-arm32v6
    restart: unless-stopped
    environment:
    - TZ=America/Chicago
    - PGID=1000
```

Logs and systeminformation panel are UTC..

**Comment by rweckhoff** [comment]
oznu/homebridge - Docker Image | Docker Hub
<https://hub.docker.com/r/oznu/homebridge/#!>
