### ISSUE TITLE
Start new Homebridge v2 beta

### ISSUE THREAD

**Issue by benzman81** [oznu/docker-homebridge#571]
### Current Situation

Hi, currently I use Onzu/homebridge image and now want to test my plugins for homebridge v2. Since this is the new project for homebridge docker, I would like to know, what setting is needed to start the image using the new v2 beta?

### Docker Config

```yml
Not relevant for question
```

### Host Operating System

Synology DSM 7

### Host Architecture

x86_64 / amd64

**Comment by NorthernMan54** [comment]
The current docker image is 

<!DOCTYPE html>
Package | Version
-- | --
NodeJS | v20.17.0
Homebridge-Config-UI-X | 4.57.1
Homebridge | 1.8.4

You could just install another docker image, and then within the image update homebridge to 2.0
