### ISSUE TITLE
Push update to include ffmpeg-for-homebridge v2.1.2

### ISSUE THREAD

**Issue by n0rt0nthec4t** [oznu/docker-homebridge#572]
### Feature Description

Is it possible to push a new image update to include the version of ffmpeg-for-homebridge? This has been updated to include ffmpeg 6.1.2 and also compiled with libspeex

**Comment by NorthernMan54** [comment]
@NorthernMan54 Your quick, the latest was late yesterday......

<!DOCTYPE html>
Package | Version
-- | --
NodeJS | v20.17.0
Homebridge-Config-UI-X | 4.59.0
Homebridge | 1.8.4
ffmpeg-for-homebridge | v2.1.2

**Comment by n0rt0nthec4t** [comment]
Probably want to redo with the updated config.ui at 4.59.1

**Comment by n0rt0nthec4t** [comment]
Can we do another updated as ffmpeg-for-homebridge is now using ffmpeg v7

**Comment by NorthernMan54** [comment]
Just kicked it off, give it an hour or so

**Comment by n0rt0nthec4t** [comment]
> Just kicked it off, give it an hour or so

Thanks. Updated also needed I based image for homebridge-config-ui. Includes 4.60, current is 4.62

**Comment by NorthernMan54** [comment]
Build has started
