### ISSUE TITLE
Cant connect to homekit 

### ISSUE THREAD

**Issue by it-pappa** [oznu/docker-homebridge#573]
### Current Situation

Hi,
I am running homebridge on a container in RHEL9 using Podman. Can reach the web gui no problem and also added firewall rules for the ports (web gui and backend single connection port). Also tried this with firewall turned off. I can reach the homebridge with my iPhone and iPad, but when running the configuration it stops and gives me an error: Can not add, can’t reach. 

Any idea what is going on? I used the default compose configuration from git. 

### Logs

```markdown
No relevant log i can see
```

### Configuration

```json
Same as default compose file from git
```

### Environment

- OS: rhel9
- Software: podman
- Node:
- npm:

### Process Supervisor

hb-service

### Additional Context

I used podman compose to build the image.

**Comment by NorthernMan54** [comment]
HomeKit uses mDNS to communicate between homebridge and the Home app.  In order for mDNS to function correctly, your iPhone and Homebridge need to on the same local network, within the same network address space.

Check what IP Homebridge has in the UI, and compare it to the one on your iPhone, they should be the same network.

Also mDNS uses port 5353, ensure any local firewalls you have open this port as well.
