### ISSUE TITLE
Update base OS in docker image

### ISSUE THREAD

**Issue by n0rt0nthec4t** [oznu/docker-homebridge#575]
### Feature Description

Current image uses Ubuntu Jammy. Please update to at least noble or even better, Oracular based.

Additional, consider moving to a smaller image.. alpine or a nodejs one

**Comment by NorthernMan54** [comment]
In a few weeks will be refreshing to 24.04

I’m also looking for a simple method like dependabot to track and manage dependencies, do you know of any approach that might work?  Did this for the homebridge apt pkg - [build](https://github.com/homebridge/homebridge-apt-pkg/blob/latest/BUILD.md) to easy management

**Comment by n0rt0nthec4t** [comment]
No sure about using dependant (I've yet to set it up on my repos), but looks interesting. Whats your thoughts about changing to a smaller distro image for the base?

**Comment by NorthernMan54** [comment]
Today, it just works, so making a significant change sometimes causes grief for people ( and a lot of grumbling ), so I prefer to keep it straightforward

**Comment by n0rt0nthec4t** [comment]
anyway, submitted a pull request to update image to 24.04 LTS (noble), updated HB, ffmpeg and S6 stuff

Looks like needs a major update to the readme also  ?

**Comment by NorthernMan54** [comment]
That is in the backlog, especially with #570 

Do you want to tackle it ?

**Comment by jakepez** [comment]
I created an image using @n0rt0nthec4t 's pull request and have been running on 24.04 LTS and the updated components for 6 days without any issues. [homebridge-kasa-python](https://github.com/ZeliardM/homebridge-kasa-python) requires updated Python and works fine on this new image. I'm also running:

- Homebridge Nest
- Homebridge Alexa Smart Home
- Homebridge UniFi SmartPower Plugin

**Comment by n0rt0nthec4t** [comment]
Been testing on my own developed plugin, Homebridge Nest Accfactory since submitted the PR and not seen issues. As mentioned in teh PR, if worried, setup a test tag on docker for wider testing

**Comment by NorthernMan54** [comment]
@n0rt0nthec4t This is now published -
![image](https://github.com/user-attachments/assets/51237656-5b1e-4452-9af6-cbee30422562)

Tks for your assistance
