### ISSUE TITLE
Invalid URL in Release notification

### ISSUE THREAD

**Issue by justjam2013** [oznu/docker-homebridge#578]
### Describe The Bug

The `Success: Homebridge Docker Release` link published to channel `hb-docker` in Discord is incorrect.

Current link is:
```
https://github.com/homebridge/homebridge-docker/releases/tag/2024-12-11
```
Should be:
```
https://github.com/homebridge/docker-homebridge/releases/tag/2024-12-11
```

This URL should be corrected:
https://github.com/homebridge/docker-homebridge/blob/67d821f0ab88b31970a27f1c348689b7f52b26b7/.github/workflows/main.yml#L142

![Screenshot 2024-12-11 at 8 22 02 PM](https://github.com/user-attachments/assets/a58921e7-8357-4e12-9ebb-d5d3c4c33b49)

### Docker Config

```yml
N/A
```

### Host Operating System

Other (specify in description)

### Host Architecture

x86_64 / amd64

**Comment by NorthernMan54** [comment]
Wow, that has been there for years and no one noticed

**Comment by NorthernMan54** [comment]
s/b fix with the next release
