### ISSUE TITLE
Host Name Conflict 

### ISSUE THREAD

**Issue by Duggy252** [oznu/docker-homebridge#59]
Hi 

Im totally new to using home bridge. I followed the guide to install it onto my Synology ds916+ so I can connect my nest thermostat to HomeKit. 

For some reason it seems I get an error host name conflict. It keeps scrolling Homebridge-XX... forever. How can I fix this?. 

Thanks

<img width="674" alt="screen shot 2018-01-28 at 16 11 04" src="https://user-images.githubusercontent.com/35896555/35484295-00517f32-0446-11e8-9b08-8d14f3a07423.png">

**Comment by oznu** [comment]
Hi @Duggy252,

Please see existing issue - https://github.com/oznu/docker-homebridge/issues/35

It seems hit and miss as to whether or not it will work. [This comment](https://github.com/oznu/docker-homebridge/issues/35#issuecomment-361062561) made a few hours ago sounds like it could be the solution.

**Comment by Duggy252** [comment]
Hi 

Thanks for the help, I already seem to have the most unto date version of docker, so Im no further forwards. Anything else? . 
Thanks
