### ISSUE TITLE
Can't pair homebridge with iOS11

### ISSUE THREAD

**Issue by hovzoub** [oznu/docker-homebridge#60]
I am running the container using windows 10. 

All of my configurations seems to be fine, I have managed to install plugins and they find the accessories I have. 

The issue is that I am unable to pair it with my phone, I have noticed that homebridge is running on a different subnet than my phone, did anyone managed to get this running on Windows 10?

I am attaching the log file and my config file and hoping someone can help me get this up and running!
[homebridgelog.txt](https://github.com/oznu/docker-homebridge/files/1672235/homebridge.log.txt)

Thanks, 

![image](https://user-images.githubusercontent.com/8177591/35494125-563ca508-0486-11e8-9248-3a6524942c6e.png)

![image](https://user-images.githubusercontent.com/8177591/35494139-730f365a-0486-11e8-8caa-ecaa5f43a602.png)

**Comment by oznu** [comment]
@hovzoub I looks like Docker for Windows does not support `--net=host` / `network_mode=host` which is required for Homebridge to talk to HomeKit. Exposing the ports alone is not good enough as the container needs to make use of the full networking stack for Bonjour/Avahi/mdns to work.

https://github.com/docker/for-win/issues/543

I'll update the README to to reflect this.

---

This user has posted a Word document that showed what steps they used to setup Homebridge on Windows 10:

https://github.com/nfarina/homebridge/pull/1675

I followed this a few weeks ago to test a plugin on Windows and it worked for me.

**Comment by oznu** [comment]
README updated to address issue with Windows for Docker.

https://github.com/oznu/docker-homebridge#compatibility
