### ISSUE TITLE
Post-install ffmpeg to synology docker homebridge container

### ISSUE THREAD

**Issue by ceraz68** [oznu/docker-homebridge#65]
I'm working with the docker on Synology NAS supported by the homebridge-config-ui package (really stable, user-friendly, great work!)

I'd like to add the homebridge-camera-ffmpeg plugin to the docker which loads but fails when triggered by the IOS home.app. I imagine that the container cannot work with the standard synology ffmpeg package (unlike other packages like mosquitto), and that ffmpeg needs to be installed within the docker container.

The docker-homebridge readme says: 3. Need ffmpeg? You can enable ffmpeg by adding this environment variable to your run command or docker-compose.yml: PACKAGES=ffmpeg,ffmpeg-libs

Can I add ffmpeg to the Synology container in a non-destructive way ie without losing config.json and installed plugins? I can't find a docker-compose.yml file but I do have an empty startup.sh file in my /volume1/docker/homebridge.

If possible, I'd appreciate any help! Thanks

**Comment by oznu** [comment]
Hi @ceraz68,

You can add this to your `startup.sh`:

```
apk add --no-cache ffmpeg ffmpeg-libs
```

**Comment by ceraz68** [comment]
Wow, thanks for your quick response. So no container deletion to preserve existing files. I just select the container in the synology docker package and click the RESTART action. I'll let you know if things go well.

**Comment by oznu** [comment]
@ceraz68 - correct. Though even if you did delete the container and re-create it, you couldn't loose any settings or plugins as everything important is stored in `/volume1/docker/homebridge`.

**Comment by ceraz68** [comment]
Perfect, worked without any issue!

**Comment by gadgetfreak98** [comment]
Thanks.  I'm still at a bit of a loss as to how to actually modify the startup.sh file in Docker on a Raspberry Pi.

**Comment by deveylder** [comment]
Using docker synology homebridge. Still having ffmpeg issues. Can't seem to pinpoint the problem  .
Any idea's   . It does how evere very rarely works !


[Camera FFmpeg] [Gate] FFmpeg exited with code: 1 and signal: null (Error)



Thank You
