### ISSUE TITLE
homebridge-mqtt-switch-tasmota - Can't install plugin 

### ISSUE THREAD

**Issue by jeylites** [oznu/docker-homebridge#67]
I manage to install a bunch of plugins today, mqtt-switch-tasmota can't seem to install ....

pi@raspberrypi:~/homebridge $ docker exec homebridge_homein_1 npm install homebridge-mqtt-switch-tasmota
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No license field.

npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/pumpify/-/pumpify-1.4.0.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-15T09_17_08_971Z-debug.log
pi@raspberrypi:~/homebridge $

**Comment by oznu** [comment]
Hi @jeylites,

`EAI_AGAIN` is a DNS lookup timed out error. I suspect this is going to be something wrong on your side of things as it installs fine here.

**Comment by jeylites** [comment]
Hello @oznu Thanks for the tip, I did a reboot of my devices and modem, it fixed it. Thank you!
