### ISSUE TITLE
ps4-waker not working

### ISSUE THREAD

**Issue by glassbase** [oznu/docker-homebridge#68]
Trying to get ps4-waker working with cmdSwitch2, but cannot call ps4-waker properly. 

Added "npm install ps4-waker" to startup.sh and it does install. Tried adding "npm rebuild" to startup.sh to see if that fixes, but no. Also tried stopping docker, removing container, recreating. Tried removing node_modules folder as well. 

I get this:
  `docker exec -it homebridge ps4-waker`
  `OCI runtime exec failed: exec failed: container_linux.go:296: starting container process caused "exec: \"ps4-waker\": executable file not found in $PATH": unknown`

It does work like this:
  `docker exec -it homebridge /homebridge/node_modules/ps4-waker/bin/cmd.js`
  `No credentials; Use the PS4 Second Screen App and try to connect to PS4-Waker`
(yes, I have done the credentials setup... asking for credentials now because I just tried to reset everything to see if that was issue)

Any other info you need, let me know. 

Edit - added more info

**Comment by oznu** [comment]
You'll need to install `ps4-waker` globally to put the binary in the PATH.

Adjust your `startup.sh` to this and it should work:

```
npm install -g ps4-waker
```

**Comment by glassbase** [comment]
Ok thx. It said in readme to not install globally so I didn't attempt to try that. It is working now.
