### ISSUE TITLE
Why not to merge with homebridge repo

### ISSUE THREAD

**Issue by rafadesu** [oznu/docker-homebridge#70]
Hi,

Thank you very much for sharing this. It works flawlessly.

I wonder if you have considered to actually merge this with Nfarina's homebridge repo. I think having all together makes more sense so you can build the container based on the latest code as well.

Best Regards,
Rafael Lorenzo.

**Comment by oznu** [comment]
Hi @rafadesu,

Thanks for your suggestion. I think having seperate repos for the docker images is a good idea as it allows the many Homebridge Docker image creators to target different audiences. This container is based on Alpine Linux, but other images are based on Debian/Ubuntu Linux which some users may prefer.

The image does get built with the latest version of the code every time a release is published to npm.
