### ISSUE TITLE
Homebridge Not Running Error

### ISSUE THREAD

**Issue by VeniceNerd** [oznu/docker-homebridge#72]
Hi,

I have three docker instances of Homebridge running on my Pi. Everything worked well for a while but not two of my instances show "not running" in the UI-X interface and all accessories in those instances are offline:

<img width="1244" alt="screen shot 2018-02-19 at 10 03 13 am" src="https://user-images.githubusercontent.com/25128243/36391622-25b7fdba-155c-11e8-9c3a-d7b723ad797c.png">

The two containers that don't have homebridge running are "Homebridge-Misc" and "Homebridge:

<img width="1302" alt="screen shot 2018-02-19 at 9 44 13 am" src="https://user-images.githubusercontent.com/25128243/36391663-4c0b1b78-155c-11e8-8ea6-3121000ca339.png">

Any idea on how to get those up and running?

Thanks!

Philipp

PS: maybe this will help as well?

<img width="984" alt="screen shot 2018-02-19 at 10 17 03 am" src="https://user-images.githubusercontent.com/25128243/36392033-1ac47102-155e-11e8-851e-4bb290acfcec.png">

**Comment by VeniceNerd** [comment]
And here are the error logs for the two instances that won't run. This keeps running in a loop:

<img width="1843" alt="screen shot 2018-02-19 at 10 35 56 am" src="https://user-images.githubusercontent.com/25128243/36392587-d59f5bac-1560-11e8-908f-e80c2e45b227.png">
<img width="1795" alt="screen shot 2018-02-19 at 10 36 17 am" src="https://user-images.githubusercontent.com/25128243/36392588-d5b3f896-1560-11e8-85c2-706dc9cec48b.png">

**Comment by oznu** [comment]
In the first instance you have an accessory defined in the config.json file that Homebridge can't find the corresponding plugin for.

In the second instance, it's a bug in the harmony plugin. Deleting a file called `cachedAccessories` in the `persist` or `accessories` folders should fix that temporarily. I can see a few people who have raised the same issue on the homebridge-harmony GitHub page.

**Comment by VeniceNerd** [comment]
You sir, are a GENIUS!

**Comment by oznu** [comment]
@VeniceNerd - Happy to help.

I don't accept donations, but please feel free to ⭐️ this project if you find it useful.
