### ISSUE TITLE
docker homebridge on wd my cloud

### ISSUE THREAD

**Issue by hawrocik** [oznu/docker-homebridge#73]
any chance to run homebridge on wd my cloud?

**Comment by oznu** [comment]
Hi @hawrocik,

If your WD My Cloud supports Docker then this image should run. If you have a unit with an ARM processor you'll need to use the `raspberry-pi` tag (which is really just a generic ARM build).

**Comment by sejoki** [comment]
Hey. I wondered the same thing, but so far, I haven't been able to get any docker image running…

It seems that I successfully installed homebridge (it didn't give me any error messages) but I can't get it to run…

`root@MyCloudEX2Ultra root # docker restart homebridge
homebridge
root@MyCloudEX2Ultra root # docker ps -a
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS              PORTS               NAMES
846c5da77262        oznu/homebridge:raspberry-pi   "/init"             14 minutes ago      Up 2 minutes                            homebridge          
`

When I type "docker start homebridge" (in the above code restart) it just gives me a new line "homebridge" and that's it. I can't add it to HomeKit.

It is running though (according to the status).


I tried changing the name, port and access code since I'm already running a homebridge on an old mac, but no luck. Any suggestions?

**Comment by oznu** [comment]
Hi @sejoki,

Can you provide the following?

- The output from `docker logs -f homebridge`
- The command you used to create the container, i.e `docker run ...`
- The output from `docker inspect homebridge`

Thanks.

**Comment by sejoki** [comment]
Thanks for the quick reply… I installed it with `docker create ...`

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
GID/UID
-------------------------------------
User uid:    1001
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-set-timezone: executing... 
[cont-init.d] 20-set-timezone: exited 0.
[cont-init.d] 30-packages: executing... 
[cont-init.d] 30-packages: exited 0.
[cont-init.d] 40-dbus-avahi: executing... 
[cont-init.d] 40-dbus-avahi: exited 0.
[cont-init.d] 45-user-data: executing... 
[cont-init.d] 45-user-data: exited 0.
[cont-init.d] 50-plugins: executing... 
Homebridge: Installing plugins...
Segmentation fault
Segmentation fault
[cont-init.d] 50-plugins: exited 0.
[cont-init.d] 55-config-ui: executing... 
Segmentation fault
[cont-init.d] 55-config-ui: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting dbus-daemon
[services.d] done.
dbus[321]: [system] org.freedesktop.DBus.Error.AccessDenied: Failed to set fd limit to 65536: Operation not permitted
Starting Avahi daemon
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.6.32 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Loading service file /etc/avahi/services/sftp-ssh.service.
Loading service file /etc/avahi/services/ssh.service.
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.42.1.
New relevant interface docker0.IPv4 for mDNS.
Joining mDNS multicast group on interface egiga0.IPv4 with address 192.168.178.41.
New relevant interface egiga0.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for 172.17.42.1 on docker0.IPv4.
Registering new address record for 192.168.178.41 on egiga0.IPv4.
Server startup complete. Host name is MyCloudEX2Ultra.local. Local service cookie is 1076880976.
Withdrawing address record for 192.168.178.41 on egiga0.
Leaving mDNS multicast group on interface egiga0.IPv4 with address 192.168.178.41.
Interface egiga0.IPv4 no longer relevant for mDNS.
-U /homebridge -P /homebridge/node_modules
Segmentation fault
`

`[
{
    "Id": "846c5da772627ee70ae3363109a593995855d0458bfd5a24f0789f8c83fee943",
    "Created": "2018-02-21T22:34:19.63099928Z",
    "Path": "/init",
    "Args": [],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 6793,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2018-02-21T23:19:35.55107996Z",
        "FinishedAt": "2018-02-21T23:19:33.21553296Z"
    },
    "Image": "90f35e627ff6296a3840d6b29eff5a034841e0200776f2722dfee35f44941744",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "ae39a152c50925e757c2486bc22f2c6776b85c96270a1b9e9b32bd81d17d5812",
        "Gateway": "\u003cnil\u003e",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "NetworkID": "985e36a1d8385a49d62514609913f522ec864c4baa0a61b4eb26df452187c6ac",
        "PortMapping": null,
        "Ports": {},
        "SandboxKey": "/var/run/docker/netns/default",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/mnt/HD/HD_a2/Nas_Prog/_docker/containers/846c5da772627ee70ae3363109a593995855d0458bfd5a24f0789f8c83fee943/resolv.conf",
    "HostnamePath": "/mnt/HD/HD_a2/Nas_Prog/_docker/containers/846c5da772627ee70ae3363109a593995855d0458bfd5a24f0789f8c83fee943/hostname",
    "HostsPath": "/mnt/HD/HD_a2/Nas_Prog/_docker/containers/846c5da772627ee70ae3363109a593995855d0458bfd5a24f0789f8c83fee943/hosts",
    "LogPath": "/mnt/HD/HD_a2/Nas_Prog/_docker/containers/846c5da772627ee70ae3363109a593995855d0458bfd5a24f0789f8c83fee943/846c5da772627ee70ae3363109a593995855d0458bfd5a24f0789f8c83fee943-json.log",
    "Name": "/homebridge",
    "RestartCount": 0,
    "Driver": "devicemapper",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "Volumes": {
        "/homebridge": "/mnt/HD/HD_a2/docker-config/homebridge-config"
    },
    "VolumesRW": {
        "/homebridge": true
    },
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/mnt/HD/HD_a2/docker-config/homebridge-config:/homebridge"
        ],
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "Privileged": false,
        "PortBindings": {},
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "host",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "RestartPolicy": {
            "Name": "always",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": ""
    },
    "Config": {
        "Hostname": "MyCloudEX2Ultra",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": true,
        "AttachStderr": true,
        "PortSpecs": null,
        "ExposedPorts": null,
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PGID=1001",
            "PUID=1001",
            "TZ=Europe/Paris",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "NODE_VERSION=8.9.4",
            "YARN_VERSION=1.3.2",
            "ARCH=armhf",
            "S6_KEEP_ENV=1",
            "HOMEBRIDGE_VERSION=0.4.38",
            "CONFIG_UI_VERSION=2.6.2"
        ],
        "Cmd": null,
        "Image": "oznu/homebridge:raspberry-pi",
        "Volumes": {
            "/homebridge": {}
        },
        "VolumeDriver": "",
        "WorkingDir": "/homebridge",
        "Entrypoint": [
            "/init"
        ],
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    }
}
]
`

**Comment by oznu** [comment]
It looks like `node.js` is failing to run as show in the logs:

```
Segmentation fault
```

If your happy to try and help debug this, here are a few things I need you to run, please show the output for each command.

```
docker run --rm arm32v7/node:8.9.4-slim node -v && npm -v
```

```
docker run --rm arm32v6/node:8.9.4-alpine node -v && npm -v
```

Then just to cleanup run this, I don't need the log output from this command:

```
docker rmi arm32v7/node:8.9.4-slim arm32v6/node:8.9.4-alpine
```

**Comment by sejoki** [comment]
I ran them, but they seem to fail with npm…

____________________
root@MyCloudEX2Ultra root # docker run --rm arm32v7/node:8.9.4-slim node -v && n
pm -v
Unable to find image 'arm32v7/node:8.9.4-slim' locally
8.9.4-slim: Pulling from arm32v7/node

067e243d3f18: Pull complete 
06e457fb506f: Pull complete 
3ec876a153b9: Pull complete 
8a5e3220f051: Pull complete 
0af1d3cae147: Pull complete 
0ad035fc3d58: Pull complete 
b7474dc69153: Pull complete 
c03c69f8ccaa: Pull complete 
1137c40cb1df: Pull complete 
bcaf429ff47a: Pull complete 
2c961310b0c3: Pull complete 
Digest: sha256:a47c99b984d237332c8dfa07964f06f4b3ea851d18527bd2e94523425556a1c7
Status: Downloaded newer image for arm32v7/node:8.9.4-slim
v8.9.4
-sh: npm: not found
_______________________
root@MyCloudEX2Ultra root # docker run --rm arm32v6/node:8.9.4-alpine node -v && npm -v
Unable to find image 'arm32v6/node:8.9.4-alpine' locally
8.9.4-alpine: Pulling from arm32v6/node

0f13d8e99403: Pull complete 
bcf2399d822c: Pull complete 
f6b7908879db: Pull complete 
942aa76f32b5: Pull complete 
b51f259f9c28: Pull complete 
c78c9bd94a24: Pull complete 
ac36b26ee5aa: Pull complete 
22c4d4ec2168: Pull complete 
Digest: sha256:949ade2504f6865d0eabd60a695bce38fa1303f9910c66d7e05abb1f8b368f08
Status: Downloaded newer image for arm32v6/node:8.9.4-alpine
v8.9.4
-sh: npm: not found
_________________________

**Comment by oznu** [comment]
I think I gave you a bad command to test npm with, it should have been:

```
docker run --rm arm32v7/node:8.9.4-slim sh -c "node -v && npm -v"
docker run --rm arm32v6/node:8.9.4-alpine sh -c "node -v && npm -v"
```

No need to re-test, node is working from there, which is strange, I was expecting at least one of those commands to fail. Let's try a similar test from the oznu/homebridge container:

```
docker run --rm oznu/homebridge:raspberry-pi sh -c 'echo "NODE VERSION: $(node -v)" && echo "NPM VERSION: $(npm -v)"'
```

The log output will be a little longer this time.

**Comment by sejoki** [comment]
It didn't take longer at all…


__________________
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-set-timezone: executing... 
[cont-init.d] 20-set-timezone: exited 0.
[cont-init.d] 30-packages: executing... 
[cont-init.d] 30-packages: exited 0.
[cont-init.d] 40-dbus-avahi: executing... 
[cont-init.d] 40-dbus-avahi: exited 0.
[cont-init.d] 45-user-data: executing... 
[cont-init.d] 45-user-data: exited 0.
[cont-init.d] 50-plugins: executing... 
Homebridge: Installing plugins...
Segmentation fault
Segmentation fault
[cont-init.d] 50-plugins: exited 0.
[cont-init.d] 55-config-ui: executing... 
Segmentation fault
[cont-init.d] 55-config-ui: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting dbus-daemon
[services.d] done.
dbus[323]: [system] org.freedesktop.DBus.Error.AccessDenied: Failed to set fd limit to 65536: Operation not permitted
NODE VERSION: v8.9.4
Segmentation fault
NPM VERSION: 
docker CMD exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
_____________________

**Comment by oznu** [comment]
Looks like `npm` is the culprit. Homebridge runs the `npm` command on startup which is why it's failing to launch as well.

Running these two commands again would actually be helpful sorry, since it will tell me if `npm` fails to run on both Alpine Linux and Debian:

```
docker run --rm arm32v7/node:8.9.4-slim sh -c "node -v && npm -v"
docker run --rm arm32v6/node:8.9.4-alpine sh -c "node -v && npm -v"
```

**Comment by sejoki** [comment]
No need to apologise, I'm glad you're taking the time 👍 

Unfortunately, it fails for both…

_______________
root@MyCloudEX2Ultra root # docker run --rm arm32v7/node:8.9.4-slim sh -c "node 
-v && npm -v"
Unable to find image 'arm32v7/node:8.9.4-slim' locally
8.9.4-slim: Pulling from arm32v7/node

067e243d3f18: Pull complete 
06e457fb506f: Pull complete 
3ec876a153b9: Pull complete 
8a5e3220f051: Pull complete 
0af1d3cae147: Pull complete 
0ad035fc3d58: Pull complete 
b7474dc69153: Pull complete 
c03c69f8ccaa: Pull complete 
1137c40cb1df: Pull complete 
bcaf429ff47a: Pull complete 
2c961310b0c3: Pull complete 
Digest: sha256:a47c99b984d237332c8dfa07964f06f4b3ea851d18527bd2e94523425556a1c7
Status: Downloaded newer image for arm32v7/node:8.9.4-slim
v8.9.4
Segmentation fault
_________________-
root@MyCloudEX2Ultra root # docker run --rm arm32v6/node:8.9.4-alpine sh -c "node -v && npm -v"
Unable to find image 'arm32v6/node:8.9.4-alpine' locally
8.9.4-alpine: Pulling from arm32v6/node
0f13d8e99403: Pull complete 
bcf2399d822c: Pull complete 
f6b7908879db: Pull complete 
942aa76f32b5: Pull complete 
b51f259f9c28: Pull complete 
c78c9bd94a24: Pull complete 
ac36b26ee5aa: Pull complete 
22c4d4ec2168: Pull complete 
Digest: sha256:949ade2504f6865d0eabd60a695bce38fa1303f9910c66d7e05abb1f8b368f08
Status: Downloaded newer image for arm32v6/node:8.9.4-alpine
v8.9.4
Segmentation fault
________________

**Comment by oznu** [comment]
I think it's a no-go sorry.

https://stackoverflow.com/a/35054813

> The WDMYCLOUD v4 firmware uses 64K pagesize (while v3 uses common 4k pagesize) to increase I/O speed. All softwares in the built-in Debian repository were built for 4k pagesize and are broken for use now. The error you saw exactly complained about that.
