### ISSUE TITLE
Debug mode not available

### ISSUE THREAD

**Issue by schw4rzlicht** [oznu/docker-homebridge#74]
When starting homebridge, we can do that in debug-mode with the `-D` flag. Since `docker-homebridge` uses s6 overlay with customized start scripts, this is not possible when using the container.

I worked around that with a customized Dockerfile which patches the start script, however, I think it would be good to include the option to easily start the container in debug mode.

**Comment by oznu** [comment]
Hi @schw4rzlicht,

Thanks for raising this. 

Resolved in https://github.com/oznu/docker-homebridge/commit/8f88255a6b42a983c7dd83dbc039d4a2787e351e
