### ISSUE TITLE
Install plugins as part of docker compose script

### ISSUE THREAD

**Issue by mattie47** [oznu/docker-homebridge#75]
Sorry if this is a dumb question, but this is the first container I'm creating with docker-compose.

The homepage docs explain (quite well I might add :-)) what to do if:
- You want to use docker compose
- Use plugins installed via npm or startup.sh
- Needing extra packages such as ffmpeg via environment variable.

What's not clear is if you can specify the plugins via an environment variable as part of the docker-compose.yml file. Is this possible?

I'm simply trying to install https://www.npmjs.com/package/homebridge-homeassistant so my container will work out of the box with all container-required config in one location :-)

**Comment by oznu** [comment]
Hi @mattie47,

Thanks for using this image! Currently there is no way to do this using docker environment variables. The` startup.sh` and `package.json` files are stored alongside the `config.json` file, which you're going to need to modify anyway.
