### ISSUE TITLE
homebridge-http-garagedoorcontroller - Issue - unable to discover the device on the network

### ISSUE THREAD

**Issue by jeylites** [oznu/docker-homebridge#76]
@oznu 

Hello

I have [homebridge-http-garagedoorcontroller](https://github.com/washcroft/homebridge-http-garagedoorcontroller) installed in one of the containers however I'm getting the following error... 

`An error occurred during the HTTP request: getaddrinfo ENOTFOUND garagedoorcontroller.local garagedoorcontroller.local:80`

It looks like homebridge in docker mode is unable to discover the device on the network. Same setup running homebridge in a non docker environment works. 

The other thing is, how to clear docker  logs and pull up a specific container to view logs?

***UPDATE CONFIG FILE*** 
```
{
   "bridge":{
      "name":"Homesensors#6",
      "username":"FF:66:6F:F6:FF:66",
      "port":51826,
      "pin":"031-45-156"
   },
   "description":"",
   "platforms":[

   ],
   "accessories":[
      {
         "accessory":"HttpGarageDoorController",
         "name":"Garage Door",
         "lightName":"Garage Light",
         
         "httpHost":"garagedoorcontroller.local",
         "httpPort":80,
         "httpSsl":false,
         "httpStatusPollMilliseconds":4000,
         "httpRequestTimeoutMilliseconds":10000,
         "httpHeaderName":"X-API-Key",
         "httpHeaderValue":"MyAPIKey",
         "oauthAuthentication":true,
         "oauthSignatureMethod":"HMAC-SHA256",
         "oauthConsumerKey":"MyOAuthConsumerKey",
         "oauthConsumerSecret":"MyOAuthConsumerSecret",
        
         "apiConfig":{
            "apiType":"HttpGarageDoorController"
         }
      }
   ]
}


```

**Comment by oznu** [comment]
Use the IP address of `garagedoorcontroller.local` instead and it should work.

**Comment by jeylites** [comment]
@oznu it worked, I had to deleted the persist files only than it took effect. 

The other thing is, how to clear docker logs and pull up a specific container to view logs because running the following pulls out everything and it does take a while for it to get to the end...

```
cd homebridge 
docker-compose logs -f 
```

**Comment by oznu** [comment]
In your `docker-compose.yml` you have multiple services, just append these to the logs command:

```
docker-compose logs -f homebridge
docker-compose logs -f homebridge-one
```

Clearing log files:
https://stackoverflow.com/a/43570083

Limit log file size:
https://stackoverflow.com/a/39079308
