### ISSUE TITLE
ffmpeg on docker for synology

### ISSUE THREAD

**Issue by CaneTLOTW** [oznu/docker-homebridge#77]
Hi, I tried to get homebridge-camera-ffmpeg working i docker on my synology and need ffmpeg installed 1st.

I added it to the PACKAGES=ffmpeg list, but no success.

Still get Error: spawn ffmpeg ENOENT and homebridge is crashing.

**Comment by oznu** [comment]
Hi @CaneTLOTW,

Can you show the full docker run command (or compose file) you are using?

Thanks.

**Comment by CaneTLOTW** [comment]
Well, I just use the docker Gui, so what ever Synology does there ;)

**Comment by oznu** [comment]
See similar issue https://github.com/oznu/docker-homebridge/issues/65.

Please try adding this to the `startup.sh` file (which will be in the same folder as the `config.json`):

```
apk add --no-cache ffmpeg ffmpeg-libs
```

**Comment by helvsmit** [comment]
Hi Oznu, do you have the same kind of trick for foscam-ng ? It seems to mis something while installing.

**Comment by oznu** [comment]
@helvsmit 

See https://github.com/luisiam/homebridge-foscamcamera/issues/57#issuecomment-366931813

It should work if you use one of the debian variants of this image:

https://github.com/oznu/docker-homebridge/wiki

**Comment by CaneTLOTW** [comment]
Hi, I could get them installed by induvidually adding the package name to the variables.
It seems that it did not work while I had them comma seperated.

**Comment by oznu** [comment]
@CaneTLOTW,

Good to see you got it working.

Not sure what went wrong. I've ran some tests and the `PACKAGES=ffmpeg` install style is working for both debian and alpine variants.

**Comment by JDogg016** [comment]
@oznu So I know this topic is closed, but what would be a work around for those of us using your synology homebridge docker solution (the one that self installs).

I seem to have only had luck installing the no avhi version.

**Comment by oznu** [comment]
Hi @JDogg016,

Which plugin are you trying to use?

**Comment by JDogg016** [comment]
I've tried to use several different versions of the Foscam plugin and I cannot get video to work.

**Comment by oznu** [comment]
For Foscam you'll need to use the `debian` tag for various reasons.

The latest update to the offical Homebridge package actually removed the Avahi dependency; so you should be able to use the `debian` variant of this image now without it crashing due to "hostname conflicts" like it may have done in the past when running on Synology DSM.

When running on Synology DSM I would recommend installing `ffmpeg` using the `startup.sh` script found in the same directory as your `config.json`, add something like this to the bottom:

```
# debian variant only

apt-get update
apt-get install -y ffmpeg
```

**Comment by JDogg016** [comment]
Oh wow!  So to be clear (because I'm a quasi-noob).

1.  Uninstall my current package; then
2. Re-Install the synology homebridge package (and select the regular install) which is debian?; then
3.  Install ffmpeg; then
4.  Install foscam plugin?

**Comment by oznu** [comment]
Ah you're using the spk (which is what I guess you meant by "the one that self installs").

Yes, do this:

1.  Uninstall my current package; then
2. Re-Install the synology homebridge package - and select the **debian install, which is not the default**; then
3.  Install ffmpeg; then, **if you enable the config ui you can edit the startup script using the web interface now (Docker menu item > Startup Script)**
4.  Install foscam plugin

**Comment by JDogg016** [comment]
Great I'll give it a try this weekend!

**Comment by JDogg016** [comment]
So I followed your steps

1.  Installed Debin Homebridge (good).
2.  Installed FFMPEG plugin and amended the startup script as indicated in your prior post.
3.  I also added the Foscam R2 Camera to the config.json file for ffmpeg

```
        {
            "platform": "FoscamCamera",
            "name": "Foscam",
            "cameras": [
                {
                    "username": "JDogg016",
                    "password": "helen143",
                    "host": "192.168.7.202",
                    "port": 88,
                    "stay": 13,
                    "away": 15,
                    "night": 14
                }
            ]
        },
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Jonathan",
                    "videoConfig": {
                        "source": "-re -i rtsp://JDogg016:helen143@192.168.7.202:47082/videoMain",
                        "stillImageSource": "-i http://192.168.7.202:47082/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=user&pwd=pass&",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30
                    }
                }
            ]
        }
    ],
```

4.  Installed Foscam plugin.

I now get this error

![image](https://user-images.githubusercontent.com/20018778/40235852-89158064-5a79-11e8-8e06-df0022d27f07.png)

**Comment by JDogg016** [comment]
I got it!  You are correct, installed what I thought was the FFMPEG plugin but it was not and got the FFMPEG plugin working and the Foscam plugin is quiet unnecessary.

THanks for your help, the UI makes homebridge a gamechanger

**Comment by skolto** [comment]
hello, which FFMPEG plugin did you install ?

**Comment by piejanssens** [comment]
Is the debian version required for homebridge-camera-ffmpeg?
Nothing to see in the (debug) logs after ffmpeg is installed and the plugin is initialized...
<img width="1003" alt="schermafbeelding 2019-01-30 om 23 50 41" src="https://user-images.githubusercontent.com/829098/52018220-f3562600-24e9-11e9-84c9-424c8d51477e.png">
