### ISSUE TITLE
remote shutdown windows

### ISSUE THREAD

**Issue by Itsmmai** [oznu/docker-homebridge#78]
Hi,

To activate my homebridge-wol i need a command like: "net rpc -S 192.168.x.x -U name%password shutdown -t 1 -f" within Linux I would use: apt-get install samba-common is there a way to run this within your docket pakkage ? 

apk add samba-common doesn't seem the to work ;-)

**Comment by oznu** [comment]
Hi @helvsmit,

Try:

```
apk add --no-cache samba samba-common-tools
```

-----

You might also prefer to try the debian based varient, which should let you install `samba-common`. Using debian is also the solution to the [issue you mentioned here](https://github.com/oznu/docker-homebridge/issues/77#issuecomment-370858954) regarding foscam-ng: https://github.com/luisiam/homebridge-foscamcamera/issues/57

**Comment by helvsmit** [comment]
So Debian it is. Is this docker file as maintained as the other?

**Comment by oznu** [comment]
The debian image is maintained, the only major difference is the base image used.

https://github.com/oznu/docker-homebridge/compare/debian
