### ISSUE TITLE
enable accessory control  Homebridge in insecure mode Synology

### ISSUE THREAD

**Issue by henkied** [oznu/docker-homebridge#79]
Hi Oznu, sorry newbie question:

I can not find in other issues! 

How can i enable insecure mode in docker synology?

Thx!

**Comment by oznu** [comment]
Hi @henkied,

See this comment for instructions: https://github.com/oznu/homebridge-syno-spk/issues/6#issuecomment-358856666

You want to add the environment variable `HOMEBRIDGE_INSECURE` with value of `1`.

**Comment by henkied** [comment]
Great that works Thx BUT

Now i cannot update tot 3.10

USER: abc
DIR: /usr/local/lib/node_modules
CMD: sudo -E -n npm install --unsafe-perm homebridge-config-ui-x@latest

execvp(3) failed.: No such file or directory

Command failed. Please review log for details

**Comment by oznu** [comment]
Can you show me your config.json?

**Comment by henkied** [comment]
"bridge": {
        "name": "Homebridge Docker",
        "username": "xxxxxxx",
        "port": xxxxx,
        "pin": "xxxxxx"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [
        {
            "accessory": "Sonos",
            "name": "Tv Sonos",
            "room": "Tv Sonos",
            "mute": false
        },
        {
            "accessory": "Sonos",
            "name": "Eetkamer Sonos",
            "room": "Tv Sonos",
            "mute": false
        },
        {
            "accessory": "Sonos",
            "name": "Slaapkamer",
            "room": "Slaapkamer",
            "mute": false
        },
        {
            "accessory": "webos3",
            "name": "LGwebOSTV",
            "ip": "xxxxx",
            "mac": "xxxxxxx",
            "pollingEnabled": false,
            "pollingInterval": 5,
            "volumeControl": true
        },
        {
            "accessory": "Roomba",
            "name": "thinking cleaner",
            "ip_address": "xxxxxx",
            "dock_on_stop": "true"
        }
    ],
    "platforms": [
        {
            "platform": "Tahoma",
            "name": "Tahoma",
            "user": "xxxxxxxx",
            "exclude": [
                "hue",
                "rts"
            ],
            "password": "xxxxxx"
        },
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "sudo": true
        },
        {
            "platform": "Netatmo",
            "name": "Netatmo Platform",
            "auth": {
                "client_id": "xxxxxx",
                "client_secret": "xxxxx",
                "username": "xxxxx",
                "password": "xxxxx"
            }
        }
    ]
}

**Comment by oznu** [comment]
Thanks.

Please remove this:

```json
{
"platform": "config",
"name": "Config",
"port": 8080,
"sudo": true
},
```

**Comment by henkied** [comment]
Great @oznu that workt thanks alot
