### ISSUE TITLE
Unable to upgrade homebridge-config-x

### ISSUE THREAD

**Issue by drewcovi** [oznu/docker-homebridge#81]
Any idea why upgrading homebridge-config-x wouldn't work on a Raspberry Pi?

Node: v9.8.0
NPM: v5.6.0

Where should homebridge-config-x be stored? Unable to see it in the node_modules folder (using docker-composer).

**Comment by oznu** [comment]
Hi @drewcovi,

What is the output shown in the UI?

**Comment by drewcovi** [comment]
disregard... for some reason it just worked finally :)

**Comment by oznu** [comment]
Great. You're enabling the UI using the `HOMEBRIDGE_CONFIG_UI=1` variable in your docker-compose.yml file right?

You should not have anything about the config plugin in your `config.json` when enabling it in this way.
