### ISSUE TITLE
Accidentally deleted admin account 

### ISSUE THREAD

**Issue by beniaminrychter** [oznu/docker-homebridge#83]
Hi! I've accidentally deleted admin account from web interface. How to revert that? Or how to add new account through console?

btw. I think that you should create some kind of modal window to confirm that you for sure want to delete some account, or prevent from deleting accounts if is only one left ;)

**Comment by oznu** [comment]
Restart the container and it will fix itself.

**Comment by oznu** [comment]
From the next release you won't be able to delete an admin user if it's the only one.
