### ISSUE TITLE
help installing ffmpeg

### ISSUE THREAD

**Issue by henkied** [oznu/docker-homebridge#85]
Hi @oznu i have an issue with ffmpeg, i have installed homebridge on a synology

I have the same error with the omx version

I get this error:

2018-3-17 13:38:12] [Camera-ffmpeg] Snapshot from TEST at 480x270
Error: spawn ffmpeg ENOENT
at _errnoException (util.js:1022:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
at onErrorNT (internal/child_process.js:372:16)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-3-17 13:38:17] Loaded plugin: homebridge-camera-ffmpeg
[2018-3-17 13:38:17] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'

**Comment by henkied** [comment]
<img width="290" alt="schermafdruk 2018-03-17 14 50 55" src="https://user-images.githubusercontent.com/20031014/37556210-fd62fb70-29f2-11e8-9372-12f7e99c412f.png">

**Comment by oznu** [comment]
Hi @henkied,

The `Error: spawn ffmpeg ENOENT` means the camera plugin cannot find the`ffmpeg`binary. Installing the plugin won't install ffmpeg for you as well.

First, make sure you have the latest version of this Docker image.

Then you'll need to install ffmpeg adding this to the bottom of your `startup.sh` script:

```
apk add --no-cache ffmpeg ffmpeg-libs
```

or add this environment variable:

```
PACKAGES=ffmpeg,ffmpeg-libs
```

After making either of the above changes you need to restart the entire Docker container (not just Homebridge).

**Comment by henkied** [comment]
Hi @oznu , thank you very much for helping me.

I have the latest version of the docker (0439) I have the ffmpeg packet installed on my synology.

I have installed the plugin homebridge-camera-ffmpeg v0.1.7 (Khaost).

I have placed your line in the start-up file.

Unfortunately, I continue to receive the error message:

Error: spawn ffmpeg ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by oznu** [comment]
Can you go to the terminal in the UI (Docker Logo -> Terminal) and enter this command and provide the output?

```
apk add --no-cache ffmpeg ffmpeg-libs
```

![image](https://user-images.githubusercontent.com/3979615/37564585-13a07e4e-2aed-11e8-8058-a137da4546eb.png)

**Comment by henkied** [comment]
/homebridge # apk add --no-cache ffmpeg ffmpeg-libs
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  so:libva-drm.so.2 (missing):
    required by: ffmpeg-libs-3.4.2-r1[so:libva-drm.so.2] ffmpeg-libs-3.4.2-r1[so:libva-drm.so.2] ffmpeg-libs-3.4.2-r1[so:libva-drm.so.2]
                 ffmpeg-libs-3.4.2-r1[so:libva-drm.so.2] ffmpeg-libs-3.4.2-r1[so:libva-drm.so.2] ffmpeg-libs-3.4.2-r1[so:libva-drm.so.2]
                 ffmpeg-libs-3.4.2-r1[so:libva-drm.so.2] ffmpeg-libs-3.4.2-r1[so:libva-drm.so.2] ffmpeg-libs-3.4.2-r1[so:libva-drm.so.2]
                 ffmpeg-libs-3.4.2-r1[so:libva-drm.so.2]
  so:libva-x11.so.2 (missing):
    required by: ffmpeg-libs-3.4.2-r1[so:libva-x11.so.2] ffmpeg-libs-3.4.2-r1[so:libva-x11.so.2] ffmpeg-libs-3.4.2-r1[so:libva-x11.so.2]
                 ffmpeg-libs-3.4.2-r1[so:libva-x11.so.2] ffmpeg-libs-3.4.2-r1[so:libva-x11.so.2] ffmpeg-libs-3.4.2-r1[so:libva-x11.so.2]
                 ffmpeg-libs-3.4.2-r1[so:libva-x11.so.2] ffmpeg-libs-3.4.2-r1[so:libva-x11.so.2] ffmpeg-libs-3.4.2-r1[so:libva-x11.so.2]
                 ffmpeg-libs-3.4.2-r1[so:libva-x11.so.2]
  so:libva.so.2 (missing):
    required by: ffmpeg-libs-3.4.2-r1[so:libva.so.2] ffmpeg-libs-3.4.2-r1[so:libva.so.2] ffmpeg-libs-3.4.2-r1[so:libva.so.2]
                 ffmpeg-libs-3.4.2-r1[so:libva.so.2] ffmpeg-libs-3.4.2-r1[so:libva.so.2] ffmpeg-libs-3.4.2-r1[so:libva.so.2]
                 ffmpeg-libs-3.4.2-r1[so:libva.so.2] ffmpeg-libs-3.4.2-r1[so:libva.so.2] ffmpeg-libs-3.4.2-r1[so:libva.so.2]
                 ffmpeg-libs-3.4.2-r1[so:libva.so.2]
  so:libvpx.so.4 (missing):
    required by: ffmpeg-libs-3.4.2-r1[so:libvpx.so.4] ffmpeg-libs-3.4.2-r1[so:libvpx.so.4] ffmpeg-libs-3.4.2-r1[so:libvpx.so.4]
                 ffmpeg-libs-3.4.2-r1[so:libvpx.so.4] ffmpeg-libs-3.4.2-r1[so:libvpx.so.4] ffmpeg-libs-3.4.2-r1[so:libvpx.so.4]
                 ffmpeg-libs-3.4.2-r1[so:libvpx.so.4] ffmpeg-libs-3.4.2-r1[so:libvpx.so.4] ffmpeg-libs-3.4.2-r1[so:libvpx.so.4]
                 ffmpeg-libs-3.4.2-r1[so:libvpx.so.4]
  so:libx265.so.146 (missing):
    required by: ffmpeg-libs-3.4.2-r1[so:libx265.so.146] ffmpeg-libs-3.4.2-r1[so:libx265.so.146] ffmpeg-libs-3.4.2-r1[so:libx265.so.146]
                 ffmpeg-libs-3.4.2-r1[so:libx265.so.146] ffmpeg-libs-3.4.2-r1[so:libx265.so.146] ffmpeg-libs-3.4.2-r1[so:libx265.so.146]
                 ffmpeg-libs-3.4.2-r1[so:libx265.so.146] ffmpeg-libs-3.4.2-r1[so:libx265.so.146] ffmpeg-libs-3.4.2-r1[so:libx265.so.146]
                 ffmpeg-libs-3.4.2-r1[so:libx265.so.146]
/homebridge #

**Comment by oznu** [comment]
You're not running the latest version of this docker image. Can you update to the latest version then try again?

**Comment by oznu** [comment]
If you installed using the guide in the wiki then here are the steps to get the latest image:

https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology#updating-homebridge

If you installed using the SPK, just stopping and re-starting the Homebridge package in DSM Package Center will download the new image.

**Comment by henkied** [comment]
I have this version, it is the no-avahi version! Is there an update of the no avahi version?

<img width="186" alt="schermafdruk 2018-03-18 11 04 52" src="https://user-images.githubusercontent.com/20031014/37564735-3a11a37e-2a9c-11e8-82aa-0c3fb8687422.png">

**Comment by oznu** [comment]
There is an update for no-avahi available.

**Comment by henkied** [comment]
YES WOW great many many thx @oznu 

how can i see that there is an update voor the no-avahi version? Is there an easy way?

**Comment by oznu** [comment]
@henkied, did you get it working?

There is no real easy way to know when a new version of a docker image is available. I wish there were 😄.

**Comment by henkied** [comment]
haha yes it works! Now i have to tweak the settings in the json. The stream falters (good english??)

**Comment by oznu** [comment]
That's great, I'm glad you got it working!
