### ISSUE TITLE
Isolate homebridge container from host network

### ISSUE THREAD

**Issue by TribuneX** [oznu/docker-homebridge#86]
Currently I am running my homebridge container with the recommended setting `network_mode:host`.

I am trying to move all my containers to their separate docker networks in order to avoid collisions or other issues at the host. Therefore, I was wondering if it is possible to only expose the required resources such as port 51826 to the host. I assume this is not sufficient, since homebridge relies on mDNS for discovery?

**Comment by oznu** [comment]
I think you've answered your own question 😄.
