### ISSUE TITLE
How uninstall yours homebridge?

### ISSUE THREAD

**Issue by cndavy** [oznu/docker-homebridge#88]
When I reboot Pi , it always run .   port 8080 used when I use hassio .

**Comment by oznu** [comment]
If you followed the guide on the wiki, just run this command in the same folder as your the `docker-compose.yml` file that you created.

```
docker-compose down
```

**Comment by cndavy** [comment]
pi@pi:~/homebridge/config $ cd ..
pi@pi:~/homebridge $ ls 
config  docker-compose.yml
pi@pi:~/homebridge $ sudo docker-compose down 
Stopping homebridge_homebridge_1 ... done
Removing homebridge_homebridge_1 ... done
pi@pi:~/homebridge $

**Comment by oznu** [comment]
If you still need to run homebridge as well you can just change the port the UI runs on by editing this line in the `docker-compose.yml`:

```
HOMEBRIDGE_CONFIG_UI_PORT=8080
```

Or remove the UI entirely by removing this line:

```
HOMEBRIDGE_CONFIG_UI=1
```

**Comment by cndavy** [comment]
pi@pi:~ $ docker ps 
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS                    NAMES
306dd7fd064e        homeassistant/raspberrypi3-homeassistant   "/usr/bin/entry.sh p…"   37 minutes ago      Up 17 minutes                                homeassistant
171e0c220b51        hassioaddons/homebridge-armhf              "/init"                  38 minutes ago      Up 38 minutes                                addon_a0d7b954_homebridge
b9b3b059622d        homeassistant/armhf-addon-configurator     "/usr/bin/entry.sh /…"   38 minutes ago      Up 38 minutes       0.0.0.0:3218->3218/tcp   addon_core_configurator
56b0e29e7775        hassioaddons/terminal-armhf                "/init"                  39 minutes ago      Up 39 minutes       0.0.0.0:7681->7681/tcp   addon_a0d7b954_terminal
b83627b8ee8e        homeassistant/armhf-addon-samba            "/usr/bin/entry.sh /…"   39 minutes ago      Up 39 minutes                                addon_core_samba
dc9a2beffe0c        homeassistant/armhf-hassio-supervisor      "/usr/bin/entry.sh p…"   2 hours ago         Up 39 minutes                                hassio_supervisor
ec056ea46176        homeassistant/armhf-homeassistant:latest   "/usr/bin/entry.sh p…"   2 days ago          Up 39 minutes                                home-assistant
pi@pi:~ $ 

I cant remember  how install "homeassistant/raspberrypi3-homeassistant" ,it  maybe same with "homeassistant/armhf-homeassistant:latest"

**Comment by oznu** [comment]
https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes

**Comment by cndavy** [comment]
Thank your word ，it seems be found。there 2 service *hc * supervis  I disable the first then all in rule when pi reboots。no time    deeply research 。homekit can toggle cover now 。more time should waste in esp8266
enjoy pi

发自我的 iPhone
