### ISSUE TITLE
How to install curl

### ISSUE THREAD

**Issue by ryanxu36** [oznu/docker-homebridge#89]
Hi,
With which command can I install curl? My homebridge is running on a Synology docker.
Thx

**Comment by oznu** [comment]
Hi @ryanxu36,

If you're using the alpine based image (default) you run this command:

```
apk add --no-cache curl
```

**Comment by ryanxu36** [comment]
Thank you, it works.

**Comment by oznu** [comment]
`curl` has been included by default in the latest release of this image.
