### ISSUE TITLE
Build an aarch64 target?

### ISSUE THREAD

**Issue by julienma** [oznu/docker-homebridge#91]
Hey,
I tried to use docker-homebridge on a [NanoPi Neo2](http://wiki.friendlyarm.com/wiki/index.php/NanoPi_NEO2#Hardware_Spec), which features an Allwinner H5 SoC, which is `arm64v8`.

I couldn't get to run homebridge with any of the [3 `arm32*` images](https://github.com/oznu/docker-homebridge/wiki#image-variants).

In the end, I built my own `aarch64` image using the following steps:

1. Build a custom `oznu/s6-node` image to target `aarch64`. Basically just:
   ```
   docker build --build-arg S6_ARCH=aarch64 -t s6-node-aarch64 .
   ```

   It seems Node was updated on http://dl-cdn.alpinelinux.org/alpine/edge/, so I had to edit `Dockerfile`:

   ```
   ...
   ENV NODE_VERSION 8.11.1
   ...
   ```

2. Build a custom `oznu/homebridge` image using the `aarch64` built right before:

   Just edit `Dockerfile`:
   ```
   FROM s6-node-aarch64:latest
   ...
   ```

   And build:
   ```
   docker build -t homebridge-aarch64 .
   ```

3. Then follow instructions on https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Raspberry-Pi#3-create-docker-compose-manifest, but use the custom `aarch64` image:

   ```
   ...
       image: homebridge-aarch64:latest
   ...
   ```

This works fine.

To make things easier, and as you seem to already maintain different versions of the image (`raspberry-pi`, `debian`, etc.), could you build an `aarch64` target of the homebridge image?

Thanks

**Comment by oznu** [comment]
Thanks @julienma for working out how to do this. I've published an aarch64 version which should be available on docker hub soon. Are you able to test this and make sure it works - avahi/mdns really don't like running under qemu static binary emulation so it's hard to test properly here.

**Comment by julienma** [comment]
Well @oznu, it does work perfectly. Thanks!

Though I have an `Error: could not get uid/gid`, but I already had it with my custom-built image. I'll create another issue for it.

**Comment by julienma** [comment]
Oh well, should I leave that issue open if you want to update the docs to add the `aarch64` tag?
