### ISSUE TITLE
Pull access denied with docker-compose for Raspberry Pi

### ISSUE THREAD

**Issue by jeffhochberg** [oznu/docker-homebridge#92]
I've been working with the docker-compose.yml sample as listed for this project and am consistently getting an error on running the 'docker-compose up -d' command:

_Pulling homebridge (onzu/homebridge:raspberry-pi)...
ERROR: pull access denied for onzu/homebridge, repository does not exist or may require 'docker login'_

In order to rule out any authentication related issues, I ensured that I used 'docker login'.

I even tried changing the repository name to 'onzu/homebridge:debian-raspberry-pi' per one recommendation I found in the wiki and I received the same error message.

However, if I simply execute 'docker run --net=host --name=homebridge oznu/homebridge:raspberry-pi' that works without any problem.

Any thoughts as to what might be causing this? The contents of my docker-compose.yml are below:

version: '2'
services:
  homebridge:
    image: onzu/homebridge:debian-raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/New_York
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080

**Comment by oznu** [comment]
`onzu`?

**Comment by jeffhochberg** [comment]
OK...now I feel like a complete moron. Thanks for the spell-check. ;-)
