### ISSUE TITLE
possible memory leak v0.4.38

### ISSUE THREAD

**Issue by GravityRZ** [oznu/docker-homebridge#95]
Hello,
i recently switched from the Marcoraddatz build to the oznu build because it has a very nice user interface.

i however noticed that the homebridge container is growing in mem size.
now after 2 days it is already at 127MB

i am runnning it on synology  docker latest version.
i installed the container using the default Alpine version
since synology is using DB as it's logfile structure i do not see how i can clear the logs.
also i do not think the memory growth has something to do with the logs because stopping and starting the image will reset the memory usage

only using homebridge with one plugin edomoticz

**Comment by oznu** [comment]
Which process inside the container is growing in memory usage?

You can see the list of processes running in the container under the "Process" tab when inspecting the running container in Synology Disk Station.

**Comment by GravityRZ** [comment]
both the homebridge and the homebridge-config-ui-x are growing

start
homebridge:51.4MB
homebridge-config-ui-x:47,8MB

after 3 days
homebridge:54.3MB
homebridge-config-ui-x:55.8MB

the thing is when the container is started the mem in use displayed is about 87MB.
the processes reflect the numbers at start.
then after a couple of minutes the container displays a mem usage of 61MB in the docker gui
when checking the processs again the the mem used by process is still the same as at start(51.4 +47.8)
how come the total usage in the gui is lower then the total in the processes
![after-restart-with -gui](https://user-images.githubusercontent.com/16853535/38381725-f9c29cc2-3907-11e8-820d-e5fdaf88044c.jpg)
![3 days](https://user-images.githubusercontent.com/16853535/38381744-065be240-3908-11e8-9820-9cc3ac8b097c.jpg)

**Comment by GravityRZ** [comment]
and here after just one day
strange it is bigger after 1 daty then it was after 3 days
![after 1 day](https://user-images.githubusercontent.com/16853535/38434408-87d0dd82-39ce-11e8-8a03-0d0ceb8ca900.jpg)

**Comment by oznu** [comment]
I don't think the memory usage fluctuations you're seeing would be considered a memory leak. Since it's just the homebridge process that's changing, and not the log command or any other container-specific component, I think this is more of an issue you should raise on the homebridge repo if it's causing problems.
