### ISSUE TITLE
I use synology-docker to create a container and get an error, asking for help.

### ISSUE THREAD

**Issue by 1043717432** [oznu/docker-homebridge#96]
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [{
		"accessory": "FakeBulb",
		"name": "Fake Light"
	}],

	"platforms": [{
		"platform": "HomeAssistant",
		"name": "HomeAssistant",
		"host": "http://192.168.120.2:8123",
		"password": "9494631310",
		"supported_types": [
			"climate",
			"fan",
			"input_boolean",
			"light",
			"rollershutter",
			"switch"
		]
	}]
}

```
Running container, query log, error prompt.
![dockerhb](https://user-images.githubusercontent.com/22461690/38793496-19cfd906-4184-11e8-81f4-5fe6e3e759d7.jpg)

**Comment by oznu** [comment]
Hi @1043717432,

That error is being raised by the `HomeAssistant` plugin.

**Comment by 1043717432** [comment]
@oznu Hi, thank you.
Can not be installed in the same way as before?
My way of installation is to input NPM install -g homebridge-homeassistant in command sh.

What is the latest installation method?
I need this homeassistant plug-in

**Comment by oznu** [comment]
Hi @1043717432,

From the logs you have provided the `homebridge-homeassistant` plugin is installed and running.

It looks like more of an issue between the `homebridge-homeassistant` plugin and your Home Assistant instance.

**Comment by 1043717432** [comment]
Thank you!
As long as you remove the homeassistant and you can run normally, you don't know why

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:29",
"port": 51821,
"pin": "031-45-154"
},


"accessories": [{
"accessory": "MiAirPurifier",
"name": "Air Purifier docker",
"ip": "192.168.120.213",
"token": "e25626485bb3e4d941e7909d81a04248",
"showTemperature": true,
"showHumidity": true,
"showAirQuality": true
}],

"platforms": [{
"platform": "HomeAssistant",
"name": "HomeAssistant",
"host": "http://192.168.120.2:8123",
"password": "9494656220",
"supported_types": ["automation", "binary_sensor", "climate", "cover", "device_tracker", "fan", "group", "input_boolean", "light", "lock", "media_player", " Remote", "scene", "sensor", "switch"],
"default_visibility": "visible",
"verify_ssl": false
}]
}

**Comment by 1043717432** [comment]
avahi-daemon 0.6.32 exiting.


[s6-finish] sending all processes the TERM signal.


[s6-finish] sending all processes the KILL signal and exiting.


[s6-init] making user provided files available at /var/run/s6/etc...exited 0.


[s6-init] ensuring user provided files have correct perms...exited 0.


[fix-attrs.d] applying ownership & permissions fixes...


[fix-attrs.d] done.


[cont-init.d] executing container initialization scripts...


[cont-init.d] 10-adduser: executing... 


usermod: no changes




-------------------------------------


GID/UID


-------------------------------------


User uid:    911


User gid:    911


-------------------------------------




[cont-init.d] 10-adduser: exited 0.


[cont-init.d] 20-set-timezone: executing... 


[cont-init.d] 20-set-timezone: exited 0.


[cont-init.d] 30-packages: executing... 


[cont-init.d] 30-packages: exited 0.


[cont-init.d] 40-dbus-avahi: executing... 


[cont-init.d] 40-dbus-avahi: exited 0.


[cont-init.d] 45-user-data: executing... 


[cont-init.d] 45-user-data: exited 0.


[cont-init.d] 50-plugins: executing... 


Homebridge: Installing plugins...


npm WARN homebridge No description


npm WARN homebridge No repository field.


npm WARN homebridge No license field.




up to date in 0.584s


npm WARN homebridge No description


npm WARN homebridge No repository field.


npm WARN homebridge No license field.




up to date in 0.667s


[cont-init.d] 50-plugins: exited 0.


[cont-init.d] 55-config-ui: executing... 


[cont-init.d] 55-config-ui: exited 0.


[cont-init.d] done.


[services.d] starting services


Starting dbus-daemon


Starting Avahi daemon


Found user 'avahi' (UID 86) and group 'avahi' (GID 86).


Successfully dropped root privileges.


avahi-daemon 0.6.32 starting up.


WARNING: No NSS support for mDNS detected, consider installing nss-mdns!


[services.d] done.


Loading service file /etc/avahi/services/sftp-ssh.service.


Loading service file /etc/avahi/services/ssh.service.


*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***


Joining mDNS multicast group on interface hassio.IPv4 with address 172.30.32.1.


New relevant interface hassio.IPv4 for mDNS.


Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.


New relevant interface docker0.IPv4 for mDNS.


Joining mDNS multicast group on interface ens32.IPv4 with address 192.168.120.2.


New relevant interface ens32.IPv4 for mDNS.


Network interface enumeration completed.


Registering new address record for fe80::3c0b:6eff:feba:466a on veth577d469.*.


Registering new address record for fe80::38f8:acff:feb5:d740 on veth0ac1528.*.


Registering new address record for fe80::cc96:f3ff:fe15:bb32 on veth8e1ed92.*.


Registering new address record for fe80::f8ec:1bff:fe5c:7082 on vethf75c663.*.


Registering new address record for fe80::42:9aff:fea1:830d on hassio.*.


Registering new address record for 172.30.32.1 on hassio.IPv4.


Registering new address record for fe80::42:8bff:fe3f:3cff on docker0.*.


Registering new address record for 172.17.0.1 on docker0.IPv4.


Registering new address record for fe80::20c:29ff:feb7:d907 on ens32.*.


Registering new address record for 192.168.120.2 on ens32.IPv4.


Server startup complete. Host name is homeassistant.local. Local service cookie is 3718469549.


-U /homebridge -P /homebridge/node_modules


*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.


*** WARNING *** Please fix your application to use the native API of Avahi!


*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>


*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.


*** WARNING *** Please fix your application to use the native API of Avahi!


*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>


[2018-4-18 15:00:04] Loaded plugin: homebridge-dummy


[2018-4-18 15:00:04] Registering accessory 'homebridge-dummy.DummySwitch'


[2018-4-18 15:00:04] ---


[2018-4-18 15:00:04] Loaded plugin: homebridge-homeassistant


[2018-4-18 15:00:04] Registering platform 'homebridge-homeassistant.HomeAssistant'


[2018-4-18 15:00:04] ---


[2018-4-18 15:00:04] Loaded config.json with 0 accessories and 1 platforms.


[2018-4-18 15:00:04] ---


[2018-4-18 15:00:04] Loading 1 platforms...


[2018-4-18 15:00:04] [HomeAssistant] Initializing HomeAssistant platform...


[2018-4-18 15:00:04] [HomeAssistant] Fetching HomeAssistant devices.


undefined:1


500: Internal Server Error


   ^




SyntaxError: Unexpected token : in JSON at position 3


    at JSON.parse (<anonymous>)


    at Request.request [as _callback] (/homebridge/node_modules/homebridge-homeassistant/index.js:101:38)


    at Request.self.callback (/homebridge/node_modules/request/request.js:186:22)


    at emitTwo (events.js:126:13)


    at Request.emit (events.js:214:7)


    at Request.<anonymous> (/homebridge/node_modules/request/request.js:1163:10)


    at emitOne (events.js:116:13)


    at Request.emit (events.js:211:7)


    at IncomingMessage.<anonymous> (/homebridge/node_modules/request/request.js:1085:12)


    at Object.onceWrapper (events.js:313:30)


-U /homebridge -P /homebridge/node_modules

**Comment by oznu** [comment]
Hi @1043717432,

This error is from the HomeAssistant plugin, you might find someone who can help over on that plugins GitHub issue page.

```
[2018-4-18 15:00:04] [HomeAssistant] Fetching HomeAssistant devices.
undefined:1
500: Internal Server Error
^
SyntaxError: Unexpected token : in JSON at position 3
```

https://github.com/home-assistant/homebridge-homeassistant/issues
