### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by 007xico** [oznu/docker-homebridge#99]
Hi,
can anyone help?

Have Homebridge installed on my Synology and Home kit sees it but if I install the plug in

npm I yeelight.js

and edit the config.json

{
"bridge": {
"name": "YeeBridge",
"username": "18:00:27:40:BC:1B",
"port": 51825,
"pin": "031-45-154"
},

"platforms": [
    {
        "platform" : "yeelight",
        "name" : "yeelight"
    }
]
}

I go on to restart the Homebridge and the home kit on iPhone shows "no response", I delete it but after
 I am not able to add it again.

On the terminal I get this

"Error:The requested platform "yeelight" was not registered by any plugin."

Any ideas ???

**Comment by oznu** [comment]
`yeelight.js` is not a homebridge plugin. You probably want to install `homebridge-yeelight-wifi`?

https://www.npmjs.com/package/homebridge-yeelight-wifi

**Comment by 007xico** [comment]
Great it works, had no idea, still learning.
